Repository cowprotocol/cowswap, pull requests merged in 2022-08, with the labels that each got.

#911 Release 1.20.1
  public/favicon.png
  public/images/og-meta-cowswap.png
  src/custom/components/Header/styled.ts
  src/custom/theme/baseTheme.tsx
  src/custom/theme/cowSwapAssets.ts
  src/custom/theme/styled.d.ts
Labels: RELEASE

#966 Added Account header dropdown
  src/components/SearchModal/styleds.tsx
  src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/custom/components/SearchModal/CommonBases/index.ts
  src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
  src/custom/components/Tokens/FiatBalanceCell.tsx
  src/custom/components/Tokens/TokensTableRow.tsx
  src/custom/constants/mainMenu.ts
  src/custom/pages/Account/Affiliate.tsx
  src/custom/pages/Account/Tokens/TokensOverview.tsx
  src/custom/pages/Account/index.tsx
Labels: Account

#948 Return to 2 account pages
  src/components/SearchModal/styleds.tsx
  src/custom/components/Modal/index.ts
  src/custom/components/NotificationBanner/index.tsx
  src/custom/components/Page/index.tsx
  src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/custom/components/SearchModal/CommonBases/index.ts
  src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
  src/custom/components/SideMenu/index.tsx
  src/custom/components/Tokens/FiatBalanceCell.tsx
  src/custom/components/Tokens/TokensTable.tsx
  src/custom/components/Tokens/TokensTableRow.tsx
  src/custom/constants/index.ts
  src/custom/constants/mainMenu.ts
  src/custom/pages/Account/Affiliate.tsx
  src/custom/pages/Account/Balances.tsx
  src/custom/pages/Account/Governance.tsx
  src/custom/pages/Account/LockedGnoVesting/index.tsx
  src/custom/pages/Account/Menu.tsx
  src/custom/pages/Account/Tokens/TokensOverview.tsx
  src/custom/pages/Account/Tokens/styled.ts
  src/custom/pages/Account/index.tsx
  src/custom/pages/Account/styled.tsx
  src/custom/state/connection/hooks.ts
  src/custom/state/user/hooks/index.ts
  src/custom/state/user/reducer.ts
Labels: Account

#958 Improve nps orderid
  src/custom/state/orders/middleware.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/utils/appzi.ts
Labels: WebSquad

#988 Fix for ToC link
  src/custom/components/WalletModal/index.tsx
Labels: WebSquad

#991 Fix for safe transaction details
  src/custom/hooks/useWalletInfo.ts
  src/custom/state/gnosisSafe/updater.tsx
Labels: WebSquad

#986 Revert z-index and fix for Coinbase
  src/custom/components/Header/HeaderMod.tsx
  src/custom/connection/index.ts
Labels: WebSquad

#993 Fix graphql generated files
  package.json
  src/custom/pages/Account/AddressSelector.tsx
  src/custom/pages/Account/ens/index.ts
  src/custom/pages/Account/ens/types.ts
  src/hooks/useFeeTierDistribution.ts
  src/hooks/usePoolTickData.ts
  src/state/application/updater.ts
  src/state/data/enhanced.ts
  yarn.lock
Labels: WebSquad

#995 Update twitter link
  README.md
  public/index.html
  src/custom/components/SideBanner/index.tsx
  src/custom/constants/index.ts
  src/custom/pages/Claim/ClaimingStatus.tsx
  src/custom/pages/Faq/TokenFaq.tsx
Labels: app:CowSwap, Protofire

#996 Misc fixes
  src/custom/components/AccountDetails/index.tsx
  src/custom/hooks/useCowBalanceAndSubsidy.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/swap/hooks.tsx
Labels: WebSquad
