Repository cowprotocol/cowswap, pull requests merged in 2022-09, with the labels that each got.

#1003 Release 1.12.0 RC.1
  cypress-custom/integration/swapMod.ts
  src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/swap/hooks.tsx
Labels: RELEASE, WebSquad

#1017 Release 1.21.0-RC.3
  src/custom/pages/Account/styled.tsx
Labels: RELEASE, WebSquad

#1032 Toast notification position
  src/custom/components/Popups/PopupsMod.tsx
Labels: app:CowSwap, Medium, Protofire

#1064 [ETH-FLOW] Address comments
  src/custom/components/AccountDetails/styled.ts
  src/custom/components/swap/EthFlow/WrapCard.tsx
  src/custom/components/swap/EthFlow/helpers.ts
  src/custom/components/swap/EthFlow/index.tsx
  src/custom/hooks/useSwapCallback.ts
  src/custom/pages/Swap/SwapMod.tsx
Labels: R&D

#1049 [SWAP REFACTORING #5] code review fixes
  package.json
  src/components/AddressInputPanel/index.tsx
  src/components/swap/SwapHeader.tsx
  src/custom/components/swap/EthFlow/index.tsx
  src/custom/hooks/Tokens/TokensMod.ts
  src/custom/hooks/usePriceImpact/index.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/pages/NewSwap/components/SwapForm.tsx
  src/custom/pages/NewSwap/helpers/initSwapStateFromUrl.ts
  src/custom/pages/NewSwap/helpers/tradeReceiveAmount.ts
  src/custom/pages/NewSwap/hooks/useSetupSwapState.ts
  src/custom/pages/NewSwap/hooks/useSwapCurrenciesAmounts.ts
  src/custom/pages/NewSwap/index.tsx
  src/custom/pages/NewSwap/propsChecker.ts
  src/custom/pages/NewSwap/pureComponents/AddRecipient.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/__fixtures__/CurrencyInputPanel.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/defaultCurrencyInputProps.ts
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/index.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/__fixtures__/CurrencySelectButton.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/index.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/styled.tsx
  src/custom/pages/NewSwap/pureComponents/ReceiveAmount/index.tsx
  src/custom/pages/NewSwap/styled.tsx
  src/custom/pages/NewSwap/warnings.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/components/ApproveButton.tsx
  src/custom/pages/Swap/components/CompatibilityIssuesWarning.tsx
  src/custom/pages/Swap/components/SwapButton/SwapButton.tsx
  src/custom/pages/Swap/helpers/getSwapButtonState.ts
  src/custom/pages/Swap/hooks/useHandleSwap.ts
  src/custom/pages/Swap/hooks/useSwapButtonContext.ts
  src/custom/pages/Swap/swapFlow/index.ts
  src/custom/pages/Swap/swapFlow/types.ts
  src/custom/pages/Swap/swapFlow/useSwapFlowContext.ts
  src/custom/state/swap/hooks.tsx
  src/hooks/Tokens.ts
  src/pages/Swap/index.tsx
  yarn.lock
Labels: WebSquad

#1041 [SWAP REFACTORING #4.5] new swap page, cosmos fixtures and documentation
  cypress-custom/integration/swap.test.ts
  cypress-custom/integration/swapMod.ts
  package.json
  src/components/AddressInputPanel/index.tsx
  src/components/swap/SwapHeader.tsx
  src/cosmos.decorator.tsx
  src/custom/components/swap/EthFlow/README.md
  src/custom/components/swap/EthFlow/ethFlow.puml
  src/custom/components/swap/EthFlow/index.tsx
  src/custom/hooks/Tokens/TokensMod.ts
  src/custom/hooks/usePriceImpact/index.ts
  src/custom/hooks/useSwapCallback.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/pages/NewSwap/components/SwapForm.tsx
  src/custom/pages/NewSwap/components/__fixtures__/SwapForm.tsx
  src/custom/pages/NewSwap/helpers/initSwapStateFromUrl.ts
  src/custom/pages/NewSwap/helpers/tradeReceiveAmount.ts
  src/custom/pages/NewSwap/hooks/useSetupSwapState.ts
  src/custom/pages/NewSwap/hooks/useSwapCurrenciesAmounts.ts
  src/custom/pages/NewSwap/index.tsx
  src/custom/pages/NewSwap/propsChecker.ts
  src/custom/pages/NewSwap/pureComponents/AddRecipient.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyArrowSeparator/__fixtures__/CurrencyArrowSeparator.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyArrowSeparator/styled.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/__fixtures__/CurrencyInputPanel.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/defaultCurrencyInputProps.ts
  src/custom/pages/NewSwap/pureComponents/CurrencyInputPanel/index.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/__fixtures__/CurrencySelectButton.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/index.tsx
  src/custom/pages/NewSwap/pureComponents/CurrencySelectButton/styled.tsx
  src/custom/pages/NewSwap/pureComponents/ReceiveAmount/index.tsx
  src/custom/pages/NewSwap/pureComponents/TradeRates/__fixtures__/TradeRates.tsx
  src/custom/pages/NewSwap/styled.tsx
  src/custom/pages/NewSwap/warnings.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/pages/Swap/components/ApproveButton.tsx
  src/custom/pages/Swap/components/CompatibilityIssuesWarning.tsx
  src/custom/pages/Swap/components/Price.tsx
  src/custom/pages/Swap/components/SwapButton/SwapButton.tsx
  src/custom/pages/Swap/helpers/getSwapButtonState.ts
  src/custom/pages/Swap/hooks/useHandleSwap.ts
  src/custom/pages/Swap/hooks/useSwapButtonContext.ts
  src/custom/pages/Swap/swapFlow/README.md
  src/custom/pages/Swap/swapFlow/index.ts
  src/custom/pages/Swap/swapFlow/swapFlow.puml
  src/custom/pages/Swap/swapFlow/types.ts
  src/custom/pages/Swap/swapFlow/useSwapFlowContext.ts
  src/custom/state/swap/hooks.tsx
  src/hooks/Tokens.ts
  src/pages/Swap/index.tsx
  yarn.lock
Labels: WebSquad

#978 977/deprecate rinkeby
  .env
  .env.production
  README.md
  src/custom/api/gnosisProtocol/hooks.ts
  src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
  src/custom/components/UnsupportedNetworkMessage/index.tsx
  src/custom/connection/index.ts
  src/custom/hooks/useApproveCallback/useApproveCallbackMod.ts
  src/custom/state/enhancedTransactions/updater/CancelReplaceTxUpdater.tsx
  src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/GpOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/utils/blocknative.ts
  src/custom/utils/supportedChainId.ts
Labels: On_hold, WebSquad

#1086 Dune analytics URL
  README.md
  public/index.html
  src/custom/constants/index.ts
Labels: app:CowSwap, Bug, Medium, Protofire

#1091 Add goerli ens subgraph support
  src/custom/pages/Account/ens/index.ts
Labels: Enhancement, Protofire, Goerli

#1122 Improve blocknative sdk error reporting
  src/custom/utils/blocknative.ts
Labels: Protofire

#974 Keep last orderId on state when popup is closed
  src/custom/components/Popups/FollowPendingTxPopup/index.tsx
  src/custom/components/Web3Status/Web3StatusMod.tsx
  src/custom/hooks/useRecentActivity.ts
  src/custom/state/application/atoms.ts
  src/custom/state/application/hooks.ts
Labels: app:CowSwap, Protofire
