Repository cowprotocol/cowswap, pull requests merged in 2022-10, with the labels that each got.

#1147 Release/1.23 RC.1
  .env.production
  src/cow-react/modules/swap/containers/NewSwapWidget/propsChecker.ts
  src/cow-react/modules/swap/containers/SwapButtons/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/custom/state/swap/hooks.tsx
Labels: RELEASE

#1198 Release 1.23 - Fix text
  src/custom/components/Popups/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx
Labels: RELEASE

#1121 [1.23] Refactor ETH Flow - base PR for fixes ready for 1.23 release
  src/cosmos.decorator.tsx
  src/cow-react/modules/swap/containers/NewSwapModals/index.tsx
  src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx
  src/cow-react/modules/swap/containers/SwapButtons/ApproveButtons.tsx
  src/cow-react/modules/swap/containers/SwapButtons/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/custom/components/AccountDetails/Transaction/styled.ts
  src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/custom/components/swap/EthFlow/WrapCard.tsx
  src/custom/components/swap/EthFlow/WrappingVisualisation.tsx
  src/custom/components/swap/EthFlow/containers/EthFlowModal/hooks/useEthFlowActions.ts
  src/custom/components/swap/EthFlow/containers/EthFlowModal/hooks/useRemainingNativeTxsAndCosts.ts
  src/custom/components/swap/EthFlow/containers/EthFlowModal/hooks/useSetupEthFlow.ts
  src/custom/components/swap/EthFlow/containers/EthFlowModal/index.tsx
  src/custom/components/swap/EthFlow/containers/EthFlowModal/utils/getDerivedEthFlowState.ts
  src/custom/components/swap/EthFlow/helpers.ts
  src/custom/components/swap/EthFlow/index.tsx
  src/custom/components/swap/EthFlow/mocks.ts
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/ActionButton.tsx
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/EthFlowModalBottomContent.tsx
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/EthFlowModalTopContent.tsx
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/configs.ts
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/index.cosmos.tsx
  src/custom/components/swap/EthFlow/pure/EthFlowModalContent/index.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/WrapCard.cosmos.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/WrapCard.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/WrappingPreview.cosmos.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/WrappingPreview.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/index.tsx
  src/custom/components/swap/EthFlow/pure/WrappingPreview/styled.tsx
  src/custom/components/swap/EthFlow/state/ethFlowContextAtom.ts
  src/custom/components/swap/EthFlow/transactionsMocks.ts
  src/custom/components/swap/EthFlow/typings.ts
  src/custom/constants/index.ts
  src/custom/hooks/useApproveCallback/index.ts
  src/custom/hooks/useApproveCallback/useApproveCallbackMod.ts
  src/custom/hooks/useRecentActivity.ts
  src/custom/hooks/useRemainingNativeTxsAndCosts.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/lib/hooks/useCurrencyLogoURIs/useCurrencyLogoURIsMod.ts
  src/custom/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/swap/hooks.tsx
Labels: RELEASE

#1081 Enable the ProgressBar with the safe wallet
  src/cow-react/abis/SafeWalletContract.json
  src/cow-react/abis/types/SafeWalletContract.d.ts
  src/cow-react/abis/types/factories/SafeWalletContract__factory.ts
  src/cow-react/abis/types/index.ts
  src/cow-react/modules/application/containers/App/Updaters.tsx
  src/custom/components/AccountDetails/Transaction/ActivityDetails.tsx
  src/custom/components/OrderProgressBar/ContentByExecutionState.tsx
  src/custom/components/OrderProgressBar/index.tsx
  src/custom/components/TransactionConfirmationModal/index.tsx
  src/custom/hooks/useContract/index.ts
  src/custom/state/gnosisSafe/updater.tsx
  src/custom/state/orders/reducer.ts
  src/custom/utils/blocks.ts
Labels: app:CowSwap, Protofire

#1225 [ETH-FLOW V2] - Banner component + cosmos
  src/cow-react/modules/swap/containers/EthFlow/EthFlowBanner.tsx
  src/cow-react/modules/swap/containers/EthFlow/index.tsx
  src/cow-react/modules/swap/containers/RowSlippage/index.tsx
  src/cow-react/modules/swap/containers/SwapButtons/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useDetectNativeToken.ts
  src/cow-react/modules/swap/hooks/useIsEthFlow.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.cosmos.tsx
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/styleds.ts
  src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
  src/custom/hooks/useStablecoinPrice/index.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/state/swap/hooks.tsx
Labels: R&D

#1212 [ETH-FLOW V2] - Slippage updater
  src/cow-react/modules/application/containers/App/Updaters.tsx
  src/cow-react/modules/swap/containers/EthFlow/EthFlowBanner.tsx
  src/cow-react/modules/swap/containers/EthFlow/index.tsx
  src/cow-react/modules/swap/containers/RowSlippage/index.tsx
  src/cow-react/modules/swap/containers/SwapButtons/index.tsx
  src/cow-react/modules/swap/containers/TradeBasicDetails/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useDetectNativeToken.ts
  src/cow-react/modules/swap/hooks/useIsEthFlow.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.cosmos.tsx
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/styleds.ts
  src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.cosmos.tsx
  src/cow-react/modules/swap/pure/Row/RowSlippageContent/index.tsx
  src/cow-react/modules/swap/pure/TradeRates/index.tsx
  src/cow-react/modules/swap/pure/TradeSummary/index.tsx
  src/cow-react/modules/swap/state/EthFlow/updater.tsx
  src/cow-react/pages/Swap/SwapMod.tsx
  src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
  src/custom/components/TransactionSettings/index.tsx
  src/custom/hooks/useStablecoinPrice/index.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/state/swap/hooks.tsx
Labels: R&D

#1247 [ETH-FLOW-V2] 1243 - Insufficient balance NATIVE/WRAPPED
  src/custom/hooks/useWrapCallback.ts
Labels: R&D

#1246 [ETH-FLOW-V2] - 1242 - Fix slippage updating
  src/cow-react/modules/swap/state/EthFlow/updater.tsx
Labels: R&D

#1252 [EFV2] Fix order digest
  src/cow-react/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/utils/signatures.ts
Labels: R&D

#1235 [ETH-FLOW-V2] Add contract addreses/abis/types
  .github/workflows/ci.yml
  package.json
  scripts/contracts_add_export.js
  src/cow-react/abis/types/ethflow/CoWSwapEthFlow.d.ts
  src/cow-react/abis/types/ethflow/common.d.ts
  src/cow-react/abis/types/ethflow/factories/CoWSwapEthFlow__factory.ts
  src/cow-react/abis/types/ethflow/index.ts
  src/cow-react/abis/types/index.ts
  src/cow-react/modules/swap/containers/SwapButtons/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useEthFlowContext.ts
  src/cow-react/modules/swap/hooks/useFlowContext.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/hooks/useSwapFlowContext.ts
  src/cow-react/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
  src/cow-react/modules/swap/services/common/steps/addPendingOrderStep.ts
  src/cow-react/modules/swap/services/common/steps/analytics.ts
  src/cow-react/modules/swap/services/common/steps/swapErrorHelper.ts
  src/cow-react/modules/swap/services/common/types.ts
  src/cow-react/modules/swap/services/ethFlow/index.ts
  src/cow-react/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
  src/cow-react/modules/swap/services/swapFlow/index.ts
  src/cow-react/modules/swap/services/swapFlow/steps/presignOrderStep.ts
  src/cow-react/modules/swap/services/utils/logger.ts
  src/custom/constants/index.ts
  src/custom/hooks/useContract/index.ts
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/mocks.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/user/hooks/index.ts
  src/custom/utils/signatures.ts
  src/custom/utils/trade.ts
  yarn.lock
Labels: R&D, High Prio

#1248 Fix: don't reset network to mainnet after page reload
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersStateFromUrl.ts
  src/cow-react/modules/limitOrders/hooks/useSetupLimitOrdersState.ts
Labels: limit-order

#1258 [Limit orders] allowance check and approve
  src/cow-react/common/containers/TradeApprove/TradeApproveButton.tsx
  src/cow-react/common/containers/TradeApprove/TradeApproveWidget.tsx
  src/cow-react/common/containers/TradeApprove/index.ts
  src/cow-react/common/containers/TradeApprove/tradeApproveStateAtom.ts
  src/cow-react/common/containers/TradeApprove/useTradeApproveCallback.ts
  src/cow-react/common/containers/TradeApprove/useTradeApproveState.ts
  src/cow-react/common/hooks/useApproveCallback.ts
  src/cow-react/common/hooks/useApproveState.ts
  src/cow-react/common/hooks/useTradeSpenderAddress.ts
  src/cow-react/common/pure/ApproveButton/index.cosmos.tsx
  src/cow-react/common/pure/ApproveButton/index.tsx
  src/cow-react/common/pure/HelpCircle/index.cosmos.tsx
  src/cow-react/common/pure/HelpCircle/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/swap/containers/EthFlow/hooks/useEthFlowActions.ts
  src/cow-react/modules/swap/containers/EthFlow/index.tsx
  src/cow-react/modules/swap/containers/NewSwapModals/index.tsx
  src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx
  src/cow-react/modules/swap/containers/SwapButtons/ApproveButtons.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/pure/ApproveButton/index.cosmos.tsx
  src/cow-react/modules/swap/pure/SwapButtons/index.cosmos.tsx
  src/cow-react/modules/swap/pure/SwapButtons/index.tsx
  src/cow-react/modules/swap/pure/SwapButtons/styled.tsx
  src/cow-react/pages/Account/Affiliate.tsx
  src/cow-react/pages/Account/Balances.tsx
  src/cow-react/pages/Account/LockedGnoVesting/index.tsx
  src/cow-react/pages/Swap/SwapMod.tsx
  src/custom/components/ArrowWrapperLoader/index.tsx
  src/custom/hooks/useApproveCallback/useApproveCallbackMod.ts
Labels: limit-order

#1232 [Limit orders] render balances and fiat amounts
  src/cow-react/common/hooks/useSafeMemo.test.ts
  src/cow-react/common/hooks/useSafeMemo.ts
  src/cow-react/common/pure/CurrencyInputPanel/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts
  src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useQuoteRequestParams.ts
Labels: limit-order

#1234 [Limit orders] confirm screen
  src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  src/cow-react/common/pure/CurrencyInputPanel/CurrencyPreview.tsx
  src/cow-react/common/pure/CurrencyInputPanel/index.cosmos.tsx
  src/cow-react/common/pure/CurrencyInputPanel/index.ts
  src/cow-react/common/pure/CurrencyInputPanel/typings.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/styled.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/styled.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/styled.tsx
  src/cow-react/modules/swap/pure/CurrencySelectButton/index.tsx
  src/cow-react/modules/swap/pure/CurrencySelectButton/styled.tsx
Labels: limit-order

#1238 [Limit orders] pending and submitted modals
  src/cow-react/common/containers/TradeApprove/TradeApproveButton.tsx
  src/cow-react/common/containers/TradeApprove/TradeApproveWidget.tsx
  src/cow-react/common/containers/TradeApprove/index.ts
  src/cow-react/common/containers/TradeApprove/tradeApproveStateAtom.ts
  src/cow-react/common/containers/TradeApprove/useTradeApproveCallback.ts
  src/cow-react/common/containers/TradeApprove/useTradeApproveState.ts
  src/cow-react/common/hooks/useApproveCallback.ts
  src/cow-react/common/hooks/useApproveState.ts
  src/cow-react/common/hooks/useTradeSpenderAddress.ts
  src/cow-react/common/pure/ApproveButton/index.cosmos.tsx
  src/cow-react/common/pure/ApproveButton/index.tsx
  src/cow-react/common/pure/HelpCircle/index.cosmos.tsx
  src/cow-react/common/pure/HelpCircle/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/state.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/services/tradeFlow/index.ts
  src/cow-react/modules/swap/containers/EthFlow/hooks/useEthFlowActions.ts
  src/cow-react/modules/swap/containers/EthFlow/index.tsx
  src/cow-react/modules/swap/containers/NewSwapModals/index.tsx
  src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx
  src/cow-react/modules/swap/containers/SwapButtons/ApproveButtons.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/pure/ApproveButton/index.cosmos.tsx
  src/cow-react/modules/swap/pure/SwapButtons/index.cosmos.tsx
  src/cow-react/modules/swap/pure/SwapButtons/index.tsx
  src/cow-react/modules/swap/pure/SwapButtons/styled.tsx
  src/cow-react/pages/Account/Affiliate.tsx
  src/cow-react/pages/Account/Balances.tsx
  src/cow-react/pages/Account/LockedGnoVesting/index.tsx
  src/cow-react/pages/Swap/SwapMod.tsx
  src/custom/components/ArrowWrapperLoader/index.tsx
  src/custom/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
  src/custom/components/TransactionConfirmationModal/index.cosmos.tsx
  src/custom/hooks/useApproveCallback/useApproveCallbackMod.ts
Labels: limit-order
