Repository cowprotocol/cowswap, pull requests merged in 2022-06, with the labels that each got.

#630 [Analytics] Sign flow: send to wallet & Cancel & Error
  src/custom/constants/index.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/pages/Swap/SwapMod.tsx
Labels: RELEASE

#649 add locked gno cow claim anayltics
  src/custom/pages/Profile/LockedGnoVesting/index.tsx
Labels: RELEASE

#631 [analytics] Order execution
  src/custom/state/orders/middleware.ts
Labels: RELEASE

#658 Add missing events for claiming COW
  src/custom/pages/Profile/LockedGnoVesting/index.tsx
Labels: RELEASE

#678 Scroll left table on page change
  src/custom/components/Tokens/TokensTable.tsx
Labels: Account

#454 Integrate Order progress bar
  src/custom/assets/cow-swap/ammslogo/1inch.png
  src/custom/assets/cow-swap/ammslogo/baoswap.png
  src/custom/assets/cow-swap/ammslogo/honeyswap.png
  src/custom/assets/cow-swap/ammslogo/paraswap.png
  src/custom/assets/cow-swap/ammslogo/sushi.png
  src/custom/assets/cow-swap/ammslogo/swapr.png
  src/custom/assets/cow-swap/ammslogo/uniswap.png
  src/custom/components/AMMsLogo/index.tsx
  src/custom/components/AccountDetails/Transaction/ActivityDetails.tsx
  src/custom/components/AccountDetails/Transaction/CancelButton.tsx
  src/custom/components/AccountDetails/Transaction/OrderProgressBar/index.tsx
  src/custom/components/AccountDetails/Transaction/OrderProgressBar/styled.ts
  src/custom/components/AccountDetails/Transaction/OrderProgressBar/utils.ts
  src/custom/components/AccountDetails/Transaction/StatusDetails.tsx
  yarn.lock
Labels: Protofire

#698 Fix swap.cow.fi appData bug
  .env
  .env.production
Labels: RELEASE

#708 [ 🔥 😮‍💨 H O T F I X ] 1.15.5
  .env
  .env.production
  .gitignore
  cypress-custom/integration/swapMod.ts
  src/custom/hooks/web3.ts
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/utils/price.ts
Labels: RELEASE

#742 [USD Price] Add sentry reporting to USD price feeds
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/state/sentry/updater/index.ts
  src/custom/utils/logging/index.ts
Labels: SENTRY

#761 🐨 🐨 🐨 RELEASE 1.17.0
  package.json
  src/custom/api/gnosisProtocol/api.ts
  src/custom/api/gnosisProtocol/errors/QuoteError.ts
  src/custom/components/ErrorBoundary/ErrorBoundaryMod.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Popups/ListUpdatePopupMod.tsx
  src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
  src/custom/components/SearchModal/ImportList/ImportListMod.tsx
  src/custom/components/SearchModal/ManageLists/ManageListsMod.tsx
  src/custom/components/Settings/SettingsMod.tsx
  src/custom/components/TransactionSettings/TransactionSettingsMod.tsx
  src/custom/components/WalletModal/WalletModalMod.tsx
  src/custom/components/analytics/GoogleAnalyticsReporter.tsx
  src/custom/hooks/useUSDCPrice/index.ts
  src/custom/hooks/useWrapCallback.ts
  src/custom/pages/Account/LockedGnoVesting/index.tsx
  src/custom/pages/Swap/SwapMod.tsx
  src/custom/state/orders/middleware.ts
  src/custom/state/sentry/updater/index.ts
  src/custom/state/swap/TradeGp.ts
  src/custom/state/swap/trade.test.ts
  src/custom/theme/baseTheme.tsx
  src/custom/utils/analytics/index.ts
  src/custom/utils/analytics/listEvents.ts
  src/custom/utils/analytics/settingsEvents.ts
  src/custom/utils/analytics/themeEvents.ts
  src/custom/utils/analytics/transactionEvents.ts
  src/custom/utils/analytics/walletEvents.ts
  src/custom/utils/logging/index.ts
  src/custom/utils/price.ts
  yarn.lock
Labels: RELEASE
