Repository cowprotocol/cowswap, pull requests merged in 2022-04, with the labels that each got.

#366 Progress of execution UI
  src/custom/assets/cow-swap/ammslogo/1inch.png
  src/custom/assets/cow-swap/ammslogo/paraswap.png
  src/custom/assets/cow-swap/ammslogo/sushi.png
  src/custom/assets/cow-swap/ammslogo/uniswap.png
  src/custom/components/AMMsLogo/index.tsx
  src/custom/components/AccountDetails/Transaction/ActivityDetails.tsx
  src/custom/components/AccountDetails/Transaction/styled.ts
Labels: app:CowSwap, Enhancement, Protofire

#367 Adds a ENS address selector to the Profile page
  codegen.yml
  package.json
  src/custom/components/AffiliateStatusCheck/index.tsx
  src/custom/hooks/useParseReferralQueryParam.ts
  src/custom/pages/Profile/AddressSelector.tsx
  src/custom/pages/Profile/ens.ts
  src/custom/pages/Profile/index.tsx
  src/custom/state/affiliate/actions.ts
  src/custom/state/affiliate/hooks.ts
  src/custom/state/affiliate/reducer.ts
  yarn.lock
Labels: Protofire

#477 Hotfix 1.13.2 - happy birthday 🍰
  cypress-custom/integration/fee.test.ts
  cypress-custom/integration/swapMod.ts
  cypress/integration/lists.test.ts
  public/audio/success-alex.mp3
  public/audio/success-martin.mp3
  src/constants/misc.ts
  src/custom/assets/cow-swap/anniversary-icons.png
  src/custom/components/SideBanner/index.tsx
  src/custom/utils/sound.ts
  src/index.tsx
  src/theme/components.tsx
Labels: RELEASE

#446 Fix unhandled exception on updaters
  src/custom/state/orders/updaters/CancelledOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/updaters/utils.ts
Labels: Auto-merge
