Repository cowprotocol/cowswap, pull requests merged in 2023-04, with the labels that each got.

#2230 Estimated execution price for partial fills - minimal
  src/custom/state/orders/utils.ts
Labels: partial fills

#2197 🌛 Feature/partial fills
  src/cow-react/common/hooks/useCategorizeRecentActivity.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
  src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts
  src/cow-react/modules/limitOrders/pure/ReceiptModal/FilledField.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/StatusField.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/SurplusField.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
  src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
  src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/styled.ts
  src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts
  src/cow-react/modules/limitOrders/utils/calculatePercentageInRelationToReference.ts
  src/cow-react/modules/limitOrders/utils/getOrderExecutedAmounts.ts
  src/cow-react/modules/limitOrders/utils/getOrderSurplus.ts
  src/cow-react/modules/limitOrders/utils/isOrderFilled.ts
  src/cow-react/modules/limitOrders/utils/isPartiallyFilled.ts
  src/cow-react/modules/swap/hooks/useFlowContext.ts
  src/custom/hooks/useRecentActivity.ts
  src/custom/state/orders/actions.ts
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/SpotPricesUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/utils.test.ts
  src/custom/state/orders/utils.ts
  src/custom/utils/trade.ts
Labels: partial fills

#2103 Ledger-live connector
  package.json
  src/cow-react/modules/account/containers/AccountDetails/index.tsx
  src/cow-react/modules/wallet/api/assets/ledger.svg
  src/cow-react/modules/wallet/api/types.ts
  src/cow-react/modules/wallet/api/utils/connection.ts
  src/cow-react/modules/wallet/web3-react/connection/asyncConnector.ts
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
  src/cow-react/modules/wallet/web3-react/connection/ledger.tsx
  src/cow-react/modules/wallet/web3-react/connectors/LedgerConnector.tsx
  src/custom/utils/misc.ts
  src/state/connection/reducer.ts
  yarn.lock
Labels: Wallets

#2236 [Limit orders] Removed excessive currencyId update
  src/cow-react/modules/limitOrders/hooks/useOnCurrencySelection.ts
Labels: Bug

#2253 Fix network switching detection
  src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Labels: Bug

#2243 Fixed wrong limit orders form state after network change
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useQuoteRequestParams.ts
Labels: Bug

#2201 Wallet modal UI improvements
  src/cow-react/modules/wallet/api/pure/ConnectWalletOption/index.tsx
  src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
  src/cow-react/modules/wallet/api/pure/WalletModal/styled.tsx
Labels: Wallets

#2226 Add ZenGo wallet banner
  src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
  src/cow-react/modules/wallet/api/pure/ZengoBanner/index.tsx
  src/cow-react/modules/wallet/api/pure/ZengoBanner/styled.ts
  src/cow-react/modules/wallet/web3-react/containers/WalletModal/index.tsx
Labels: Wallets

#2247 Feature/partial fills estimating price again
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/utils.test.ts
  src/custom/state/orders/utils.ts
Labels: partial fills

#2266 Feature/partial fills fix executes at receipt
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
Labels: partial fills

#2269 Feature/partial fills explicit order type
  src/cow-react/modules/limitOrders/pure/ReceiptModal/OrderTypeField.tsx
Labels: partial fills

#2251 Ignore GnosisSafe NoSafeContext error
  src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Labels: Bug

#2270 Feature/partial fills settings
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/Settings/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/Settings/index.tsx
  src/cow-react/modules/limitOrders/state/limitOrdersSettingsAtom.ts
Labels: partial fills

#2267 Feature/partial fills no low fee warning when unfillable
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
Labels: partial fills

#2198 Added trust wallet implementation
  src/cow-react/modules/account/containers/AccountDetails/index.tsx
  src/cow-react/modules/wallet/api/assets/trust.png
  src/cow-react/modules/wallet/api/types.ts
  src/cow-react/modules/wallet/api/utils/connection.ts
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
  src/cow-react/modules/wallet/web3-react/connection/tally.tsx
  src/cow-react/modules/wallet/web3-react/connection/trust.tsx
  src/cow-react/modules/wallet/web3-react/connection/walletConnect.tsx
  src/cow-react/modules/wallet/web3-react/connectors/Injected/index.tsx
  src/cow-react/modules/wallet/web3-react/containers/WalletModal/index.tsx
  src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
  src/react-app-env.d.ts
  src/state/application/updater.ts
  src/state/connection/reducer.ts
Labels: Wallets

#2254 Disable Swap form while loading best price
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/custom/hooks/useRefetchPriceCallback.tsx
Labels: Bug

#2272 Feature/partial fills chose type on submit
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/styled.tsx
  src/cow-react/modules/limitOrders/state/limitOrdersSettingsAtom.ts
  src/cow-react/modules/limitOrders/state/partiallyFillableOverride.ts
Labels: partial fills

#2285 Feature/partial fills order type tooltip
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
  src/cow-react/modules/limitOrders/pure/Settings/index.tsx
  src/cow-react/pages/Faq/LimitOrdersFaq.tsx
  src/cow-react/pages/Faq/TradingFaq.tsx
Labels: partial fills

#2305 Added settingsState to limit orders memo component props
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
Labels: partial fills

#2297 Add feature flag for Partial fills using Launch Darkly
  .env
  .env.production
  package.json
  src/cow-react/common/hooks/useFeatureFlags.ts
  src/cow-react/constants/launchDarkly.ts
  src/cow-react/modules/application/containers/App/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/SettingsWidget/index.tsx
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/styled.tsx
  src/cow-react/modules/limitOrders/pure/Settings/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/Settings/index.tsx
  yarn.lock
Labels: partial fills

#2304 Fixes some bugs with trust wallet
  src/cow-react/modules/account/containers/AccountDetails/index.tsx
  src/cow-react/modules/wallet/api/assets/trust.png
  src/cow-react/modules/wallet/api/assets/trust.svg
  src/cow-react/modules/wallet/web3-react/connection/trust.tsx
  src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx
Labels: Wallets

#2343 Disable Ledger on Mobile
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
Labels: RELEASE
