Repository cowprotocol/cowswap, pull requests merged in 2023-12, with the labels that each got.

#3413 [1] feat: multicall library
  apps/cowswap-frontend/tsconfig.json
  libs/abis/src/abis/Multicall3.json
  libs/abis/src/generated/custom/Multicall3.ts
  libs/abis/src/generated/custom/factories/Multicall3__factory.ts
  libs/abis/src/generated/custom/index.ts
  libs/abis/src/index.ts
  libs/multicall/.babelrc
  libs/multicall/.eslintrc.json
  libs/multicall/README.md
  libs/multicall/jest.config.ts
  libs/multicall/package.json
  libs/multicall/project.json
  libs/multicall/src/const.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/hooks/useSingleContractMultipleData.ts
  libs/multicall/src/index.ts
  libs/multicall/src/multiCall.ts
  libs/multicall/src/utils/getMulticallContract.ts
  libs/multicall/tsconfig.json
  libs/multicall/tsconfig.lib.json
  libs/multicall/tsconfig.spec.json
  libs/multicall/vite.config.ts
  tsconfig.base.json
Labels: Balances

#3414 [2] feat: balances and allowances lib
  apps/cowswap-frontend/tsconfig.json
  libs/abis/src/index.ts
  libs/balances-and-allowances/.babelrc
  libs/balances-and-allowances/.eslintrc.json
  libs/balances-and-allowances/README.md
  libs/balances-and-allowances/jest.config.ts
  libs/balances-and-allowances/package.json
  libs/balances-and-allowances/project.json
  libs/balances-and-allowances/src/hooks/useCurrencyAmountBalance.ts
  libs/balances-and-allowances/src/hooks/useNativeCurrencyAmount.ts
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/hooks/useNativeTokensBalances.ts
  libs/balances-and-allowances/src/hooks/useTokenBalanceForAccount.ts
  libs/balances-and-allowances/src/hooks/useTokensAllowances.ts
  libs/balances-and-allowances/src/hooks/useTokensBalances.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/allowancesAtom.ts
  libs/balances-and-allowances/src/state/balancesAtom.ts
  libs/balances-and-allowances/src/types.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.ts
  libs/balances-and-allowances/tsconfig.json
  libs/balances-and-allowances/tsconfig.lib.json
  libs/balances-and-allowances/tsconfig.spec.json
  libs/balances-and-allowances/vite.config.ts
  libs/multicall/src/index.ts
  libs/multicall/src/multicall.ts
  tsconfig.base.json
Labels: Balances

#3417 [4] feat(balances): update balances for priority tokens
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveButton.tsx
  apps/cowswap-frontend/src/common/containers/TradeApprove/index.ts
  apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveState.ts
  apps/cowswap-frontend/src/common/hooks/useApproveState.ts
  apps/cowswap-frontend/src/legacy/hooks/useTokenAllowance.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/hooks/TransactionHooksMod.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/utils/getOrderParams.test.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/utils/getOrderParams.ts
  apps/cowswap-frontend/src/modules/swap/containers/EthFlow/index.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/tokens/hooks/useEnoughBalance.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/usePriorityTokenAddresses.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/allowancesAtom.ts
  libs/balances-and-allowances/src/state/balancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.ts
  libs/balances-and-allowances/src/updaters/PriorityTokensUpdater.ts
Labels: Balances

#3489 feat: prettify token name displaying for Gnosis chain
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/TokenName/index.tsx
  libs/ui/src/pure/TokenName/sanitizeTokenName.ts
Labels: RELEASE

#3488 fix(trade): don't display fiat value when there is no amount
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
Labels: RELEASE

#3476 chore(main): release 1.51.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3495 chore(main): release 1.51.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3472 chore: change fee label
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
Labels: Zero fee

#3469 feat(swap): set fee=zero for swap orders
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
Labels: Zero fee

#3505 fix(wallet): fix ledger live
  libs/wallet/src/constants.ts
  libs/wallet/src/web3-react/connection/walletConnectV2.tsx
  libs/wallet/src/web3-react/connectors/LedgerConnector.tsx
  package.json
  yarn.lock
Labels: RELEASE

#3509 fix: remove ledger integration because it's hacked
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  libs/wallet/src/api/types.ts
  libs/wallet/src/api/utils/connection.ts
  libs/wallet/src/index.ts
  libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts
  libs/wallet/src/web3-react/utils/isChainAllowed.ts
  package.json
  yarn.lock
Labels: RELEASE

#3510 chore(main): release 1.51.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3513 fix(deps): upgrade wagmi version to remove ledger lib
  package.json
  yarn.lock
Labels: RELEASE

#3518 fix(classic-eth-flow): wrap no longer clears input amounts
  apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
  apps/cowswap-frontend/src/modules/swap/pure/EthFlow/WrappingPreview/WrapCard.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts
Labels: RELEASE

#3521 fix(twap): deduplicate safe transactions with the same order
  apps/cowswap-frontend/src/modules/twap/updaters/TwapOrdersUpdater.tsx
Labels: RELEASE

#3501 chore(release): 1.52.0
  apps/cowswap-frontend/src/common/containers/FeatureGuard/index.tsx
  apps/cowswap-frontend/src/common/updaters/orders/GpOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/mocks/tradeStateMock.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitHasEnoughAllowance.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/hooks/useTokensForOrdersList.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/EthFlow/WrappingPreview/WrapCard.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedPartOrders.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedTwapOrders.ts
  apps/cowswap-frontend/src/modules/twap/updaters/CreatedInOrderBookOrdersUpdater.tsx
  apps/cowswap-frontend/src/modules/twap/updaters/TwapOrdersUpdater.tsx
  apps/cowswap-frontend/src/modules/twap/utils/mapPartOrderToStoreOrder.ts
  apps/cowswap-frontend/src/modules/twap/utils/mapTwapOrderToStoreOrder.ts
  apps/cowswap-frontend/src/utils/orderUtils/getTokenFromMapping.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/wallet/src/api/utils/connection.ts
  libs/wallet/src/constants.ts
  libs/wallet/src/web3-react/connection/walletConnectV2.tsx
  libs/wallet/src/web3-react/connectors/LedgerConnector.tsx
  libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
Labels: RELEASE

#3525 chore(main): release 1.52.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3529 fix: remove ledger connector completely
  libs/wallet/src/web3-react/connection/ledger.tsx
  libs/wallet/src/web3-react/connectors/LedgerConnector.tsx
Labels: RELEASE

#3531 feat: replace time column labels with nouns
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
Labels: RELEASE

#3534 fix: use button text color for error button
  libs/ui/src/pure/Button/index.tsx
Labels: RELEASE

#3536 fix: eth-flow stepper missing border
  apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/StatusIcon.tsx
Labels: RELEASE

#3537 fix: unsupported token button text color
  apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx
  apps/cowswap-frontend/src/legacy/theme/styled.d.ts
Labels: RELEASE

#3538 fix: terms and conditions link hover color
  apps/cowswap-frontend/src/legacy/components/Card/index.tsx
  apps/cowswap-frontend/src/legacy/theme/components.tsx
Labels: RELEASE

#3539 chore(main): release 1.53.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3542 chore(main): release 1.53.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3555 feat(sepolia): quote strategy config
  config/barn/strategies/strategy-11155111.json
  config/production/strategies/strategy-11155111.json
Labels: Sepolia

#3554 Release/1.54.0
  apps/cowswap-frontend/src/common/hooks/useApproveCallback.ts
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
  apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/useApproveCallbackMod.ts
  apps/cowswap-frontend/src/legacy/hooks/useRefetchPriceCallback.tsx
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/reducer.test.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/reducer.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
  apps/cowswap-frontend/src/modules/swap/helpers/logSwapParams.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/transactionsMocks.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrdersAuthMulticall.ts
  apps/cowswap-frontend/src/utils/orderUtils/getIsComposableCowOrder.ts
  libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts
  libs/balances-and-allowances/src/hooks/useNativeCurrencyAmount.ts
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/hooks/useTokensAllowances.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/allowancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.ts
  libs/wallet/src/web3-react/connection/injected.tsx
Labels: RELEASE

#3556 chore(main): release 1.54.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3562 fix(permit): replace permit signer used for quoting
  libs/permit-utils/src/const.ts
Labels: RELEASE

#3563 chore(main): release 1.54.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending
