Repository cowprotocol/cowswap, pull requests merged in 2023-09, with the labels that each got.

#3113 fix(twap): load TWAP part details
  apps/cowswap-frontend/src/cowSdk.ts
Labels: RELEASE

#3114 fix(price-impact): display unknown price impact warning only when there is no data
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapWarningsContext.ts
Labels: RELEASE

#3116 fix(swap): reset state after network changes
  apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
  apps/cowswap-frontend/src/legacy/state/swap/reducer.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts
Labels: RELEASE

#3107 Reduce queries from unfillable updater
  apps/cowswap-frontend/src/legacy/state/orders/consts.ts
  apps/cowswap-frontend/src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
Labels: RELEASE

#3117 fix: add html space chars before banner token symbols
  apps/cowswap-frontend/src/common/pure/InlineBanner/banners.tsx
Labels: RELEASE

#3121 fix(usd-amount): delete token from queue only if there are no subscribers left
  apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Labels: RELEASE

#3124 fix: surplus modal flickering
  apps/cowswap-frontend/src/common/hooks/useGetSurplusFiatValue.ts
Labels: RELEASE

#3125 fix: fix mapping network name from URL query to chainId
  apps/cowswap-frontend/src/utils/getCurrentChainIdFromUrl.test.ts
  apps/cowswap-frontend/src/utils/getCurrentChainIdFromUrl.ts
Labels: RELEASE

#3126 chore(main): release 1.47.0-RC.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3127 fix(usd-price): handle individual token price query failure
  apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Labels: RELEASE

#3128 chore(release): 1.47.0
  apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
Labels: RELEASE

#3129 chore(main): release 1.47.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3102 feat(permit): check allowance
  apps/cowswap-frontend/src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/state/price/updater.ts
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/permit/const.ts
  apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts
  apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
  apps/cowswap-frontend/src/modules/tokens/hooks/useEnoughBalance.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useQuoteParams.ts
Labels: permit

#3135 feat(permit): feature flag
  apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
Labels: permit

#3138 feat(permit): better gas limit estimation
  apps/cowswap-frontend/src/modules/permit/const.ts
  apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts
Labels: permit

#3130 Custom recipient warning banner
  apps/cowswap-frontend/src/common/hooks/useCategorizeRecentActivity.ts
  apps/cowswap-frontend/src/common/pure/ButtonSecondary/index.tsx
  apps/cowswap-frontend/src/common/pure/Icon/index.cosmos.tsx
  apps/cowswap-frontend/src/common/pure/Icon/index.tsx
  apps/cowswap-frontend/src/common/pure/InlineBanner/banners.tsx
  apps/cowswap-frontend/src/common/pure/InlineBanner/index.cosmos.tsx
  apps/cowswap-frontend/src/common/pure/InlineBanner/index.tsx
  apps/cowswap-frontend/src/common/state/receiverWalletBannerVisibility/atom.ts
  apps/cowswap-frontend/src/common/state/receiverWalletBannerVisibility/hooks.ts
  apps/cowswap-frontend/src/common/state/receiverWalletBannerVisibility/index.ts
  apps/cowswap-frontend/src/legacy/components/swap/ConfirmSwapModal/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/FeeInformationTooltip.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/styled.ts
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/account/containers/Transaction/styled.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/FallbackHandlerWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/SwapPriceDifferenceWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/UnsupportedWalletWarning.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedTwapOrders.ts
  apps/cowswap-frontend/src/modules/twap/utils/emulateTwapAsOrder.ts
  apps/cowswap-frontend/src/utils/orderUtils/parseOrder.ts
Labels: RELEASE

#3140 feat(permit): update outdated permits
  apps/cowswap-frontend/src/modules/permit/utils/checkIsTokenPermittable.ts
  apps/cowswap-frontend/src/modules/permit/utils/generatePermitHook.ts
  apps/cowswap-frontend/src/modules/permit/utils/getPermitDeadline.ts
  apps/cowswap-frontend/src/modules/permit/utils/getPermitUtilsInstance.ts
Labels: permit

#3142 feat(permit): limit orders
  apps/cowswap-frontend/src/mocks/tradeStateMock.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
  apps/cowswap-frontend/src/modules/permit/index.ts
  apps/cowswap-frontend/src/modules/permit/types.ts
  apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
Labels: permit

#3161 Hotfix 1.47.1 follow ups
  apps/cowswap-frontend/.env.production
Labels: RELEASE

#3155 feat(permit): quote by order type
  apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersDerivedState.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitOrdersDerivedState.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/permit/const.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useDerivedTradeState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeTypeInfo.ts
  apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/twap/services/createTwapOrderTxs.test.ts
Labels: permit

#3159 Hotfix/1.47.1
  .github/workflows/vercel.yml
  README.md
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/.env.production
  apps/cowswap-frontend/src/common/pure/ButtonSecondary/index.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/QuestionHelperMod.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/index.tsx
  apps/cowswap-frontend/src/legacy/constants/networks.ts
  apps/cowswap-frontend/src/legacy/hooks/useFetchListCallback.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.test.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/types.ts
  apps/cowswap-frontend/src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  apps/cowswap-frontend/src/modules/twap/services/createTwapOrderTxs.ts
Labels: RELEASE

#3172 chore(main): release 1.47.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3166 feat(tokens): new UI component for token select modal
  apps/cowswap-frontend/src/legacy/components/InfoIcon/index.tsx
  apps/cowswap-frontend/src/modules/orders/hooks/useTokensForOrdersList.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenModal/mocks.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenModal/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/AllTokensList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/AllTokensList/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/state/tokensListAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  apps/cowswap-frontend/src/modules/tokensList/updaters/TokensListUpdater.ts
Labels: Tokens
