Repository cowprotocol/cowswap, pull requests merged in 2023-03, with the labels that each got.

#2031 [3] Creation and expiration date of the order in the order table
  src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
  src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
  src/cow-react/modules/limitOrders/pure/Orders/orders.mock.ts
  src/cow-react/modules/limitOrders/pure/ReceiptModal/StatusField.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
  src/cow-react/modules/limitOrders/utils/ordersSorter.ts
  src/custom/hooks/useTimeAgo.ts
Labels: limit-order

#2030 [2] Execution price on Limit orders confirmation screen
  src/cow-react/common/pure/RateInfo/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
  src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/hooks/useExecutionPriceFiat.ts
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersPriceImpactParams.ts
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/limitOrders/index.ts
  src/cow-react/modules/limitOrders/pure/ExecutionPrice/index.tsx
  src/cow-react/modules/limitOrders/pure/ExecutionPriceTooltip/index.tsx
  src/cow-react/modules/limitOrders/pure/ExecutionPriceTooltip/styled.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTablePagination.tsx
  src/cow-react/modules/limitOrders/pure/Orders/orders.mock.ts
  src/cow-react/modules/limitOrders/pure/RateTooltip/index.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/StatusField.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
  src/cow-react/modules/limitOrders/state/executionPriceAtom.ts
  src/cow-react/modules/limitOrders/state/limitRateAtom.ts
  src/cow-react/modules/limitOrders/updaters/ExecutionPriceUpdater/index.tsx
  src/cow-react/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/index.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useQuoteRequestParams.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/index.tsx
  src/cow-react/modules/limitOrders/updaters/QuoteUpdater/index.tsx
  src/cow-react/modules/limitOrders/utils/getSellAmountWithFee.ts
  src/cow-react/modules/limitOrders/utils/ordersSorter.ts
  src/cow-react/pages/LimitOrders/index.tsx
  src/custom/hooks/useTimeAgo.ts
Labels: limit-order

#2118 Fix focusing of search input in walletconnect modal
  src/cow-react/common/pure/Modal/ModalMod.tsx
Labels: Bug

#2115 Fix CurrencyInputPanel value changes
  src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
Labels: Bug

#2116 Don't update limit order amounts when price was entered by user
  src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
  src/cow-react/modules/limitOrders/hooks/useUpdateActiveRate.ts
  src/cow-react/modules/limitOrders/updaters/InitialPriceUpdater/index.tsx
Labels: Bug

#2123 Invert tokens when user selected the same token
  src/cow-react/modules/trade/hooks/useOnCurrencySelection.ts
Labels: Bug

#2119 UnsupportedToken state for the swap form
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/pure/SwapButtons/index.tsx
  src/custom/hooks/useRefetchPriceCallback.tsx
Labels: Bug

#2120 Fix detection of Gnosis transactions
  src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts
  src/custom/state/enhancedTransactions/hooks/index.ts
Labels: Bug

#2099 Add Alpha wallet option
  src/cow-react/modules/wallet/api/assets/alpha.svg
  src/cow-react/modules/wallet/api/pure/ConnectWalletOption/index.tsx
  src/cow-react/modules/wallet/api/types.ts
  src/cow-react/modules/wallet/api/utils/connection.ts
  src/cow-react/modules/wallet/web3-react/connection/alpha.tsx
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
  src/cow-react/modules/wallet/web3-react/connection/walletConnect.tsx
  src/state/connection/reducer.ts
Labels: Wallets

#2100 Add view more button
  src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
Labels: Wallets

#2107 Simplify Gnosis Safe state
  src/cow-react/modules/application/containers/App/Updaters.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/swap/hooks/useFlowContext.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/wallet/api/hooks.ts
  src/cow-react/modules/wallet/api/state.ts
  src/cow-react/modules/wallet/api/types.ts
  src/cow-react/modules/wallet/web3-react/hooks/useGnosisSafeSdkInfo.test.tsx
  src/cow-react/modules/wallet/web3-react/hooks/useGnosisSafeSdkInfo.ts
  src/cow-react/modules/wallet/web3-react/updater.ts
  src/custom/components/EnhancedTransactionLink/index.tsx
  src/custom/components/TransactionConfirmationModal/index.tsx
  src/custom/hooks/useActivityDerivedState.ts
  src/custom/hooks/useGnosisSafeInfo.ts
  src/custom/state/enhancedTransactions/hooks/index.ts
  src/custom/state/gnosisSafe/atoms.ts
  src/custom/state/gnosisSafe/updater.tsx
Labels: Auto-merge, Wallets

#2108 Limit UI prototype orders table 6 indicator status 2
  src/cow-react/common/hooks/usePrice.ts
  src/cow-react/modules/application/containers/App/Updaters.tsx
  src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/hooks/useGetInitialPrice.ts
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
  src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/Orders/index.tsx
  src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.test.ts
  src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.ts
  src/cow-react/modules/orders/state/pendingOrdersPricesAtom.ts
  src/cow-react/modules/orders/state/spotPricesAtom.ts
  src/custom/state/orders/consts.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/SpotPricesUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/utils.ts
Labels: limit-order

#2135 Limit UI prototype fix smart quote on table
  src/cow-react/common/hooks/useRateInfoParams.ts
  src/cow-react/common/pure/RateInfo/index.cosmos.tsx
  src/cow-react/common/pure/RateInfo/index.tsx
  src/cow-react/modules/account/containers/Transaction/ActivityDetails.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
  src/cow-react/modules/limitOrders/hooks/useExecutionPriceFiat.ts
  src/cow-react/modules/limitOrders/pure/ExecutionPrice/index.tsx
  src/cow-react/modules/limitOrders/pure/ExecutionPriceTooltip/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
  src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts
  src/cow-react/modules/limitOrders/state/limitRateAtom.ts
  src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts
  src/cow-react/modules/limitOrders/utils/toFraction.ts
  src/cow-react/modules/swap/pure/TradeRates/index.cosmos.tsx
Labels: limit-order

#2091 🎨 Limit UI iteration (styles & functionality)
  src/cow-react/common/pure/TokenAmount/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
Labels: limit-order

#2140 Feature/limit UI update - wire up tooltips
  src/cow-react/common/utils/markets.ts
  src/cow-react/modules/limitOrders/containers/OrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx
  src/cow-react/modules/limitOrders/pure/Orders/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/Orders/index.tsx
  src/cow-react/modules/limitOrders/utils/calculateAmountForRate.ts
  src/cow-react/modules/limitOrders/utils/calculateFractionLikePercentDifference.ts
  src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.test.ts
  src/cow-react/modules/limitOrders/utils/calculateOrderExecutionStatus.ts
  src/cow-react/modules/limitOrders/utils/calculatePriceDifference.test.ts
  src/cow-react/modules/limitOrders/utils/calculatePriceDifference.ts
  src/cow-react/modules/orders/state/pendingOrdersPricesAtom.ts
  src/cow-react/modules/orders/state/spotPricesAtom.ts
  src/cow-react/utils/fractionUtils.ts
  src/cow-react/utils/rawToTokenAmount.ts
  src/custom/constants/index.ts
  src/custom/lib/utils/tryParseCurrencyAmount.ts
  src/custom/state/orders/updaters/SpotPricesUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/custom/state/orders/utils.ts
Labels: limit-order

#2148 Wallet/alpha enabled
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
  src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts
Labels: Wallets

#2156 Fix circular deps for cosmos
  src/cow-react/common/pure/ApproveButton/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/swap/pure/SwapButton/index.tsx
  src/cow-react/modules/swap/pure/SwapButtons/index.tsx
  src/cow-react/modules/swap/pure/SwapButtons/styled.tsx
  src/cow-react/pages/Account/LockedGnoVesting/index.tsx
  src/cow-react/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/custom/components/Button/ButtonMod.tsx
  src/custom/components/Button/index.tsx
  src/custom/components/swap/SwapModalFooter/SwapModalFooterMod.tsx
  src/custom/theme/baseTheme.tsx
  src/custom/theme/enum.ts
  src/custom/theme/index.tsx
  src/custom/theme/styled.d.ts
Labels: Bug

#2157 Wallet/remove view more button
  src/cow-react/modules/wallet/api/pure/WalletModal/index.tsx
  src/cow-react/modules/wallet/web3-react/connection/index.tsx
Labels: RELEASE

#2163 Fix white token symbol on black color text
  src/cow-react/common/pure/TokenAmount/index.tsx
Labels: limit-order

#2162 Do not show high fee warning on limit orders table for market orders
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
Labels: limit-order

#2160 Inverting all prices on order row when any price is clicked
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
Labels: limit-order

#2170 Refactor and add initial swap.cow.fi landing event
  src/custom/components/analytics/events/listEvents.ts
  src/custom/components/analytics/events/otherEvents.ts
  src/custom/components/analytics/events/settingsEvents.ts
  src/custom/components/analytics/events/swapEvents.ts
  src/custom/components/analytics/events/themeEvents.ts
  src/custom/components/analytics/events/transactionEvents.ts
  src/custom/components/analytics/events/walletEvents.ts
  src/custom/components/analytics/hooks/useAnalyticsReporter.ts
  src/custom/components/analytics/index.ts
  src/custom/components/analytics/provider/index.ts
  src/custom/components/analytics/types.ts
Labels: Analytics

#2155 Feature/limit UI - Small sell amount/high fee warning on limit orders widget
  src/cow-react/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/utils/calculatePercentageInRelationToReference.ts
Labels: limit-order

#2167 Feature/limit UI update - #2164 negative price
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/styled.tsx
  src/cow-react/modules/limitOrders/utils/calculatePriceDifference.test.ts
  src/cow-react/modules/limitOrders/utils/calculatePriceDifference.ts
  src/cow-react/utils/amountFormat/index.ts
  src/custom/state/orders/utils.ts
Labels: limit-order

#2202 Fix connect again wallet button
  src/cow-react/abis/types/index.ts
  src/cow-react/modules/wallet/web3-react/containers/WalletModal/index.tsx
Labels: RELEASE

#2189 Feature/partial fills update beta banner
  src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/index.tsx
  src/cow-react/modules/limitOrders/pure/UnlockLimitOrders/styled.ts
Labels: partial fills

#2199 Feature/partial fills show banner again
  src/cow-react/modules/limitOrders/state/limitOrdersAtom.ts
Labels: partial fills

#2210 Fixed bought token symbol on limit orders table receipt
  src/cow-react/modules/limitOrders/pure/ReceiptModal/FilledField.tsx
Labels: partial fills

#2220 Feature/partial fills order type
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/pure/OrderType/index.tsx
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
Labels: partial fills

#2217 Showing a different button text when expert mode is enabled
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
Labels: partial fills

#2225 Feature/partial fills messages and warnings
  src/cow-react/common/hooks/useCategorizeRecentActivity.ts
  src/cow-react/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
  src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/EstimatedExecutionPrice.tsx
  src/cow-react/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts
  src/cow-react/modules/limitOrders/utils/calculatePercentageInRelationToReference.ts
  src/custom/hooks/useRecentActivity.ts
  src/custom/state/orders/actions.ts
  src/custom/state/orders/hooks.ts
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
  src/custom/state/orders/updaters/SpotPricesUpdater.ts
  src/custom/state/orders/updaters/UnfillableOrdersUpdater.ts
Labels: partial fills

#2231 Cancelled status takes precedence on limit orders table
  src/cow-react/modules/limitOrders/pure/OrderStatusBox/index.tsx
Labels: partial fills

#2232 Showing custom execution price label on receipt for partial fills
  src/cow-react/modules/limitOrders/pure/ReceiptModal/index.tsx
Labels: partial fills

#2222 Feature/partial fills show surplus
  src/cow-react/modules/limitOrders/pure/ReceiptModal/SurplusField.tsx
  src/cow-react/modules/limitOrders/utils/getOrderExecutedAmounts.ts
  src/cow-react/modules/limitOrders/utils/getOrderSurplus.ts
Labels: partial fills
