Repository cowprotocol/cowswap, pull requests merged in 2023-08, with the labels that each got.

#2963 feat: enhance twap banner
  src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
Labels: RELEASE

#2945 chore(solver-colocation): use verified quote
  package.json
  src/api/gnosisProtocol/api.ts
  src/api/gnosisProtocol/legacy/types.ts
  src/legacy/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/legacy/hooks/usePriceImpact/useQuoteAndSwap.ts
  src/legacy/hooks/useRefetchPriceCallback.tsx
  src/legacy/hooks/useStablecoinPrice/index.ts
  src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/legacy/state/price/updater.ts
  src/legacy/utils/price.ts
  src/legacy/utils/priceLegacy.ts
  src/modules/tokens/hooks/useEnoughBalance.ts
  src/modules/tokens/index.ts
  src/modules/tradeQuote/hooks/useQuoteParams.ts
  yarn.lock
Labels: RELEASE

#2975 feat(verify-quote): add feature flag
  src/common/hooks/featureFlags/useVerifiedQuotesEnabled.ts
  src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/legacy/state/price/updater.ts
  src/modules/tradeQuote/hooks/useQuoteParams.ts
Labels: RELEASE

#2933 chore(app-data): upload app-data document
  package.json
  src/legacy/state/orders/updaters/UnfillableOrdersUpdater.ts
  src/mocks/tradeStateMock.ts
  src/modules/appData/appData-module.md
  src/modules/appData/hooks.ts
  src/modules/appData/index.ts
  src/modules/appData/services/index.ts
  src/modules/appData/state/atoms.ts
  src/modules/appData/types.tsx
  src/modules/appData/updater/UploadToIpfsUpdater.ts
  src/modules/application/containers/App/Updaters.tsx
  src/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/modules/limitOrders/services/safeBundleFlow/index.ts
  src/modules/limitOrders/services/tradeFlow/index.ts
  src/modules/limitOrders/services/types.ts
  src/modules/swap/hooks/useFlowContext.ts
  src/modules/swap/services/ethFlow/index.ts
  src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  src/modules/swap/services/swapFlow/index.ts
  src/modules/swap/services/types.ts
  src/modules/twap/hooks/useCreateTwapOrder.ts
  yarn.lock
Labels: RELEASE

#2980 fix(swap): change quote amount for price impact calculation on Gnosis chain
  src/legacy/hooks/useStablecoinPrice/index.ts
Labels: RELEASE

#2973 fix(twap): always display price diff warning
  src/modules/twap/containers/TwapFormWarnings/index.tsx
Labels: TWAP

#2986 fix: upload appData to ETH flow
  src/modules/appData/services/index.ts
  src/modules/appData/types.tsx
  src/modules/appData/updater/UploadToIpfsUpdater.ts
  src/modules/appData/updater/useAppDataUpdater.ts
  src/modules/swap/hooks/useFlowContext.ts
  src/modules/swap/services/ethFlow/index.ts
  src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  src/modules/swap/services/types.ts
Labels: RELEASE

#2981 fix(twap): don't redirect to swap when feature-flag value is not defined
  src/common/hooks/useIsAdvancedOrdersEnabled.ts
  src/modules/mainMenu/hooks.ts
  src/pages/AdvancedOrders/index.tsx
Labels: RELEASE

#2994 feat(twap): fetch first 200 transactions using pagination
  src/modules/twap/hooks/useFetchTwapOrdersFromSafe.ts
  src/modules/twap/services/fetchTwapOrdersFromSafe.ts
Labels: TWAP

#3004 Release 1.44-RC.1
  src/common/hooks/useGetSurplusFiatValue.ts
  src/modules/appData/services/index.ts
  src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  src/modules/twap/hooks/useFetchTwapOrdersFromSafe.ts
  src/modules/twap/services/fetchTwapOrdersFromSafe.ts
Labels: RELEASE

#3016 fix: pass account address along with other verified quote params
  src/modules/tradeQuote/hooks/useQuoteParams.ts
Labels: RELEASE

#3013 chore(main): release 1.44.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3028 fix(twap): load unknown tokens from blockchain
  src/legacy/state/orders/updaters/GpOrdersUpdater.ts
  src/modules/orders/hooks/useTokensForOrdersList.ts
  src/modules/orders/index.ts
  src/modules/orders/utils/getTokensListFromOrders.ts
  src/modules/twap/hooks/useAllEmulatedOrders.ts
  src/modules/twap/hooks/useEmulatedPartOrders.ts
  src/modules/twap/hooks/useEmulatedTwapOrders.ts
  src/modules/twap/hooks/useTwapOrdersTokens.ts
  src/modules/twap/updaters/CreatedInOrderBookOrdersUpdater.tsx
  src/utils/orderUtils/getTokenFromMapping.ts
Labels: RELEASE, TWAP

#3030 chore(main): release 1.44.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3034 chore(release): hotfix 1.44.2
  src/modules/trade/pure/TradeNumberInput/index.tsx
  src/modules/twap/pure/CustomDeadlineSelector/index.tsx
  src/modules/twap/pure/CustomDeadlineSelector/styled.tsx
  src/modules/twap/state/swapAmountDifferenceAtom.ts
Labels: RELEASE

#3035 chore(main): release 1.44.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3031 feat(twap): update contract addresses
  src/modules/advancedOrders/const.ts
  src/modules/twap/const.ts
  src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  src/modules/twap/services/__snapshots__/extensibleFallbackSetupTxs.test.tsx.snap
  src/modules/twap/services/verifyExtensibleFallback.test.ts
Labels: RELEASE

#3039 chore(release): hotfix 1.44.3
  src/modules/advancedOrders/const.ts
  src/modules/twap/const.ts
  src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  src/modules/twap/services/__snapshots__/extensibleFallbackSetupTxs.test.tsx.snap
  src/modules/twap/services/verifyExtensibleFallback.test.ts
Labels: RELEASE

#3040 chore(main): release 1.44.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3041 fix: disable limit orders state sync between tabs
  src/jotaiStore.ts
  src/modules/advancedOrders/state/advancedOrdersAtom.ts
  src/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/modules/limitOrders/state/limitOrdersRawStateAtom.ts
  src/modules/limitOrders/state/limitOrdersSettingsAtom.ts
  src/modules/twap/state/twapOrdersListAtom.ts
  src/modules/twap/state/twapOrdersSettingsAtom.ts
  src/modules/twap/state/twapPartOrdersAtom.ts
Labels: RELEASE

#3020 feat(wallets): trezor wallet support
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveButton.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/LegacyConfirmationPendingContent.tsx
  apps/cowswap-frontend/src/legacy/state/gas/hooks.ts
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/gasPirce/index.ts
  apps/cowswap-frontend/src/modules/gasPirce/state/gasPriceAtom.ts
  apps/cowswap-frontend/src/modules/tokens/hooks/useCurrencyBalance.ts
  apps/cowswap-frontend/src/modules/wallet/api/assets/trezor.svg
  apps/cowswap-frontend/src/modules/wallet/api/container/HwAccountIndexSelector/index.tsx
  apps/cowswap-frontend/src/modules/wallet/api/pure/AccountIndexSelect/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/wallet/api/pure/AccountIndexSelect/index.tsx
  apps/cowswap-frontend/src/modules/wallet/api/pure/PendingView/index.tsx
  apps/cowswap-frontend/src/modules/wallet/api/pure/WalletModal/index.tsx
  apps/cowswap-frontend/src/modules/wallet/api/state.ts
  apps/cowswap-frontend/src/modules/wallet/api/types.ts
  apps/cowswap-frontend/src/modules/wallet/api/updaters/HwAccountIndexUpdater.tsx
  apps/cowswap-frontend/src/modules/wallet/api/utils/connection.ts
  apps/cowswap-frontend/src/modules/wallet/api/utils/getHwAccount.ts
  apps/cowswap-frontend/src/modules/wallet/index.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/connection/index.tsx
  apps/cowswap-frontend/src/modules/wallet/web3-react/connection/trezor.tsx
  apps/cowswap-frontend/src/modules/wallet/web3-react/connectors/TrezorConnector/TrezorProvider.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/connectors/TrezorConnector/getAccountsList.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/connectors/TrezorConnector/index.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/connectors/TrezorConnector/sendTransactionHandler.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/connectors/TrezorConnector/signTypedDataHandler.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/containers/WalletModal/index.tsx
  apps/cowswap-frontend/src/modules/wallet/web3-react/hooks/useEagerlyConnect.ts
  apps/cowswap-frontend/src/modules/wallet/web3-react/types.ts
  apps/cowswap-frontend/vite.config.ts
  package.json
  yarn.lock
Labels: Wallets

#3049 chore(main): release 1.45.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3053 chore(main): release 1.44.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3055 chore(main): release 1.44.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3057 chore(main): release 1.44.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3062 chore(main): release 1.44.7
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3065 chore(main): release 1.45.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3075 chore(main): release 1.45.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3087 chore(main): release 1.46.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
