Repository cowprotocol/cowswap, pull requests merged in 2023-05, with the labels that each got.

#2400 feat: component TradeWidget to unify layout of all trade widgets
  src/cow-react/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersTradeState.ts
  src/cow-react/modules/swap/pure/SwapForm/index.cosmos.tsx
  src/cow-react/modules/swap/pure/SwapForm/index.tsx
  src/cow-react/modules/trade/containers/TradeWidget/index.tsx
  src/cow-react/modules/trade/containers/TradeWidget/styled.tsx
  src/cow-react/modules/trade/types/TradeWidgetState.ts
Labels: TWAP

#2434 feat(tx-bundling): enable bundled approval + presign for Safe App on SWAP
  src/cow-react/api/gnosisSafe/hooks/useSafeApiKit.ts
  src/cow-react/api/gnosisSafe/hooks/useSafeSdk.ts
  src/cow-react/api/gnosisSafe/index.ts
  src/cow-react/common/hooks/useApproveCallback.ts
  src/cow-react/common/hooks/useIsTxBundlingEnabled.ts
  src/cow-react/common/hooks/useNeedsApproval.ts
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  src/cow-react/modules/limitOrders/pure/Orders/utils/getOrderParams.ts
  src/cow-react/modules/operations/bundle/buildApproveTx.ts
  src/cow-react/modules/operations/bundle/buildPresignTx.ts
  src/cow-react/modules/swap/hooks/useEthFlowContext.ts
  src/cow-react/modules/swap/hooks/useFlowContext.ts
  src/cow-react/modules/swap/hooks/useHandleSwap.test.tsx
  src/cow-react/modules/swap/hooks/useHandleSwap.ts
  src/cow-react/modules/swap/hooks/useSafeBundleFlowContext.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/swap/hooks/useSwapFlowContext.ts
  src/cow-react/modules/swap/services/safeBundleFlow/index.ts
  src/cow-react/modules/swap/services/types.ts
  src/cow-react/modules/wallet/web3-react/hooks/useGnosisSafeSdkInfo.ts
  src/cow-react/modules/wallet/web3-react/hooks/useSafeAppsSdk.ts
  src/cow-react/modules/wallet/web3-react/hooks/useSafeAppsSdkInfo.test.tsx
  src/cow-react/modules/wallet/web3-react/hooks/useSafeAppsSdkInfo.ts
  src/cow-react/modules/wallet/web3-react/updater.ts
  src/cow-react/utils/isEnoughAmount.ts
Labels: tx-bundling

#2446 feat(tx-bundling): enable bundled approval + presign for Safe App on Limit orders
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  src/cow-react/modules/limitOrders/hooks/useSafeBundleFlowContext.ts
  src/cow-react/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  src/cow-react/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/cow-react/modules/limitOrders/services/safeBundleFlow/index.ts
  src/cow-react/modules/limitOrders/services/tradeFlow/index.ts
  src/cow-react/modules/limitOrders/services/types.ts
Labels: tx-bundling

#2453 feat: get UTM codes from URL and add them to the app state and local …
  package.json
  src/cow-react/modules/application/containers/App/index.tsx
  src/cow-react/modules/utm/hooks.ts
  src/cow-react/modules/utm/index.ts
  src/cow-react/modules/utm/state.ts
  src/cow-react/modules/utm/types.ts
  src/hooks/useAppData.ts
  src/state/appData/AppDataInfoUpdater.tsx
  src/utils/appData.ts
  yarn.lock
Labels: RELEASE

#2457 Hotfix 1.36.1
  cypress-custom/integration/limit-orders.test.ts
  cypress-custom/integration/swap.test.ts
  cypress-custom/support/commands.d.ts
  cypress-custom/support/commands.js
  package.json
  src/components/Header/index.tsx
  src/cow-react/modules/application/containers/App/index.tsx
  src/cow-react/modules/swap/hooks/useSwapRawState.ts
  src/cow-react/modules/utm/hooks.ts
  src/cow-react/modules/utm/index.ts
  src/cow-react/modules/utm/state.ts
  src/cow-react/modules/utm/types.ts
  src/hooks/useAppData.ts
  src/state/appData/AppDataInfoUpdater.tsx
  src/state/swap/actions.ts
  src/state/swap/hooks.tsx
  src/state/swap/reducer.ts
  src/utils/appData.ts
  yarn.lock
Labels: RELEASE

#2450 feat: add account address to ga tracking
  src/components/analytics/hooks/useAnalyticsReporter.ts
  src/components/analytics/provider/index.ts
  src/components/analytics/types.ts
  src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md
Labels: Analytics

#2466 feature(tx-bundling): warning banner
  src/cow-react/common/pure/WarningBanner/banners.tsx
  src/cow-react/common/pure/WarningBanner/index.tsx
  src/cow-react/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  src/cow-react/modules/swap/containers/SwapWidget/index.tsx
  src/cow-react/modules/swap/pure/warnings.tsx
Labels: tx-bundling

#2472 feat(tx-bundling): update button content
  src/components/swap/ConfirmSwapModal/ConfirmSwapModalMod.tsx
  src/components/swap/ConfirmSwapModal/index.tsx
  src/components/swap/SwapModalFooter/SwapModalFooterMod.tsx
  src/components/swap/SwapModalFooter/index.tsx
  src/cow-react/common/hooks/useNeedsApproval.ts
  src/cow-react/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  src/cow-react/modules/limitOrders/hooks/useIsSafeApprovalBundle.ts
  src/cow-react/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/cow-react/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  src/cow-react/modules/swap/hooks/useFlowContext.ts
  src/cow-react/modules/swap/pure/SwapButtons/index.tsx
Labels: tx-bundling

#2474 feat(tx-bundling): analytics
  src/components/analytics/events/transactionEvents.ts
  src/components/analytics/types.ts
  src/cow-react/modules/limitOrders/services/safeBundleFlow/index.ts
  src/cow-react/modules/swap/services/safeBundleFlow/index.ts
  src/cow-react/modules/trade/utils/analytics.ts
Labels: tx-bundling

#2487 fix(tx-bundling): fix tx bundling buy order approval
  src/legacy/components/swap/ConfirmSwapModal/index.tsx
  src/modules/swap/hooks/useFlowContext.ts
Labels: tx-bundling

#2479 feature(twap-orders): refactor NumberOfParts and Slippage (9)
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/styled.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
Labels: TWAP

#2460 feat(twap-orders): twap orders deadline updates (8)
  package.json
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/styled.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  yarn.lock
Labels: TWAP

#2455 feat(twap-orders): add parts display to TWAP orders (7)
  package.json
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/styled.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/styled.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  yarn.lock
Labels: TWAP

#2451 feat(twap-orders) add quote fetching loading indicator (6)
  package.json
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/styled.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/styled.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useGetQuote.ts
  src/cow-react/modules/advancedOrders/hooks/useIsQuoteLoading.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersQuoteAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  yarn.lock
Labels: TWAP

#2445 feat(twap-orders) Add quote fetching part 1 (5)
  package.json
  src/cow-react/abis/types/index.ts
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/styled.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/styled.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useGetQuote.ts
  src/cow-react/modules/advancedOrders/hooks/useIsQuoteLoading.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useQuoteParams.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useUpdateCurrencyAmount.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersQuoteAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/updaters/QuoteUpdater/index.tsx
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/containers/TradeWidget/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  src/cow-react/pages/AdvancedOrders/index.tsx
  src/cow-react/utils/featureFlags.ts
  yarn.lock
Labels: TWAP

#2438 feat(twap-orders): update no. of parts error and responsivnes (4)
  package.json
  src/constants/index.ts
  src/cow-react/abis/types/index.ts
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/styled.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/NumberOfParts/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/styled.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/index.tsx
  src/cow-react/modules/advancedOrders/containers/Slippage/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useGetQuote.ts
  src/cow-react/modules/advancedOrders/hooks/useIsQuoteLoading.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useQuoteParams.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useUpdateCurrencyAmount.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersQuoteAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/updaters/QuoteUpdater/index.tsx
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/containers/TradeWidget/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  src/cow-react/pages/AdvancedOrders/index.tsx
  src/cow-react/utils/featureFlags.ts
  yarn.lock
Labels: TWAP

#2436 feat(twap-orders): No. of parts field (2)
  package.json
  src/constants/index.ts
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/cow-react/modules/advancedOrders/containers/AdvancedOrdersWidget/styled.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/CustomDeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineDisplayPart/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineInput/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/deadlines.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useDisplayDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/hooks/useUpdateDeadline.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/index.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/Selector.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/pure/styled.ts
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/styled.tsx
  src/cow-react/modules/advancedOrders/containers/DeadlineSelector/types.ts
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/index.tsx
  src/cow-react/modules/advancedOrders/containers/PartsDisplay/styled.tsx
  src/cow-react/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageError.ts
  src/cow-react/modules/advancedOrders/hooks/useDisplaySlippageValue.ts
  src/cow-react/modules/advancedOrders/hooks/useGetQuote.ts
  src/cow-react/modules/advancedOrders/hooks/useIsQuoteLoading.ts
  src/cow-react/modules/advancedOrders/hooks/useParseNumberOfParts.ts
  src/cow-react/modules/advancedOrders/hooks/useParseSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useParts.ts
  src/cow-react/modules/advancedOrders/hooks/useQuoteParams.ts
  src/cow-react/modules/advancedOrders/hooks/useSetSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useSinglePartTime.ts
  src/cow-react/modules/advancedOrders/hooks/useSlippage.ts
  src/cow-react/modules/advancedOrders/hooks/useUpdateCurrencyAmount.ts
  src/cow-react/modules/advancedOrders/pure/NumericalInput/index.tsx
  src/cow-react/modules/advancedOrders/pure/WidgetField/index.tsx
  src/cow-react/modules/advancedOrders/state/advancedOrdersAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersQuoteAtom.ts
  src/cow-react/modules/advancedOrders/state/advancedOrdersSettingsAtom.ts
  src/cow-react/modules/advancedOrders/updaters/QuoteUpdater/index.tsx
  src/cow-react/modules/advancedOrders/utils/displayTime.tsx
  src/cow-react/modules/trade/containers/TradeWidget/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/index.tsx
  src/cow-react/modules/trade/pure/TradeNumberInput/styled.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/index.tsx
  src/cow-react/modules/trade/pure/TradeWidgetField/styled.tsx
  src/cow-react/pages/AdvancedOrders/index.tsx
  src/cow-react/utils/featureFlags.ts
  yarn.lock
Labels: TWAP

#2501 fix: formatting issue breaking when reminder carries over
  src/cow-react/common/pure/TokenAmount/index.tsx
  src/cow-react/utils/amountFormat/index.test.ts
  src/cow-react/utils/amountFormat/index.ts
Labels: RELEASE

#2505 fix: fix app crashing while calculating price impact
  src/cow-react/abis/types/index.ts
  src/cow-react/common/services/getQuoteCurrency/index.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts
  src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts
  src/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/utils/price.ts
Labels: RELEASE

#2511 chore: release hotfix/1.37.1
  package.json
  src/cow-react/abis/types/index.ts
  src/cow-react/common/pure/TokenAmount/index.tsx
  src/cow-react/common/services/getQuoteCurrency/index.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts
  src/cow-react/modules/limitOrders/utils/calculateExecutionPrice.ts
  src/cow-react/utils/amountFormat/index.test.ts
  src/cow-react/utils/amountFormat/index.ts
  src/hooks/usePriceImpact/useFallbackPriceImpact.ts
  src/utils/price.ts
Labels: RELEASE

#2493 feat(tx-bundling): add banner when approving for Save via WC
  src/common/pure/InlineBanner/banners.tsx
  src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  src/modules/swap/containers/SwapWidget/index.tsx
  src/modules/swap/pure/warnings.tsx
  src/modules/wallet/web3-react/hooks/useWalletMetadata.ts
Labels: RELEASE, tx-bundling

#2462 feat(smart-contract-orders): hide presign order until wallet returns tx for Safe app limit bundling tx
  src/legacy/hooks/useRecentActivity.ts
  src/legacy/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx
  src/legacy/state/orders/actions.ts
  src/legacy/state/orders/hooks.ts
  src/legacy/state/orders/middleware.tsx
  src/legacy/state/orders/utils.ts
  src/modules/limitOrders/containers/OrdersWidget/hooks/useLimitOrdersList.ts
  src/modules/limitOrders/services/safeBundleFlow/index.ts
Labels: tx-bundling

#2519 fix: bring back change after bad merge
  src/common/services/getQuoteCurrency/index.ts
Labels: RELEASE

#2504 feat(twap): twap order creation services
  src/abis/ComposableCoW.json
  src/abis/ExtensibleFallbackHandler.json
  src/modules/advancedOrders/const.ts
  src/modules/advancedOrders/hooks/useComposableCowContract.ts
  src/modules/twap/README.md
  src/modules/twap/const.ts
  src/modules/twap/docs/twap-creation.drawio.svg
  src/modules/twap/hooks/useTwapOrderCreationContext.ts
  src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  src/modules/twap/services/createTwapOrderTxs.test.ts
  src/modules/twap/services/createTwapOrderTxs.ts
  src/modules/twap/services/settleTwapOrder.test.ts
  src/modules/twap/services/settleTwapOrder.ts
  src/modules/twap/types.ts
Labels: TWAP

#2513 feat(twap): services to verify and setup extensible fallback handler
  src/abis/GPv2Settlement.json
  src/abis/SignatureVerifierMuxer.json
  src/modules/advancedOrders/const.ts
  src/modules/advancedOrders/index.ts
  src/modules/twap/hooks/useExtensibleFallbackContext.ts
  src/modules/twap/services/__snapshots__/extensibleFallbackSetupTxs.test.ts.snap
  src/modules/twap/services/createTwapOrderTxs.ts
  src/modules/twap/services/extensibleFallbackSetupTxs.test.ts
  src/modules/twap/services/extensibleFallbackSetupTxs.ts
  src/modules/twap/services/getSignatureVerifierContract.ts
  src/modules/twap/services/setupExtensibleFallbackHandler.test.ts
  src/modules/twap/services/setupExtensibleFallbackHandler.ts
  src/modules/twap/services/verifyExtensibleFallback.test.ts
  src/modules/twap/services/verifyExtensibleFallback.ts
Labels: TWAP

#2529 feat(usdt-approval): ✨ add zero approval flow to safe bundles
  src/common/hooks/useShouldZeroApprove/shouldZeroApprove.ts
  src/common/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
  src/modules/limitOrders/services/safeBundleFlow/index.ts
  src/modules/operations/bundle/buildZeroApproveTx.ts
  src/modules/swap/services/safeBundleFlow/index.ts
Labels: RELEASE

#2528 fix(usdt-approval): :bug: fix modal not dismissing when close is clicked
  src/common/containers/ZeroApprovalModal/ZeroApprovalModal.tsx
Labels: RELEASE

#2536 Fix message for revoke
  src/common/hooks/useApproveCallback.ts
Labels: RELEASE

#2543 fix(usdt-approval): 🐛 fix wallet connect with safe causing same nonce to appear twice
  src/common/hooks/useZeroApprove.ts
  src/common/utils/pollUntil.ts
  src/common/utils/wait.ts
Labels: RELEASE

#2539 fix: fix approval edge case
  src/common/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
  src/lib/hooks/swap/useSwapApproval.ts
  src/lib/hooks/useApproval.ts
Labels: RELEASE

#2547 feat(trade): move import token and approval modals to TradeWidget
  src/common/containers/ImportTokenModal/index.tsx
  src/common/containers/TradeApprove/TradeApproveModal.tsx
  src/common/containers/TradeApprove/index.ts
  src/common/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
  src/common/hooks/useShouldZeroApproveLimit.ts
  src/common/hooks/useShouldZeroApproveSwap.ts
  src/legacy/state/swap/hooks.tsx
  src/lib/hooks/useApproval.ts
  src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/modules/swap/containers/SwapModals/index.tsx
  src/modules/swap/containers/SwapWidget/index.tsx
  src/modules/swap/hooks/useSwapButtonContext.ts
  src/modules/swap/state/swapDerivedStateAtom.ts
  src/modules/swap/state/useSwapDerivedState.ts
  src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  src/modules/trade/containers/TradeWidget/index.tsx
  src/modules/trade/hooks/useBuildTradeDerivedState.ts
  src/modules/trade/hooks/useDerivedTradeState.ts
  src/modules/trade/hooks/useOnImportDismiss.ts
  src/modules/trade/types/TradeDerivedState.ts
Labels: TWAP

#2555 fix: use tradeQuote module for all services in Limit orders
  src/modules/limitOrders/containers/TradeButtons/index.tsx
  src/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/modules/limitOrders/index.ts
  src/modules/limitOrders/state/limitOrdersQuoteAtom.ts
  src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
  src/modules/limitOrders/utils/isUnsupportedTokenInQuote.ts
Labels: TWAP

#2544 refactor: quote for LIMIT and TWAP widgets
  src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
  src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/modules/limitOrders/containers/TradeButtons/index.tsx
  src/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/modules/limitOrders/hooks/useTradeFlowContext.ts
  src/modules/limitOrders/index.ts
  src/modules/limitOrders/state/limitOrdersQuoteAtom.ts
  src/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/index.ts
  src/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.test.ts
  src/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useFetchMarketPrice/useHandleResponse.ts
  src/modules/limitOrders/updaters/MarketPriceUpdater/hooks/useQuoteRequestParams.ts
  src/modules/limitOrders/updaters/MarketPriceUpdater/index.tsx
  src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
  src/modules/limitOrders/utils/isUnsupportedTokenInQuote.ts
  src/modules/swap/containers/SwapWidget/index.tsx
  src/modules/trade/containers/TradeWidget/index.tsx
  src/modules/tradeQuote/hooks/useQuoteParams.ts
  src/modules/tradeQuote/hooks/useTradeQuote.ts
  src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  src/modules/tradeQuote/index.ts
  src/modules/tradeQuote/state/tradeQuoteAtom.ts
  src/modules/tradeQuote/updaters/TradeQuoteUpdater/index.tsx
  src/modules/twap/containers/TwapFormWidget/index.tsx
  src/modules/twap/updaters/QuoteObserverUpdater.tsx
  src/pages/AdvancedOrders/index.tsx
  src/pages/LimitOrders/index.tsx
Labels: TWAP

#2563 refactor: clean up and align UI components related to CurrencyAmountPreview
  src/api/proxy/hooks.ts
  src/common/hooks/useExternalTokenLogo.ts
  src/common/pure/ApproveButton/index.tsx
  src/common/pure/CurrencyAmountPreview/index.tsx
  src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  src/common/pure/CurrencyInputPanel/defaultCurrencyInputProps.ts
  src/common/pure/CurrencyInputPanel/index.cosmos.tsx
  src/common/pure/CurrencyInputPanel/index.ts
  src/common/pure/CurrencyLogo/hooks/useCurrencyLogoURIs.ts
  src/common/pure/CurrencyLogo/index.tsx
  src/common/pure/CurrencySelectButton/index.cosmos.tsx
  src/common/pure/CurrencySelectButton/index.tsx
  src/common/pure/CurrencySelectButton/styled.tsx
  src/common/pure/FiatValue/index.tsx
  src/common/pure/PriceImpactIndicator/index.tsx
  src/legacy/components/CurrencyInputPanel/CurrencyInputPanelMod.tsx
  src/legacy/components/CurrencyInputPanel/FiatValue/FiatValueMod.tsx
  src/legacy/components/CurrencyInputPanel/FiatValue/index.tsx
  src/legacy/components/CurrencyLogo/index.tsx
  src/legacy/components/DoubleLogo/index.tsx
  src/legacy/components/Loader/styled.tsx
  src/legacy/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/legacy/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/legacy/components/SearchModal/CurrencyList/index.tsx
  src/legacy/components/SearchModal/ImportRow/ImportRowMod.tsx
  src/legacy/components/SearchModal/ImportToken/index.tsx
  src/legacy/components/SearchModal/ManageTokens/ManageTokensMod.tsx
  src/legacy/components/SearchModal/TokenImportCard/TokenImportCardMod.tsx
  src/legacy/components/SwapWarnings/index.tsx
  src/legacy/components/Tokens/styled.ts
  src/legacy/components/swap/FormattedPriceImpact.tsx
  src/legacy/components/swap/SwapModalHeader/SwapModalHeaderMod.tsx
  src/legacy/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx
  src/legacy/components/swap/styleds.tsx
  src/legacy/utils/prices.test.ts
  src/legacy/utils/prices.ts
  src/modules/account/containers/Transaction/ActivityDetails.tsx
  src/modules/account/containers/Transaction/styled.ts
  src/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
  src/modules/limitOrders/pure/LimitOrdersConfirm/index.tsx
  src/modules/limitOrders/pure/LimitOrdersConfirm/styled.tsx
  src/modules/limitOrders/pure/Orders/OrderRow/index.tsx
  src/modules/limitOrders/pure/ReceiptModal/CurrencyField.tsx
  src/modules/swap/pure/EthFlow/WrappingPreview/WrapCard.tsx
  src/modules/trade/containers/TradeWidget/index.tsx
  src/modules/wallet/web3-react/containers/AddToMetamask/index.tsx
  src/pages/Claim/InvestmentFlow/InvestOption.tsx
Labels: TWAP

#2570 feat: add rate info
  src/modules/twap/containers/TwapFormWidget/index.tsx
  src/modules/twap/containers/TwapFormWidget/styled.tsx
Labels: TWAP

#2571 refactor: decompose TransactionConfirmationModal
  src/common/containers/MultipleOrdersCancellationModal/index.tsx
  src/common/containers/TradeApprove/TradeApproveModal.tsx
  src/common/pure/AnimatedConfirmation/index.tsx
  src/common/pure/CancellationModal/RequestCancellationModal.tsx
  src/common/pure/CancellationModal/index.tsx
  src/common/pure/OrderSubmittedContent/index.tsx
  src/common/pure/TransactionSubmittedContent/index.tsx
  src/legacy/components/CowSubsidyModal/index.tsx
  src/legacy/components/Tokens/TokensTable.tsx
  src/legacy/components/Tokens/TokensTableRow.tsx
  src/legacy/components/TransactionConfirmationModal/DisplayLink.tsx
  src/legacy/components/TransactionConfirmationModal/LegacyConfirmationModalContent.tsx
  src/legacy/components/TransactionConfirmationModal/LegacyConfirmationPendingContent.tsx
  src/legacy/components/TransactionConfirmationModal/TransactionConfirmationModalMod.tsx
  src/legacy/components/TransactionConfirmationModal/index.cosmos.tsx
  src/legacy/components/TransactionConfirmationModal/index.tsx
  src/legacy/components/TransactionConfirmationModal/styled.ts
  src/legacy/components/TransactionConfirmationModal/types.ts
  src/legacy/components/TransactionExecutedContent/index.tsx
  src/legacy/components/swap/ConfirmSwapModal/index.tsx
  src/legacy/hooks/useApproveCallback/useApproveCallbackMod.ts
  src/legacy/hooks/useTransactionConfirmationModal.tsx
  src/legacy/hooks/useWrapCallback.ts
  src/legacy/state/cowToken/hooks.ts
  src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  src/modules/swap/pure/EthFlow/EthFlowModalContent/index.tsx
  src/modules/swap/state/transactionConfirmAtom.ts
  src/pages/Account/Balances.tsx
  src/pages/Account/LockedGnoVesting/hooks.ts
  src/pages/Account/LockedGnoVesting/index.tsx
  src/pages/Claim/InvestmentFlow/InvestOption.tsx
  src/pages/Claim/InvestmentFlow/index.tsx
  src/pages/Claim/index.tsx
Labels: TWAP

#2573 feat(limit-orders): integrate TradeConfirmModal in Limit orders
  src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.cosmos.tsx
  src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  src/modules/limitOrders/containers/LimitOrdersConfirmModal/state.ts
  src/modules/limitOrders/containers/LimitOrdersConfirmModal/styled.tsx
  src/modules/limitOrders/containers/LimitOrdersWidget/hooks/useLimitOrdersWidgetActions.ts
  src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/modules/limitOrders/containers/LimitOrdersWidget/limitOrdersPropsChecker.ts
  src/modules/limitOrders/containers/TradeButtons/index.tsx
  src/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
  src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  src/modules/limitOrders/services/safeBundleFlow/index.ts
  src/modules/limitOrders/services/tradeFlow/index.ts
  src/modules/swap/containers/SwapWidget/index.tsx
  src/modules/trade/containers/TradeConfirmModal/TradeConfirmPendingContent.tsx
  src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
  src/modules/trade/containers/TradeConfirmModal/index.tsx
  src/modules/trade/hooks/useTradeConfirmActions.ts
  src/modules/trade/index.ts
  src/modules/trade/pure/TradeConfirmation/index.cosmos.tsx
  src/modules/trade/pure/TradeConfirmation/index.tsx
  src/modules/trade/pure/TradeConfirmation/styled.tsx
  src/modules/trade/state/tradeConfirmStateAtom.ts
  src/modules/trade/types/TradeAmounts.ts
  src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
Labels: TWAP

#2574 feat(twap): integrate TradeConfirmModal in Twap orders
  src/common/pure/OrderSubmittedContent/index.tsx
  src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
  src/modules/trade/hooks/useTradeConfirmActions.ts
  src/modules/trade/state/tradeConfirmStateAtom.ts
  src/modules/twap/containers/TwapConfirmModal/index.tsx
  src/modules/twap/containers/TwapFormWidget/index.tsx
  src/modules/twap/hooks/useCreateTwapOrder.ts
  src/modules/twap/hooks/useSetupFallbackHandler.ts
  src/modules/twap/hooks/useTwapFormActions.ts
  src/modules/twap/pure/PrimaryActionButton/index.tsx
Labels: TWAP

#2567 feat: swap SELL and BUY fields
  src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts
  src/modules/limitOrders/containers/LimitOrdersWidget/hooks/useLimitOrdersWidgetActions.ts
  src/modules/trade/hooks/useSwitchTokensPlaces.ts
Labels: TWAP

#2583 [#3] refactor(orders-table): rename OrdersWidget to OrdersTableWidget
  src/constants/featureFlags.ts
  src/modules/limitOrders/containers/RateInput/index.tsx
  src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  src/modules/ordersTable/const/limitOrdersTabs.ts
  src/modules/ordersTable/const/tabs.ts
  src/modules/ordersTable/containers/MultipleCancellationMenu/index.tsx
  src/modules/ordersTable/containers/OrdersReceiptModal/hooks.ts
  src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
  src/modules/ordersTable/containers/OrdersTableWidget/hooks/useValidatePageUrlParams.ts
  src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  src/modules/ordersTable/index.tsx
  src/modules/ordersTable/pure/OrderStatusBox/index.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/OrderContextMenu.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrdersTablePagination.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/OrdersTabs.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/orders.mock.ts
  src/modules/ordersTable/pure/OrdersTableContainer/styled.tsx
  src/modules/ordersTable/pure/OrdersTableContainer/types.ts
  src/modules/ordersTable/pure/OrdersTableContainer/utils/getOrderParams.test.ts
  src/modules/ordersTable/pure/OrdersTableContainer/utils/getOrderParams.ts
  src/modules/ordersTable/state/orderReceiptAtom.ts
  src/modules/ordersTable/utils/buildLimitOrdersUrl.ts
  src/modules/ordersTable/utils/buildOrdersTableUrl.ts
  src/pages/AdvancedOrders/index.tsx
  src/pages/LimitOrders/index.tsx
Labels: TWAP
