Repository cowprotocol/cowswap, pull requests merged in 2023-01, with the labels that each got.

#1796 [EthFlow]#1294 - updated backend return types
  src/cow-react/api/gnosisProtocol/api.ts
  src/cow-react/modules/swap/containers/EthFlowStepper/index.tsx
  src/cow-react/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step3.tsx
  src/cow-react/pages/Faq/EthFlowFaq.tsx
  src/custom/components/Header/styled.ts
  src/custom/state/orders/actions.ts
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updaters/ExpiredOrdersUpdater.ts
  src/custom/state/orders/updaters/GpOrdersUpdater.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
Labels: eth-flow

#1816 Hotfix 1.28.1
  package.json
  public/audio/send-winterTheme.mp3
  src/cow-react/modules/application/containers/App/index.tsx
  src/cow-react/modules/application/containers/App/styled.ts
  src/cow-react/modules/winterEdition/index.tsx
  src/custom/components/Footer/index.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Header/styled.ts
  src/custom/components/SideMenu/index.tsx
  src/custom/components/Version/index.tsx
  src/custom/theme/cowSwapAssets.ts
  src/custom/utils/sound.ts
  yarn.lock
Labels: RELEASE

#1708 Parse sell/buy amount from URL and apply to Limit orders widget
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  src/cow-react/modules/limitOrders/containers/RateInput/index.tsx
  src/cow-react/modules/limitOrders/hooks/useApplyLimitRate.ts
  src/cow-react/modules/limitOrders/hooks/useSetupLimitOrderAmountsFromUrl.ts
  src/cow-react/modules/limitOrders/hooks/useUpdateActiveRate.ts
  src/cow-react/modules/limitOrders/hooks/useUpdateCurrencyAmount.ts
  src/cow-react/modules/limitOrders/index.ts
  src/cow-react/modules/limitOrders/state/limitRateAtom.ts
  src/cow-react/modules/limitOrders/updaters/ActiveRateUpdater/index.ts
  src/cow-react/modules/limitOrders/updaters/MarketPriceUpdater/index.tsx
  src/cow-react/modules/limitOrders/utils/calculateAmountForRate.ts
  src/cow-react/modules/swap/hooks/useSetupSwapAmountsFromUrl.ts
  src/cow-react/modules/trade/const/tradeUrl.ts
  src/cow-react/pages/LimitOrders/index.tsx
  src/cow-react/utils/getIntOrFloat.ts
Labels: limit-order

#1813 Reduce bundle size by excluding unused files (-0.28MB gzip)
  package.json
  patches/@ethereumjs+common+2.5.0.patch
  patches/@uniswap+swap-router-contracts+1.3.0.patch
  patches/@uniswap+v3-periphery+1.4.3.patch
  patches/@uniswap+v3-staker+1.0.0.patch
  patches/web3+1.8.1.patch
  yarn.lock
Labels: Performance

#1819 [EthFlow]#1586 progress bar starts not from 0
  src/custom/components/OrderProgressBar/index.tsx
  src/custom/state/orders/reducer.ts
  src/custom/state/orders/updaters/PendingOrdersUpdater.ts
Labels: eth-flow

#1714 Add warning when unsupported token is selected
  src/cow-react/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/index.tsx
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts
  src/cow-react/modules/swap/pure/warnings.tsx
  src/cow-react/modules/trade/pure/CompatibilityIssuesWarning/index.tsx
Labels: limit-order

#1812 [Tokens refactoring #1] Remove tons of tokens lists recalculations by moving them to Updater
  src/cow-react/common/hooks/useAllTokensList.ts
  src/cow-react/common/hooks/useAreThereTokensWithSameSymbol.ts
  src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts
  src/cow-react/modules/application/containers/App/Updaters.tsx
  src/cow-react/modules/tokensList/TokensListUpdater.ts
  src/cow-react/modules/tokensList/tokensListAtom.ts
  src/custom/hooks/Tokens/TokensMod.ts
Labels: Performance

#1822 [Tokens refactoring #2] Removed usage of WrappedTokenInfo and removed redundant cycles with tokens lists
  src/cow-react/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  src/cow-react/modules/swap/containers/NewSwapWidget/index.tsx
  src/cow-react/modules/swap/helpers/getSwapButtonState.ts
  src/cow-react/modules/swap/hooks/useSwapButtonContext.ts
  src/cow-react/modules/tokensList/TokensListUpdater.ts
  src/cow-react/modules/tokensList/tokensListAtom.ts
  src/custom/components/SearchModal/CommonBases/CommonBasesMod.tsx
  src/custom/components/SearchModal/CurrencyList/CurrencyListMod.tsx
  src/custom/components/SearchModal/CurrencySearch/CurrencySearchMod.tsx
  src/custom/components/swap/UnsupportedCurrencyFooter/UnsupportedCurrencyFooterMod.tsx
  src/custom/hooks/Tokens/TokensMod.ts
  src/custom/hooks/useIsSwapUnsupported/index.ts
  src/custom/hooks/useIsSwapUnsupported/useIsSwapUnsupportedMod.ts
  src/custom/lib/hooks/useCurrencyLogoURIs/useCurrencyLogoURIsMod.ts
  src/custom/state/lists/hooks/hooksMod.ts
  src/custom/state/lists/hooks/index.ts
Labels: Performance

#1877 Fix for wrap mode
  src/cow-react/modules/application/pure/Page/index.tsx
Labels: RELEASE

#1880 Address comments in issue
  src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md
Labels: RELEASE

#1882 Fix issues
  src/cow-react/modules/application/pure/Page/index.tsx
  src/cow-react/pages/CookiePolicy/CookiePolicy.md
  src/cow-react/pages/CookiePolicy/index.tsx
Labels: RELEASE

#1887 Remove gas cost label from ETH orders
  src/cow-react/modules/swap/pure/ReceiveAmountInfo/index.tsx
  src/custom/components/swap/FeeInformationTooltip.tsx
Labels: RELEASE

#1890 Add back to top button to content pages
  src/cow-react/modules/application/pure/Page/index.tsx
  src/cow-react/pages/CookiePolicy/CookiePolicy.md
  src/cow-react/pages/PrivacyPolicy/PrivacyPolicy.md
  src/cow-react/pages/TermsAndConditions/TermsAndConditions.md
  src/cow-react/pages/TermsAndConditions/index.tsx
Labels: RELEASE

#1938 Hotfix 1.29.3
  package.json
  src/cow-react/modules/limitOrders/containers/TradeButtons/limitOrdersTradeButtonsMap.tsx
  src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx
  src/custom/components/Header/index.tsx
  src/custom/components/Header/styled.ts
  src/custom/theme/cowSwapAssets.ts
Labels: RELEASE
