Repository cowprotocol/cowswap, pull requests merged in 2023-11, with the labels that each got.

#3306 feat: revert halloween theme
  apps/cowswap-frontend/index.html
  apps/cowswap-frontend/src/common/constants/theme.ts
  apps/cowswap-frontend/src/legacy/state/cowToken/middleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.ts
  apps/cowswap-frontend/src/legacy/state/user/hooks.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/Layer3Banner/index.tsx
Labels: RELEASE

#3313 docs: vanilla js widget demo
  libs/widget-lib/demo/vanilla.html
Labels: Widget

#3314 chore(main): release 1.48.13
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3318 refactor(widget): make only one flat set of params
  apps/cowswap-frontend/src/common/hooks/useAnalyticsReporter.ts
  apps/cowswap-frontend/src/modules/appData/hooks.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetMetaData.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetMetaDataAtom.ts
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/IframeResizer.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
  apps/widget-configurator/src/app/configurator/embedDialog.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  libs/widget-lib/README.md
  libs/widget-lib/demo/vanilla.html
  libs/widget-lib/docs/README.md
  libs/widget-lib/src/JsonRpcManager.ts
  libs/widget-lib/src/consts.ts
  libs/widget-lib/src/cowSwapWidget.ts
  libs/widget-lib/src/types.ts
  libs/widget-lib/src/urlUtils.ts
  libs/widget-react/README.md
  libs/widget-react/src/lib/CowSwapWidget.tsx
Labels: Widget

#3317 docs(widget): typedoc for widget lib
  libs/widget-lib/src/JsonRpcManager.ts
Labels: Widget

#3322 feat(widget-configurator): different examples for embed code
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/embedDialog/index.tsx
  apps/widget-configurator/src/app/embedDialog/utils/reactExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanilaNpmExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanillaNoDepsExample.ts
  libs/widget-lib/demo/vanilla.html
Labels: Widget

#3325 chore(main): release 1.48.14
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3331 chore(main): release 1.48.17
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3316 feat(permit): load pre generated permit info
  .gitignore
  apps/cowswap-frontend/src/modules/permit/const.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitCompatibleTokens.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePreGeneratedPermitInfo.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePreGeneratedPermitInfoForToken.ts
  apps/cowswap-frontend/src/modules/permit/index.ts
  apps/cowswap-frontend/src/modules/permit/types.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  libs/common-const/src/common.ts
Labels: permit

#3320 feat(permit): remove permit related feature flags
  apps/cowswap-frontend/src/common/hooks/featureFlags/useIsPermitEnabled.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
Labels: permit

#3324 feat(widget-configurator): button to show drawer
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/styled.ts
  libs/widget-lib/docs/README.md
Labels: Widget

#3332 feat(permit): update gas-free flag tooltip
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  libs/ui/src/pure/Tooltip/index.tsx
Labels: permit

#3339 fix(widget-lib): adjust code for server-side rendering
  libs/widget-lib/package.json
  libs/widget-lib/src/consts.ts
  libs/widget-react/package.json
Labels: Widget

#3340 fix: update chainId in trade state
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Labels: Bug

#3335 feat(widget-configurator): google analytics events
  apps/widget-configurator/.env
  apps/widget-configurator/.env.production
  apps/widget-configurator/src/app/analytics.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/embedDialog/index.tsx
  apps/widget-configurator/vite.config.ts
  libs/analytics/src/types.ts
Labels: Widget

#3337 chore: add a link to widget typeform
  apps/widget-configurator/src/app/embedDialog/utils/reactExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/sanitizeParameters.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanilaNpmExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanillaNoDepsExample.ts
  libs/widget-lib/docs/README.md
  libs/widget-lib/src/types.ts
Labels: Widget

#3345 feat: add comment to config
  apps/widget-configurator/src/app/embedDialog/const.ts
  apps/widget-configurator/src/app/embedDialog/utils/formatParameters.ts
  apps/widget-configurator/src/app/embedDialog/utils/reactExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/sanitizeParameters.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanilaNpmExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/vanillaNoDepsExample.ts
  libs/widget-lib/docs/README.md
Labels: Widget

#3356 Fix styles general
  apps/cowswap-frontend/src/common/pure/Icon/index.tsx
  apps/cowswap-frontend/src/common/pure/InlineBanner/banners.tsx
  apps/cowswap-frontend/src/common/pure/InlineBanner/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/TradeWidgetLinks/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/UnsupportedWalletWarning.tsx
  libs/tokens/src/pure/TokenLogo/index.tsx
Labels: RELEASE

#3348 fix(twap): fix infinite loop in orders hook
  apps/cowswap-frontend/src/modules/orders/hooks/useSWRProdOrders.ts
Labels: Bug

#3359 feat(widget): links to landing and docs
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/styled.ts
Labels: Widget

#3369 fix(widget-configurator): switch network only when user changed in the configurator
  apps/widget-configurator/src/app/configurator/hooks/useSyncWidgetNetwork.ts
Labels: Widget

#3373 chore(main): release 1.49.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3376 fix(widget): add a threshold for the widget height
  libs/widget-lib/src/cowSwapWidget.ts
Labels: Widget

#3379 chore(main): release 1.49.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3381 feat(widget): add widget link to main menu
  apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
  apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/index.tsx
  apps/cowswap-frontend/src/modules/mainMenu/pure/MenuTree/styled.ts
  apps/cowswap-frontend/src/modules/mainMenu/types.ts
  libs/assets/src/cow-swap/widget-icon.svg
  libs/common-const/src/common.ts
Labels: RELEASE, Widget

#3380 fix(widget): polish configurator
  apps/widget-configurator/index.html
  apps/widget-configurator/public/favicon.ico
  apps/widget-configurator/public/favicon.png
  apps/widget-configurator/src/app/configurator/controls/ThemeControl.tsx
  apps/widget-configurator/src/app/configurator/controls/TradeModesControl.tsx
  apps/widget-configurator/src/app/embedDialog/utils/reactExample.ts
  libs/widget-lib/src/urlUtils.ts
Labels: RELEASE, Widget

#3387 fix(balances): always use network provider for multicalls
  apps/cowswap-frontend/src/legacy/state/multicall.tsx
  libs/common-hooks/src/useContract.ts
  libs/widget-lib/src/urlUtils.spec.ts
Labels: RELEASE

#3388 chore(main): release 1.49.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3395 fix(token-selector): show direct match on top
  apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx
  libs/tokens/src/const/defaultFavouriteTokens.ts
  libs/tokens/src/utils/getTokenSearchFilter.ts
Labels: RELEASE

#3392 chore(main): release 1.49.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3396 chore(release): hotfix/1.49.5
  apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx
  libs/tokens/src/const/defaultFavouriteTokens.ts
  libs/tokens/src/utils/getTokenSearchFilter.ts
Labels: RELEASE

#3397 chore(main): release 1.49.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3404 fix(permit): disable permit for sc wallets
  apps/cowswap-frontend/src/modules/permit/hooks/useIsTokenPermittable.ts
  apps/cowswap-frontend/src/modules/permit/state/permitCacheAtom.ts
  libs/permit-utils/src/const.ts
  libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
Labels: RELEASE, permit

#3403 chore(main): release 1.49.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3374 feat(permit): fetch token name from chain
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useGeneratePermitHook.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitCompatibleTokens.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePreGeneratedPermitInfo.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useTokenSupportsPermit.ts
  apps/cowswap-frontend/src/modules/permit/index.ts
  apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
  apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  libs/permit-utils/package.json
  libs/permit-utils/src/abi/erc20.json
  libs/permit-utils/src/index.ts
  libs/permit-utils/src/lib/checkIsCallDataAValidPermit.ts
  libs/permit-utils/src/lib/generatePermitHook.ts
  libs/permit-utils/src/lib/getTokenPermitInfo.ts
  libs/permit-utils/src/types.ts
  libs/permit-utils/src/utils/PermitProviderConnector.ts
  libs/permit-utils/src/utils/fixTokenName.ts
  libs/permit-utils/src/utils/getContract.ts
  libs/permit-utils/src/utils/getTokenName.ts
  libs/permit-utils/src/utils/isSupportedPermitInfo.ts
Labels: permit

#3438 chore(main): release 1.50.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3456 chore(main): release 1.50.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending
