Repository cowprotocol/cowswap, pull requests merged in 2024-07, with the labels that each got.

#4642 fix(explorer): invert fills table order (newest first)
  apps/explorer/src/hooks/useOperatorTrades.ts
Labels: RELEASE

#4651 fix(widget): use custom label and content for partner fee (#4646)
  apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
Labels: RELEASE

#4653 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4652 chore: update hooks-store PR
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/common/pure/CloseIcon/index.tsx
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/application/containers/App/RoutesApp.tsx
  apps/cowswap-frontend/src/modules/hooks/const.ts
  apps/cowswap-frontend/src/modules/hooks/context.ts
  apps/cowswap-frontend/src/modules/hooks/dapps/BuildHookApp/gnosis-logo.svg
  apps/cowswap-frontend/src/modules/hooks/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooks/dapps/ClaimGnoHookApp/gnosis-logo.svg
  apps/cowswap-frontend/src/modules/hooks/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooks/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooks/hooks.ts
  apps/cowswap-frontend/src/modules/hooks/images/bridge.svg
  apps/cowswap-frontend/src/modules/hooks/images/build.png
  apps/cowswap-frontend/src/modules/hooks/images/cowAMM.png
  apps/cowswap-frontend/src/modules/hooks/images/cowAMM.svg
  apps/cowswap-frontend/src/modules/hooks/images/curve.svg
  apps/cowswap-frontend/src/modules/hooks/images/dai.svg
  apps/cowswap-frontend/src/modules/hooks/index.ts
  apps/cowswap-frontend/src/modules/hooks/smart/HookStoreModal.tsx
  apps/cowswap-frontend/src/modules/hooks/smart/hookButtons.tsx
  apps/cowswap-frontend/src/modules/hooks/state/hookDetailsAtom.ts
  apps/cowswap-frontend/src/modules/hooks/utils.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/OrderTypeField.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
  apps/cowswap-frontend/src/pages/Hooks/index.tsx
  apps/cowswap-frontend/src/pages/Swap/index.tsx
  apps/cowswap-frontend/src/utils/orderUtils/getUiOrderType.ts
  libs/abis/src/abis/SBCDepositContract.json
  libs/abis/src/generated/custom/CoWSwapEthFlow.ts
  libs/abis/src/generated/custom/Multicall3.ts
  libs/abis/src/generated/custom/SBCDepositContract.ts
  libs/abis/src/generated/custom/factories/CoWSwapEthFlow__factory.ts
  libs/abis/src/generated/custom/factories/Multicall3__factory.ts
  libs/abis/src/generated/custom/factories/SBCDepositContract__factory.ts
  libs/abis/src/generated/custom/factories/index.ts
  libs/abis/src/generated/custom/index.ts
  libs/abis/src/index.ts
  libs/analytics/src/events/transactionEvents.ts
  libs/events/src/CowEventEmitter.ts
  libs/events/src/types/events.ts
  libs/types/src/common.ts
  libs/types/src/hooks.ts
  libs/types/src/index.ts
Labels: Hooks store

#4654 feat(hooks-store): hooks merging with permit and feature-flag
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/common/hooks/useMenuItems.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/hooks/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooks/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
Labels: Hooks store

#4673 fix(widget): always listen activation event (#4670)
  libs/widget-lib/src/cowSwapWidget.ts
Labels: RELEASE

#4674 chore: release main
  .release-please-manifest.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4675 chore: up widget lib version
  libs/widget-react/package.json
Labels: RELEASE

#4681 fix(widget-lib): exclude cow-sdk from the bundle
  libs/widget-lib/src/flexibleConfig.ts
  libs/widget-lib/src/types.ts
Labels: RELEASE

#4682 chore: up widget lib version
  libs/widget-react/package.json
Labels: RELEASE

#4679 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4686 fix: vercel redirects
  apps/cowswap-frontend/vercel.json
Labels: RELEASE

#4698 fix(hooks): link hooks page to swap trade state
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeTypeInfoFromUrl.tsx
Labels: Hooks store

#4699 refactor: split hooks module into files
  apps/cowswap-frontend/src/modules/hooks/const.ts
  apps/cowswap-frontend/src/modules/hooks/containers/HookStoreModal.tsx
  apps/cowswap-frontend/src/modules/hooks/containers/PostHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooks/containers/PreHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooks/containers/PreHookButton/styled.tsx
  apps/cowswap-frontend/src/modules/hooks/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooks/hooks.ts
  apps/cowswap-frontend/src/modules/hooks/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooks/hooks/useHooks.ts
  apps/cowswap-frontend/src/modules/hooks/hooks/useRemoveHook.ts
  apps/cowswap-frontend/src/modules/hooks/hooks/useSBCDepositContract.ts
  apps/cowswap-frontend/src/modules/hooks/index.ts
  apps/cowswap-frontend/src/modules/hooks/pure/HookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooks/pure/HookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooks/pure/HookTooltip/index.tsx
  apps/cowswap-frontend/src/modules/hooks/smart/hookButtons.tsx
Labels: Hooks store

#4700 refactor: rename hooks -> hooksStore
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/hooksStore/const.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookStoreModal.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PostHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/context.ts
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/gnosis-logo.svg
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/gnosis-logo.svg
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useHooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSBCDepositContract.ts
  apps/cowswap-frontend/src/modules/hooksStore/images/bridge.svg
  apps/cowswap-frontend/src/modules/hooksStore/images/build.png
  apps/cowswap-frontend/src/modules/hooksStore/images/cowAMM.png
  apps/cowswap-frontend/src/modules/hooksStore/images/cowAMM.svg
  apps/cowswap-frontend/src/modules/hooksStore/images/curve.svg
  apps/cowswap-frontend/src/modules/hooksStore/images/dai.svg
  apps/cowswap-frontend/src/modules/hooksStore/index.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookTooltip/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/hookDetailsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/utils.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
Labels: Hooks store

#4712 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/abis/CHANGELOG.md
  libs/abis/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4714 fix(explorer): fix linter issues
  apps/explorer/src/components/orders/DetailsTable/index.tsx
  apps/explorer/src/explorer/components/OrdersTableWidget/useSearchInAnotherNetwork.tsx
  apps/explorer/src/explorer/components/common/BlockExplorerLink/index.tsx
  apps/explorer/src/hooks/useOperatorOrder.ts
  apps/explorer/src/hooks/usePopper.ts
Labels: RELEASE

#4715 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4719 fix(permit): filter out permit signer and rotate it
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/appData/types.ts
  apps/cowswap-frontend/src/modules/appData/utils/appDataFilter.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
  apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
  libs/permit-utils/src/const.ts
Labels: RELEASE

#4726 fix(permit): typefy hooks and allow only 1 permit
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/appData/state/atoms.ts
  apps/cowswap-frontend/src/modules/appData/types.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
  apps/cowswap-frontend/src/modules/appData/utils/appDataFilter.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppDataHooks.ts
  apps/cowswap-frontend/src/modules/appData/utils/typedHooks.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
  apps/cowswap-frontend/src/modules/permit/types.ts
  apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
Labels: RELEASE

#4720 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
Labels: autorelease: pending

#4731 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4752 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
Labels: autorelease: pending
