Repository cowprotocol/cowswap, pull requests merged in 2024-03, with the labels that each got.

#3942 refactor: remove fee=zero feature flag
  apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/calculateUniqueOrderId.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
Labels: partner fee

#3967 chore: remove geo-blocking banner
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  libs/tokens/src/containers/OnlyUniswapListAvailableBanner/index.tsx
  libs/tokens/src/index.ts
Labels: RELEASE

#3971 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3964 Fee display styling
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
Labels: partner fee

#3958 feat(widget): validate partner fee
  apps/cowswap-frontend/src/modules/injectedWidget/consts.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/pure/WidgetParamsErrorsScreen/index.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validateWidgetParams.ts
  apps/widget-configurator/src/app/configurator/controls/PartnerFeeControl.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  apps/widget-configurator/src/app/embedDialog/const.ts
Labels: partner fee

#3941 feat: display and sign order with partner fee
  apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/defaultCurrencyInputProps.ts
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/AdvancedSwapDetails.tsx
  apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
  apps/cowswap-frontend/src/legacy/state/swap/extension.ts
  apps/cowswap-frontend/src/legacy/state/swap/trade.test.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/mocks/tradeStateMock.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/injectedWidget/consts.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/pure/WidgetParamsErrorsScreen/index.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validateWidgetParams.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useEthFlowActions.ts
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeSummary/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.ts
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/helpers/tradeReceiveAmount.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/tradeReceiveAmount.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapCurrenciesAmounts.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmountInfo/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/types.ts
  apps/cowswap-frontend/src/modules/swap/pure/Row/typings.ts
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/useFeeAmounts.ts
  apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeSummary/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/calculateUniqueOrderId.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
  apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
  apps/widget-configurator/src/app/configurator/controls/PartnerFeeControl.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  apps/widget-configurator/src/app/embedDialog/const.ts
Labels: partner fee

#4007 Fee accordion fix
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
Labels: RELEASE

#4010 chore: fix new modal heading styles
  apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
Labels: RELEASE

#4009 chore: fix fee warning calculations
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  libs/common-const/src/common.ts
Labels: RELEASE

#3998 feat: add standalone/dapp mode to params
  apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  libs/widget-lib/src/types.ts
Labels: RELEASE

#4005 Rebrand labels and improve tooltips
  apps/cowswap-frontend/src/common/pure/OrderExecutionStatusList/RateTooltipHeader.tsx
  apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowBanner/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmountInfo/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/styled.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/SwapPriceDifferenceWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/tooltips.tsx
  apps/cowswap-frontend/src/pages/Faq/TradingFaq.tsx
  libs/ui/src/pure/InlineBanner/banners.tsx
Labels: RELEASE

#3991 feat: add option to define the base URL for the widget
  apps/cowswap-frontend/src/legacy/components/Header/AccountElement/index.tsx
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/embedDialog/const.ts
  libs/widget-lib/docs/README.md
  libs/widget-lib/src/consts.ts
  libs/widget-lib/src/index.ts
  libs/widget-lib/src/types.ts
  libs/widget-lib/src/urlUtils.spec.ts
  libs/widget-lib/src/urlUtils.ts
Labels: RELEASE

#3966 Release widget rc
  .github/workflows/npm.yml
  libs/events/package.json
  libs/events/project.json
  libs/types/package.json
  libs/types/project.json
  libs/widget-lib/package.json
  libs/widget-react/package.json
Labels: RELEASE

#4019 fix(order-receipt): fix recreate order button style
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/styled.ts
  libs/ui/src/pure/InlineBanner/banners.tsx
Labels: RELEASE

#4031 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/widget-lib/CHANGELOG.md
Labels: autorelease: pending

#4041 fix: migrate to nodereal api from infura
  apps/explorer/src/api/web3/index.ts
  apps/explorer/src/const.ts
Labels: RELEASE

#3902 [NOTIFICATIONS #1] feat: show order submitted notification from event
  apps/cowswap-frontend/src/legacy/state/orders/hooks.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/pendingOrderPopup.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/pendingOrderPopup.tsx
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/showPendingOrderNotification.tsx
  apps/cowswap-frontend/src/legacy/state/orders/middleware/updateOrderPopup.ts
  apps/cowswap-frontend/src/legacy/state/orders/mocks.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/getPendingOrderNotificationProps.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/getPendingOrderNotificationToast.test.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/index.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitPostedOrderEvent.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useCreateTwapOrder.tsx
  apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdAmount.ts
  apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/index.tsx
  libs/common-utils/src/currencyAmountToTokenAmount.ts
  libs/events/src/types/events.ts
  libs/events/src/types/orders.ts
  libs/events/src/types/toastMessages.ts
Labels: notifications

#3921 [NOTIFICATIONS #2] feat(orders): bind fulfilled notification to EVENT_EMITTER
  apps/cowswap-frontend/src/common/updaters/orders/CancelledOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/utils.ts
  apps/cowswap-frontend/src/legacy/state/orders/actions.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchFulfillOrderPopup.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchFulfillOrderPopup.tsx
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/reducer.ts
  apps/cowswap-frontend/src/modules/orders/containers/ExecutedSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/ExecutedSummary/styled.ts
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/index.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitFulfilledOrderEvent.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitPostedOrderEvent.tsx
  apps/widget-configurator/src/app/configurator/consts.ts
  libs/events/src/types/events.ts
  libs/events/src/types/orders.ts
Labels: notifications

#3922 [NOTIFICATIONS #3] refactor(orders): unify orders notifications handlers
  apps/cowswap-frontend/src/common/hooks/useGetSurplusFiatValue.ts
  apps/cowswap-frontend/src/common/updaters/orders/CancelledOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/utils.ts
  apps/cowswap-frontend/src/modules/orders/containers/ExecutedSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/getPendingOrderNotificationProps.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/getPendingOrderNotificationToast.test.ts
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/commonStyled.ts
  apps/cowswap-frontend/src/modules/orders/types.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/index.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/types.ts
  apps/cowswap-frontend/src/modules/orders/utils/emitFulfilledOrderEvent.tsx
  apps/cowswap-frontend/src/modules/swap/state/surplusModal.ts
  apps/widget-configurator/src/app/configurator/consts.ts
  libs/events/src/types/orders.ts
  libs/events/src/types/toastMessages.ts
Labels: notifications

#3927 [NOTIFICATIONS #4] refactor(orders): bind order cancellation notification to events emitter
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/state/orders/buildCancellationPopupSummary.tsx
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchCancelOrdersPopup.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchCancelOrdersPopup.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.ts
  apps/cowswap-frontend/src/modules/orders/containers/CancelledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitCancelledOrderEvent.tsx
  apps/widget-configurator/src/app/configurator/consts.ts
  libs/events/src/types/events.ts
  libs/events/src/types/orders.ts
  libs/events/src/types/toastMessages.ts
Labels: notifications

#3931 [NOTIFICATIONS #5] refactor(orders): extract OrderSummary and ReceiverInfo components
  apps/cowswap-frontend/src/modules/orders/containers/CancelledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/OrderSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/ReceiverInfo/index.tsx
  libs/common-const/src/types.ts
  libs/common-utils/src/doesTokenMatchSymbolOrAddress.ts
  libs/events/src/types/orders.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
  libs/tokens/src/utils/fetchTokenFromBlockchain.ts
  libs/tokens/src/utils/getTokenSearchFilter.ts
  libs/tokens/src/utils/validateTokenList.test.ts
  libs/tokens/src/utils/validateTokenList.ts
  libs/types/src/index.ts
Labels: notifications

#3933 [NOTIFICATIONS #7] refactor(orders): bind presigned order notification to events emitter
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/state/index.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchPresignOrdersPopup.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/batchPresignOrdersPopup.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/index.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/popupMiddleware.ts
  apps/cowswap-frontend/src/modules/orders/containers/PresignedOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitPresignedOrderEvent.tsx
  libs/events/src/types/events.ts
  libs/events/src/types/orders.ts
  libs/events/src/types/toastMessages.ts
Labels: notifications

#3934 [NOTIFICATIONS #8] refactor: unify order events and notifications
  apps/cowswap-frontend/src/api/gnosisProtocol/getIsOrderBookTypedError.ts
  apps/cowswap-frontend/src/common/hooks/useGetSurplusFiatValue.ts
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/orders/containers/CancelledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/ExecutedSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/ExpiredOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderInfo/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderInfo/styled.ts
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/utils.ts
  apps/cowswap-frontend/src/modules/orders/containers/PresignedOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/OrderSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/OrderSummary/summaryTemplates.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/index.tsx
  apps/cowswap-frontend/src/modules/orders/utils/emitPostedOrderEvent.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/permit/const.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/state/tradeConfirmStateAtom.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useCancelTwapOrder.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useGetTwapOrderById.ts
  libs/events/src/types/orders.ts
  libs/snackbars/src/containers/SnackbarsWidget/index.tsx
Labels: notifications

#4038 [NOTIFICATIONS #9] refactor: use new snackbars for wrap/unwrap/approve notifications
  apps/cowswap-frontend/src/common/hooks/useOnSelectNetwork.tsx
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/TransactionContentWithLink/index.tsx
  apps/cowswap-frontend/src/modules/orders/index.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
Labels: notifications

#4039 [NOTIFICATIONS #10] refactor: remove legacy popups
  apps/cowswap-frontend/src/common/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/cow-react/index.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/FailedNetworkSwitchPopup.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/PopupItem.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/TransactionPopup.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/WarningPopup.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/index.tsx
  apps/cowswap-frontend/src/legacy/components/Popups/styled.ts
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/legacy/state/application/initialState.ts
  apps/cowswap-frontend/src/legacy/state/application/reducer.test.ts
  apps/cowswap-frontend/src/legacy/state/application/reducer.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.ts
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/wallet/containers/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx
Labels: notifications

#4045 [NOTIFICATIONS #11] feat(events): fire on-chain transactions events
  apps/cowswap-frontend/src/cow-react/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/index.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/OnchainTransactionEventsUpdater.tsx
  apps/cowswap-frontend/src/modules/onchainTransactions/utils/emitOnchainTransactionEvent.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/widget-configurator/src/app/configurator/index.tsx
  libs/events/src/types/events.ts
  libs/events/src/types/index.ts
  libs/events/src/types/toastMessages.ts
  libs/events/src/types/transactions.ts
  libs/snackbars/src/containers/SnackbarsWidget/index.tsx
Labels: notifications

#4067 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4069 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4073 Release/2024.03.21
  apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
Labels: RELEASE

#4074 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4075 fix: show link to Explorer for twap orders
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/TransactionContentWithLink/index.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
Labels: RELEASE

#4077 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4084 chore: release main
  .release-please-manifest.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4091 chore: release main
  .release-please-manifest.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4015 feat(limit): edit limit order (disabled)
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/src/common/hooks/useCategorizeRecentActivity.ts
  apps/cowswap-frontend/src/legacy/state/orders/actions.ts
  apps/cowswap-frontend/src/legacy/state/orders/mocks.ts
  apps/cowswap-frontend/src/legacy/state/orders/reducer.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/mocks/orderMock.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/appData/utils/fullAppData.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts
  apps/cowswap-frontend/src/modules/limitOrders/updaters/AlternativeLimitOrderUpdater.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersReceiptModal/hooks.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/OrderContextMenu.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/orders.mock.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/types.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
  apps/cowswap-frontend/src/modules/trade/state/alternativeOrder/atoms.ts
  apps/cowswap-frontend/src/modules/trade/state/alternativeOrder/const.ts
  apps/cowswap-frontend/src/modules/trade/state/alternativeOrder/hooks.ts
  apps/cowswap-frontend/src/modules/trade/state/alternativeOrder/index.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap
  apps/cowswap-frontend/src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  apps/cowswap-frontend/src/pages/LimitOrders/AlternativeLimitOrder.tsx
  apps/cowswap-frontend/src/utils/orderUtils/parseOrder.ts
  package.json
  yarn.lock
Labels: DONT_MERGE, On_hold

#4104 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4112 fix: replace dpaste lists with a version stored on github
  libs/tokens/src/const/tokensList.json
  libs/tokens/src/const/tokensLists.ts
Labels: RELEASE

#4114 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4117 fix(limit-orders): use ff for zero balance orders
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/pure/UnlockWidgetScreen/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
Labels: RELEASE

#4118 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4121 Release 2024-03-29 (release-please configs)
  release-please-config.json
Labels: RELEASE

#4123 ci: fix libs package jsons
  apps/widget-configurator/package.json
  libs/analytics/project.json
  libs/assets/project.json
  libs/balances-and-allowances/project.json
  libs/common-const/project.json
  libs/common-hooks/project.json
  libs/common-utils/project.json
  libs/core/project.json
  libs/ens/project.json
  libs/multicall/project.json
  libs/snackbars/project.json
  libs/tokens/project.json
  libs/ui/project.json
  libs/wallet/project.json
Labels: RELEASE
