Repository cowprotocol/cowswap, pull requests merged in 2024-05, with the labels that each got.

#4322 feat(widget): support different partnerFee recipient for networks
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.test.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
  libs/widget-lib/src/types.ts
Labels: Widget

#4339 chore: simplify ux and code
  libs/ui/src/pure/Tooltip/index.tsx
Labels: RELEASE

#4342 refactor: refactor and fix issues with tooltips
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/common/pure/PriceImpactIndicator/index.tsx
  apps/cowswap-frontend/src/legacy/components/Badge/RangeBadge.tsx
  apps/cowswap-frontend/src/legacy/components/Header/Polling.tsx
  apps/cowswap-frontend/src/legacy/components/HoverInlineText/index.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/QuestionHelperMod.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/index.tsx
  apps/cowswap-frontend/src/legacy/components/Settings/SettingsMod.tsx
  apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/FiatBalanceCell.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionSettings/TransactionSettingsMod.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/AccountIcon.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/SurplusCard.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/styled.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/styled.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/OrderType/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/RateImpactIndicator/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/FieldLabel.tsx
  apps/cowswap-frontend/src/modules/swap/containers/FeesDiscount/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/styled.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowDeadline/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenSourceTitle/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/RecipientRow/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Settings/SettingsBox.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeWarning/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeWidgetField/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/SwapPriceDifferenceWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/styled.tsx
  apps/cowswap-frontend/src/modules/twap/pure/AmountParts/index.tsx
  apps/cowswap-frontend/src/modules/twap/pure/AmountParts/styled.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/HelpTooltip/index.tsx
  libs/ui/src/pure/InfoTooltip/index.tsx
  libs/ui/src/pure/Popover/PopoverMod.tsx
  libs/ui/src/pure/Popover/index.tsx
  libs/ui/src/pure/Popover/styled.tsx
  libs/ui/src/pure/Tooltip/index.tsx
  libs/wallet/src/api/pure/ConnectWalletOption/index.tsx
Labels: RELEASE

#4340 chore: release of 2024-04-29
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/common/pure/PriceImpactIndicator/index.tsx
  apps/cowswap-frontend/src/legacy/components/Badge/RangeBadge.tsx
  apps/cowswap-frontend/src/legacy/components/Header/Polling.tsx
  apps/cowswap-frontend/src/legacy/components/HoverInlineText/index.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/QuestionHelperMod.tsx
  apps/cowswap-frontend/src/legacy/components/QuestionHelper/index.tsx
  apps/cowswap-frontend/src/legacy/components/Settings/SettingsMod.tsx
  apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/FiatBalanceCell.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionSettings/TransactionSettingsMod.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/AccountIcon.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/SurplusCard.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/styled.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/styled.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/OrderType/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/RateImpactIndicator/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/styled.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/FieldLabel.tsx
  apps/cowswap-frontend/src/modules/swap/containers/FeesDiscount/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/styled.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowDeadline/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenSourceTitle/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/RecipientRow/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Settings/SettingsBox.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeWarning/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeWidgetField/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/SwapPriceDifferenceWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/styled.tsx
  apps/cowswap-frontend/src/modules/twap/pure/AmountParts/index.tsx
  apps/cowswap-frontend/src/modules/twap/pure/AmountParts/styled.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/FollowPendingTxPopup/FollowPendingTxPopupUI.tsx
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/HelpTooltip/index.tsx
  libs/ui/src/pure/InfoTooltip/index.tsx
  libs/ui/src/pure/Popover/PopoverMod.tsx
  libs/ui/src/pure/Popover/index.tsx
  libs/ui/src/pure/Popover/styled.tsx
  libs/ui/src/pure/Tooltip/index.tsx
  libs/wallet/src/api/pure/ConnectWalletOption/index.tsx
  libs/widget-lib/src/types.ts
Labels: RELEASE

#4349 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4351 chore: release main
  .release-please-manifest.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4355 chore: release main
  .release-please-manifest.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4359 chore: up widget-lib deps
  libs/widget-lib/package.json
Labels: RELEASE

#4360 chore: up widget-lib version
  libs/widget-lib/package.json
Labels: RELEASE

#4362 chore(widget-react): bump version
  libs/widget-react/package.json
Labels: RELEASE

#4361 fix(cow-fi): fix buttons style
  apps/cow-fi/components/Button.tsx
Labels: RELEASE

#4365 feat: add coingecko token list to Gnosis chain
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
Labels: RELEASE

#4366 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4399 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4401 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4404 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4405 fix(widget): improve PartnerFeeDiscarded error
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
Labels: RELEASE

#4406 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4413 fix: clean outdated localStorage stores
  apps/cowswap-frontend/public/emergency.js
Labels: RELEASE

#4415 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4426 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#4420 [3] fix: remove custom wallets
  apps/cowswap-frontend/src/common/hooks/useWalletStatusIcon.tsx
  apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/ConfirmationPendingContentShell.tsx
  apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
  apps/cowswap-frontend/src/cow-react/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/NetworkSelector/index.tsx
  apps/cowswap-frontend/src/legacy/state/user/reducer.ts
  apps/cowswap-frontend/src/legacy/state/user/userWalletMigration.ts
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/AccountIcon.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
  apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
  apps/cowswap-frontend/src/modules/account/index.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/orders/containers/FulfilledOrderInfo/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/PendingOrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/AccountSelectorModal/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/AddToMetamask/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/WalletModal/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/WatchAssetInWallet/index.tsx
  apps/cowswap-frontend/src/modules/wallet/pure/StatusIcon/index.tsx
  apps/cowswap-frontend/src/modules/wallet/pure/WatchAssetInWallet/index.tsx
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/Account/styled.tsx
  apps/cowswap-frontend/src/test-utils.tsx
  libs/analytics/src/events/walletEvents.ts
  libs/common-const/src/addresses.ts
  libs/common-const/src/index.ts
  libs/ens/src/hooks/useENSRegistrarContract.ts
  libs/ens/src/hooks/useENSResolver.ts
  libs/ens/src/hooks/useENSResolverContract.ts
  libs/ens/src/hooks/useENSResolverMethod.ts
  libs/wallet-provider/README.md
  libs/wallet/src/api/hooks.ts
  libs/wallet/src/api/state/multiInjectedProvidersAtom.ts
  libs/wallet/src/api/types.ts
  libs/wallet/src/api/utils/connection.ts
  libs/wallet/src/constants.ts
  libs/wallet/src/index.ts
  libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
  libs/wallet/src/web3-react/Web3Provider/hooks/useOrderedConnections.ts
  libs/wallet/src/web3-react/Web3Provider/index.tsx
  libs/wallet/src/web3-react/connection/alpha.tsx
  libs/wallet/src/web3-react/connection/ambire.tsx
  libs/wallet/src/web3-react/connection/injectedOptions.tsx
  libs/wallet/src/web3-react/connection/keystone.tsx
  libs/wallet/src/web3-react/connection/tally.tsx
  libs/wallet/src/web3-react/connection/trust.tsx
  libs/wallet/src/web3-react/connection/walletConnectV2.tsx
  libs/wallet/src/web3-react/connectors/Injected/index.tsx
  libs/wallet/src/web3-react/connectors/TrezorConnector/index.ts
  libs/wallet/src/web3-react/connectors/WalletConnectV2Connector/index.tsx
  libs/wallet/src/web3-react/containers/WalletConnectLabeledOption/index.tsx
  libs/wallet/src/web3-react/hooks/useActivateConnector.ts
  libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
  libs/wallet/src/web3-react/hooks/useWalletMetadata.ts
  libs/wallet/src/web3-react/updater.ts
  libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts
  libs/wallet/src/web3-react/utils/isChainAllowed.ts
Labels: EIP6963

#4464 fix(notifications): don't fail when CMS API is down
  apps/cowswap-frontend/src/modules/notifications/hooks/useAccountNotifications.ts
Labels: RELEASE

#4463 fix(widget-cfg): don't request network switching with standalone mode
  apps/cowswap-frontend/index.html
  apps/widget-configurator/src/app/configurator/controls/NetworkControl.tsx
  apps/widget-configurator/src/app/configurator/hooks/useSyncWidgetNetwork.ts
  apps/widget-configurator/src/app/configurator/index.tsx
Labels: RELEASE

#4466 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/ens/CHANGELOG.md
  libs/ens/package.json
  libs/wallet-provider/CHANGELOG.md
  libs/wallet-provider/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#4494 fix: fix double negation
  apps/cowswap-frontend/src/common/pure/ChainPrefixWarning/index.tsx
Labels: RELEASE

#4497 fix(wallets): don't reset wallet on network switching
  libs/wallet/src/web3-react/connectors/Injected/index.tsx
Labels: RELEASE

#4499 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/ens/CHANGELOG.md
  libs/ens/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending
