Repository cowprotocol/cowswap, pull requests merged in 2024-01, with the labels that each got.

#3558 feat(networks): support Sepolia
  .github/workflows/vercel.yml
  README.md
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/src/api/gnosisProtocol/priceApi.ts
  apps/cowswap-frontend/src/common/hooks/featureFlags/useVerifiedQuotesEnabled.ts
  apps/cowswap-frontend/src/common/hooks/useIsProviderNetworkUnsupported.ts
  apps/cowswap-frontend/src/common/pure/NetworksList/index.tsx
  apps/cowswap-frontend/src/common/services/getQuoteCurrency/index.ts
  apps/cowswap-frontend/src/legacy/components/AMMsLogo/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/NetworkSelector/index.tsx
  apps/cowswap-frontend/src/legacy/components/OrderProgressBar/utils.ts
  apps/cowswap-frontend/src/legacy/state/claim/reducer.ts
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/advancedOrders/const.ts
  apps/cowswap-frontend/src/modules/permit/state/permittableTokensAtom.ts
  apps/cowswap-frontend/src/modules/permit/types.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/banners/TwapSuggestionBanner.tsx
  apps/cowswap-frontend/src/modules/twap/const.ts
  apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
  apps/cowswap-frontend/src/modules/usdAmount/services/fetchCurrencyUsdPrice.ts
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/claimData/index.ts
  apps/cowswap-frontend/src/pages/Account/ens/index.ts
  apps/cowswap-frontend/src/pages/Account/ens/types.ts
  libs/assets/src/cow-swap/network-sepolia-logo.svg
  libs/common-const/src/chainInfo.ts
  libs/common-const/src/common.ts
  libs/common-const/src/nativeAndWrappedTokens.ts
  libs/common-const/src/networks.ts
  libs/common-const/src/tokens.ts
  libs/common-utils/src/explorer.ts
  libs/common-utils/src/getExplorerLink.ts
  libs/common-utils/src/legacyAddressUtils.ts
  libs/core/src/gnosisSafe/index.ts
  libs/permit-utils/src/const.ts
  libs/tokens/src/const/defaultFavouriteTokens.ts
  libs/tokens/src/const/tokensList.json
  libs/tokens/src/migrations/tokensLegacyStateMigration.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/unsupportedTokensAtom.ts
  libs/tokens/src/state/tokens/userAddedTokensAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/tokens/src/utils/trustTokenLogoUrl.ts
  libs/wallet/src/web3-react/utils/switchChain.ts
  package.json
  yarn.lock
Labels: Sepolia

#3582 fix: disable Christmas theme
  apps/cowswap-frontend/src/legacy/components/Header/index.tsx
  apps/cowswap-frontend/src/legacy/theme/cowSwapAssets.ts
  apps/cowswap-frontend/src/legacy/theme/themeCovers/christmasCover.ts
  apps/cowswap-frontend/src/legacy/theme/themeCovers/defaultCover.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  libs/common-const/src/index.ts
  libs/common-const/src/theme.ts
  libs/common-utils/src/sound.ts
Labels: RELEASE

#3585 chore(main): release 1.54.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#3577 [1] chore(explorer): setup blank react project
  apps/explorer/.eslintrc.json
  apps/explorer/index.html
  apps/explorer/project.json
  apps/explorer/public/favicon.ico
  apps/explorer/src/app/app.spec.tsx
  apps/explorer/src/app/app.tsx
  apps/explorer/src/app/nx-welcome.tsx
  apps/explorer/src/assets/.gitkeep
  apps/explorer/src/main.tsx
  apps/explorer/tsconfig.app.json
  apps/explorer/tsconfig.json
  apps/explorer/tsconfig.spec.json
  apps/explorer/vite.config.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Explorer

#3580 feat(explorer): support Sepolia network
  apps/explorer/src/api/tenderly/tenderlyApi.ts
  apps/explorer/src/api/web3/hooks.ts
  apps/explorer/src/api/web3/index.ts
  apps/explorer/src/components/NetworkSelector/NetworkSelector.styled.ts
  apps/explorer/src/components/NetworkSelector/index.tsx
  apps/explorer/src/components/RedirectToSearch.tsx
  apps/explorer/src/components/layout/GenericLayout/Footer/index.tsx
  apps/explorer/src/consts/network.ts
  apps/explorer/src/consts/subgraphUrls.ts
  apps/explorer/src/cowSdk.ts
  apps/explorer/src/explorer/ExplorerApp.tsx
  apps/explorer/src/explorer/components/OrdersTableWidget/useSearchInAnotherNetwork.tsx
  apps/explorer/src/explorer/components/TransanctionBatchGraph/nodesBuilder.ts
  apps/explorer/src/explorer/const.ts
  apps/explorer/src/explorer/layout/Header.tsx
  apps/explorer/src/explorer/pages/Home/index.tsx
  apps/explorer/src/hooks/useGetOrders.tsx
  apps/explorer/src/services/helpers/getErc20Info.ts
  apps/explorer/src/services/helpers/tryGetOrderOnAllNetworks.ts
  apps/explorer/src/state/network/NetworkUpdater.tsx
  apps/explorer/src/state/network/hooks.ts
  apps/explorer/src/state/network/updater.tsx
  apps/explorer/src/styles/colours.ts
  apps/explorer/src/test/hooks/useDecomposedPath.test.tsx
  apps/explorer/src/utils/contract.ts
  apps/explorer/vite.config.ts
  package.json
  yarn.lock
Labels: Sepolia, Explorer

#3593 refactor(explorer): get rid of config yaml file
  apps/explorer/jest.config.ts
  apps/explorer/src/api/thegraph/index.ts
  apps/explorer/src/const.ts
  apps/explorer/src/test/api/getProviderByNetwork.test.ts
  apps/explorer/src/types/global-config.d.ts
Labels: Explorer

#3584 chore(explorer): migrate pending PRs from old repo
  README.md
  apps/explorer/.env.example
  apps/explorer/README.md
  apps/explorer/src/api/operator/index.ts
  apps/explorer/src/api/operator/operatorApi.ts
  apps/explorer/src/cowSdk.ts
  apps/explorer/src/explorer/pages/AppData/EncodePage.tsx
  apps/explorer/src/explorer/pages/AppData/config.tsx
  apps/explorer/vite.config.ts
Labels: Explorer

#3624 fix(explorer): cast string SupportedChainId to number
  apps/explorer/src/state/network/NetworkUpdater.tsx
Labels: RELEASE

#3635 chore: add lost changes from prev repo (PR #720)
  apps/explorer/README.md
  apps/explorer/src/components/AppData/DecodeAppData.tsx
  apps/explorer/src/components/orders/DetailsTable/index.tsx
  apps/explorer/src/utils/decodeFullAppData.ts
  apps/explorer/src/utils/getUiOrderType.ts
Labels: RELEASE

#3641 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3643 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3647 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3649 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3651 fix: don't crash when there is no fav tokens in new network
  libs/tokens/src/state/tokens/favouriteTokensAtom.ts
Labels: RELEASE

#3653 fix(explorer): change link to explorer version
  apps/explorer/src/components/layout/GenericLayout/Footer/config.ts
Labels: RELEASE

#3650 fix: don't display Sepolia in supported list when it is off
  apps/cowswap-frontend/src/common/containers/WalletUnsupportedNetworkBanner/index.tsx
  apps/cowswap-frontend/src/common/hooks/useUnsupportedNetworksText.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
Labels: RELEASE

#3652 fix(widget): simplify token lists config
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  libs/tokens/src/updaters/WidgetTokensListsUpdater/index.tsx
  libs/widget-lib/src/types.ts
Labels: RELEASE

#3654 Release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/cowswap-frontend/src/common/containers/WalletUnsupportedNetworkBanner/index.tsx
  apps/cowswap-frontend/src/common/hooks/useUnsupportedNetworksText.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/index.tsx
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/explorer/src/components/layout/GenericLayout/Footer/config.ts
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/src/state/tokens/favouriteTokensAtom.ts
  libs/tokens/src/updaters/WidgetTokensListsUpdater/index.tsx
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
  libs/widget-lib/src/types.ts
Labels: RELEASE

#3655 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3669 feat: update cow-sdk to 4.1.0 (#3660)
  package.json
  yarn.lock
Labels: RELEASE

#3672 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3674 feat(widget-react): update widget-lib
  libs/widget-react/package.json
Labels: RELEASE

#3675 chore: release main
  .release-please-manifest.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#3688 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3691 fix(permit): replace permit signer account
  libs/permit-utils/src/const.ts
Labels: RELEASE

#3694 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
Labels: autorelease: pending

#3614 feat(feeZero): deliver fee zero only to 10% of users
  apps/cowswap-frontend/src/common/hooks/featureFlags/useSwapZeroFee.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
Labels: DONT_MERGE

#3713 fix(permit): invalidate static and user permit cache
  apps/cowswap-frontend/src/modules/permit/state/permitCacheAtom.ts
Labels: RELEASE

#3699 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3716 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending
