Repository cowprotocol/cowswap, pull requests merged in 2024-10, with the labels that each got.

#4928 feat(hooks-store): update custom hook-dapps manifests periodically
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/updaters/iframeDappsManifestUpdater.tsx
  apps/cowswap-frontend/src/modules/hooksStore/validateHookDappManifest.tsx
Labels: Hooks store

#4920 feat(hooks-store): add dapp id to hook callData
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/AirdropHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/const.ts
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/useSBCDepositContract.ts
  apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAllHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useEditHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useInternalHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useMatchHooksToDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDappDetails/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/utils.ts
  apps/hook-dapp-omnibridge/public/manifest.json
  libs/hook-dapp-lib/package.json
  libs/hook-dapp-lib/src/consts.ts
  libs/hook-dapp-lib/src/hookDappsRegistry.json
  libs/hook-dapp-lib/src/index.ts
  libs/hook-dapp-lib/src/types.ts
  libs/hook-dapp-lib/src/utils.ts
Labels: Hooks store

#4921 feat(explorer): display order hooks details
  apps/explorer/src/components/AppData/DecodeAppData.tsx
  apps/explorer/src/components/orders/DetailsTable/index.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/HookItem/index.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/HookItem/styled.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/index.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/styled.tsx
  apps/explorer/src/hooks/useAppData.ts
  apps/explorer/tsconfig.json
  libs/hook-dapp-lib/package.json
Labels: Hooks store

#4925 feat(swap): display order hooks details
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/index.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/styled.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/index.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/styled.tsx
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/updaters/iframeDappsManifestUpdater.tsx
  apps/cowswap-frontend/src/modules/hooksStore/validateHookDappManifest.tsx
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapUpdaters/index.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useBaseSafeBundleFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useEthFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSafeBundleApprovalFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSafeBundleEthFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
  apps/cowswap-frontend/src/modules/swap/state/baseFlowContextSourceAtom.ts
  apps/cowswap-frontend/src/modules/swap/types/flowContext.ts
  apps/cowswap-frontend/src/modules/swap/updaters/BaseFlowContextUpdater.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  libs/hook-dapp-lib/src/utils.ts
Labels: Hooks store

#4935 feat: rescue funds from CoW Shed Proxy
  apps/cowswap-frontend/src/common/hooks/useCowShedHooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/useRescueFundsFromProxy.ts
  libs/abis/src/abis/CowShedContract.json
  libs/abis/src/generated/custom/CowShedContract.ts
  libs/abis/src/generated/custom/factories/CowShedContract__factory.ts
  libs/abis/src/generated/custom/factories/index.ts
  libs/abis/src/generated/custom/index.ts
  libs/abis/src/index.ts
  package.json
  yarn.lock
Labels: Hooks store

#4932 feat: add styling for hooksitems in review modal
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/index.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/HookItem/styled.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/index.tsx
  apps/cowswap-frontend/src/common/containers/OrderHooksDetails/styled.tsx
  apps/cowswap-frontend/src/modules/analytics/events.ts
  apps/cowswap-frontend/src/modules/hooksStore/index.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/validateHookDappManifest.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  apps/hook-dapp-omnibridge/public/manifest.json
  libs/hook-dapp-lib/src/utils.ts
Labels: Hooks store

#4938 feat(hooks-store): use dappId from hook model to match with dapp
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/appData/utils/fullAppData.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useEditHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useHookById.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/usePostHooksRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/state/hookDetailsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/utils.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap
  apps/cowswap-frontend/src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  libs/hook-dapp-lib/src/types.ts
  libs/hook-dapp-lib/src/utils.ts
  libs/permit-utils/src/lib/generatePermitHook.ts
  package.json
  yarn.lock
Labels: Hooks store

#4942 fix(widget-configurator): use different default partner fee address per chain
  apps/widget-configurator/src/app/configurator/consts.ts
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
Labels: RELEASE

#4946 chore: release main
  .release-please-manifest.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
Labels: autorelease: pending

#4952 chore: release main
  .release-please-manifest.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
Labels: autorelease: pending

#4980 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/abis/CHANGELOG.md
  libs/abis/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4983 fix(explorer): do not crash when appData is not parsed
  apps/explorer/src/components/orders/OrderHooksDetails/index.tsx
Labels: RELEASE

#4984 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4987 chore: up widget lib deps
  libs/widget-lib/package.json
Labels: RELEASE

#4988 chore: up widget react deps
  libs/widget-react/package.json
Labels: RELEASE

#4924 Add claim vesting iframe hook
  apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  libs/hook-dapp-lib/src/hookDappsRegistry.json
Labels: Hooks store

#4990 feat(hooks-store): add sell/buy amounts to hook-dapp context
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetupHooksStoreOrderParams.ts
  libs/hook-dapp-lib/src/types.ts
Labels: Hooks store

#4995 fix(explorer): display hook details of unknown hook-dapp
  apps/explorer/src/components/orders/OrderHooksDetails/HookItem/index.tsx
Labels: RELEASE

#4996 chore: update hook docs link
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
Labels: RELEASE

#4994 feat: display new label for cow amm
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
  libs/ui/src/index.ts
  libs/ui/src/pure/Badge/index.tsx
  libs/ui/src/pure/MenuBar/index.tsx
  libs/ui/src/pure/MenuBar/styled.ts
Labels: RELEASE

#5000 Release 17-10-2024
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/common/updaters/FeesUpdater/index.ts
  apps/cowswap-frontend/src/common/updaters/FeesUpdater/isRefetchQuoteRequired.ts
  apps/cowswap-frontend/src/common/updaters/FeesUpdater/quoteUsingSameParameters.ts
  apps/cowswap-frontend/src/legacy/components/NetworkAlert/NetworkAlert.tsx
  apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
  apps/cowswap-frontend/src/legacy/state/price/hooks.ts
  apps/cowswap-frontend/src/legacy/state/user/hooks.tsx
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetupHooksStoreOrderParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetDeadline.ts
  apps/cowswap-frontend/src/modules/injectedWidget/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/DeadlineInput/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/deadlines.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/DeadlineSelector/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/updaters/AlternativeLimitOrderUpdater.ts
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowDeadline/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowSlippageContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx
  apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/calculateBpsFromFeeMultiplier.test.ts
  apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/calculateBpsFromFeeMultiplier.ts
  apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/index.ts
  apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/useSmartSlippageFromBff.ts
  apps/cowswap-frontend/src/modules/swap/updaters/SmartSlippageUpdater/useSmartSlippageFromFeeMultiplier.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/TradeSelect/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
  apps/cowswap-frontend/src/modules/twap/pure/DeadlineSelector/index.tsx
  apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
  apps/cowswap-frontend/src/pages/LimitOrders/RegularLimitOrders.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/HookItem/index.tsx
  apps/widget-configurator/src/app/configurator/controls/DeadlineControl.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  libs/common-const/src/misc.ts
  libs/hook-dapp-lib/src/hookDappsRegistry.json
  libs/hook-dapp-lib/src/types.ts
  libs/ui/src/index.ts
  libs/ui/src/pure/Badge/index.tsx
  libs/ui/src/pure/MenuBar/index.tsx
  libs/ui/src/pure/MenuBar/styled.ts
  libs/widget-lib/src/types.ts
Labels: RELEASE

#5007 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#5009 fix(widget): ignore selected eip6963 provider when in widget
  apps/cowswap-frontend/src/cow-react/index.tsx
  libs/wallet/src/web3-react/Web3Provider/hooks/useEagerlyConnect.ts
  libs/wallet/src/web3-react/Web3Provider/index.tsx
Labels: RELEASE

#5008 feat(explorer): update explorer graph images
  apps/explorer/src/assets/img/CoW-protocol.svg
  apps/explorer/src/assets/img/Trader-variant.svg
  apps/explorer/src/assets/img/Trader.svg
Labels: RELEASE

#5011 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#4981 Va cowamm banner
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/CoWAmmBannerContent.tsx
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/arrowBackground.tsx
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/cowAmmBannerState.ts
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/dummyData.ts
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/index.tsx
  apps/cowswap-frontend/src/common/pure/CoWAMMBanner/styled.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
  libs/assets/src/cow-swap/icon-curve.svg
  libs/assets/src/cow-swap/icon-pancakeswap.svg
  libs/assets/src/cow-swap/icon-sushi.svg
  libs/assets/src/cow-swap/icon-uni.svg
  libs/ui/src/enum.ts
  libs/ui/src/theme/ThemeColorVars.tsx
Labels: 🧛‍♂️ Vampire

#4943 (feat: hook-store): create bundle hooks tenderly simulation
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/package.json
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetupHooksStoreOrderParams.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/tenderly/hooks/useGetTopTokenHolders.ts
  apps/cowswap-frontend/src/modules/tenderly/hooks/useTenderlyBundleSimulation.ts
  apps/cowswap-frontend/src/modules/tenderly/state/topTokenHolders.ts
  apps/cowswap-frontend/src/modules/tenderly/types.ts
  apps/cowswap-frontend/src/modules/tenderly/utils/bundleSimulation.ts
  apps/cowswap-frontend/src/modules/tenderly/utils/generateSimulationData.ts
  apps/cowswap-frontend/src/modules/tenderly/utils/getTokenTransferInfo.ts
  libs/hook-dapp-lib/src/types.ts
Labels: Hooks store

#5030 chore: do not enable yet in PRs by default
  apps/cowswap-frontend/src/common/hooks/useMenuItems.ts
Labels: RELEASE

#5041 fix(swap): fix safe eth-flow
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
Labels: RELEASE

#5040 fix(trade): use recipient address in order data
  apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
Labels: RELEASE

#5043 feat(yield): add unlock screen
  apps/cowswap-frontend/src/modules/yield/containers/YieldWidget/index.tsx
  apps/cowswap-frontend/src/modules/yield/hooks/useYieldSettings.ts
  apps/cowswap-frontend/src/modules/yield/state/yieldSettingsAtom.ts
Labels: 🧛‍♂️ Vampire

#5047 fix(swap): reset widget start after successful swap
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/propsChecker.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/types.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useHandleSwapOrEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useHandleSwap.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/yield/containers/YieldWidget/index.tsx
Labels: RELEASE

#5005 feat(yield): fetch balances for LP-tokens
  apps/cowswap-frontend/src/common/pure/VirtualList/index.tsx
  apps/cowswap-frontend/src/common/pure/VirtualList/styled.ts
  apps/cowswap-frontend/src/common/updaters/LpBalancesAndAllowancesUpdater.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenListsWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenListsWidget/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/LpTokenLists/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/LpTokenLists/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
  apps/cowswap-frontend/src/modules/yield/containers/YieldWidget/index.tsx
  apps/cowswap-frontend/src/modules/yield/hooks/useYieldSettings.ts
  apps/cowswap-frontend/src/modules/yield/state/yieldSettingsAtom.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/balancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
  libs/common-const/src/types.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/multicall.ts
  libs/tokens/src/const/lpTokensList.json
  libs/tokens/src/const/tokensLists.ts
  libs/tokens/src/hooks/tokens/useAllLpTokens.ts
  libs/tokens/src/index.ts
  libs/tokens/src/migrations/userAddedTokenListsAtomv2Migration.ts
  libs/tokens/src/services/fetchTokenList.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/tokens/src/utils/parseTokenInfo.ts
  libs/tokens/src/utils/tokenMapToListWithLogo.ts
  libs/tokens/src/utils/validateTokenList.ts
  libs/types/src/common.ts
  libs/ui/src/containers/ExternalLink/index.tsx
  libs/ui/src/enum.ts
  libs/ui/src/index.ts
  libs/ui/src/pure/InfoTooltip/index.tsx
  libs/ui/src/pure/Loader/styled.tsx
  libs/ui/src/theme/ThemeColorVars.tsx
Labels: 🧛‍♂️ Vampire

#5052 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#5013 feat(yield): use lp-token in widget
  apps/cowswap-frontend/src/common/updaters/LpBalancesAndAllowancesUpdater.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenListsWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenPage/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenPage/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/LpTokenLists/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/LpTokenLists/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ModalHeader/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/state/selectTokenWidgetAtom.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useAutoImportTokensState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNavigateOnCurrencySelection.ts
  apps/cowswap-frontend/src/modules/yield/hooks/useLpTokensWithBalances.ts
  apps/cowswap-frontend/src/modules/yield/hooks/usePoolsInfo.ts
  apps/cowswap-frontend/src/modules/yield/shared.ts
  apps/cowswap-frontend/src/modules/yield/state/poolsInfoAtom.ts
  apps/cowswap-frontend/src/modules/yield/updaters/PoolsInfoUpdater/index.tsx
  apps/cowswap-frontend/src/modules/yield/updaters/PoolsInfoUpdater/mockPoolInfo.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/tokens/src/const/tokensLists.ts
  libs/tokens/src/hooks/tokens/useTokenBySymbolOrAddress.ts
  libs/tokens/src/index.ts
  libs/tokens/src/pure/TokenLogo/index.tsx
  libs/tokens/src/state/environmentAtom.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
Labels: 🧛‍♂️ Vampire

#5018 feat(yield): define token category by default for selection
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/common/updaters/orders/OrdersFromApiUpdater.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/RescueFundsFromProxy/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/LpTokenListsWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/getDefaultTokenListCategories.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOpenTokenSelectWidget.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/state/selectTokenWidgetAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/utils/tokensListSorter.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/yield/hooks/useLpTokensWithBalances.ts
  apps/cowswap-frontend/src/modules/yield/shared.ts
  apps/cowswap-frontend/src/modules/yield/updaters/PoolsInfoUpdater/index.tsx
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/common-const/src/types.ts
  libs/tokens/src/hooks/tokens/useAllActiveTokens.ts
  libs/tokens/src/hooks/tokens/useAllLpTokens.ts
  libs/tokens/src/index.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
  libs/tokens/src/utils/tokenMapToListWithLogo.ts
  libs/types/src/common.ts
Labels: 🧛‍♂️ Vampire
