Repository cowprotocol/cowswap, pull requests merged in 2024-12, with the labels that each got.

#5144 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/ens/CHANGELOG.md
  libs/ens/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
Labels: autorelease: pending

#5149 Release 2024-12-04
  apps/cow-fi/next-env.d.ts
  apps/cow-fi/pages/mev-blocker.tsx
  apps/cowswap-frontend/src/common/hooks/useCancelOrder/useSendOnChainCancellation.test.tsx
  apps/cowswap-frontend/src/common/hooks/useSafeMemo.test.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.test.ts
  apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdAmount.test.tsx
  apps/explorer/src/test/hooks/useDecomposedPath.test.tsx
  apps/explorer/src/test/hooks/useSafeState.hooks.test.tsx
  apps/explorer/src/test/hooks/useSearchSubmit.test.tsx
  apps/explorer/src/test/hooks/useTable.test.tsx
  apps/sdk-tools/.env
  apps/sdk-tools/.env.production
  apps/sdk-tools/index.html
  apps/sdk-tools/jest.config.ts
  apps/sdk-tools/package.json
  apps/sdk-tools/project.json
  apps/sdk-tools/public/apple-touch-icon.png
  apps/sdk-tools/public/favicon-dark-mode.png
  apps/sdk-tools/public/favicon-light-mode.png
  apps/sdk-tools/public/manifest.json
  apps/sdk-tools/public/safari-pinned-tab.svg
  apps/sdk-tools/src/SdkTools.tsx
  apps/sdk-tools/src/assets/.gitkeep
  apps/sdk-tools/src/main.tsx
  apps/sdk-tools/tsconfig.app.json
  apps/sdk-tools/tsconfig.json
  apps/sdk-tools/tsconfig.spec.json
  apps/sdk-tools/vite.config.ts
  package.json
  yarn.lock
Labels: RELEASE

#5157 fix(twap): fix orders fetching
  apps/cowswap-frontend/src/api/cowProtocol/hooks.ts
Labels: RELEASE

#5158 fix: update safe fee tooltip label
  apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFeeTooltip.ts
  apps/cowswap-frontend/src/modules/volumeFee/index.ts
Labels: RELEASE

#5159 Release 2024-12-05
  apps/cowswap-frontend/src/api/cowProtocol/hooks.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeFeesAndCosts/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFeeTooltip.ts
  apps/cowswap-frontend/src/modules/volumeFee/index.ts
Labels: RELEASE

#5160 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5161 fix: add safe apps fee in Base network
  apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
Labels: RELEASE

#5162 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5171 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#5187 fix(volume-fee): control safe app fees for stablecoins with ff
  apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
  libs/common-const/src/tokens.ts
Labels: RELEASE

#5188 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5192 fix: add more stablecoins in fees logic
  libs/common-const/src/tokens.ts
Labels: RELEASE

#5193 chore: release main
  .release-please-manifest.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5194 fix(cow-fi): add info about base launch
  apps/cow-fi/app/(main)/legal/cowswap-terms/page.tsx
Labels: RELEASE

#5195 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#5196 fix(cowfi): reduce cms requests cache time to 5 min
  apps/cow-fi/next.config.js
  apps/cow-fi/services/cms/index.ts
Labels: RELEASE

#5197 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#5200 fix(twap): cache fb handler verification for 10min
  apps/cowswap-frontend/src/modules/twap/services/verifyExtensibleFallback.ts
  apps/cowswap-frontend/src/modules/twap/updaters/FallbackHandlerVerificationUpdater.tsx
Labels: RELEASE

#5206 fix(cowfi): fix pages crashes
  apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx
  apps/cow-fi/app/(main)/tokens/[tokenId]/page.tsx
  apps/cow-fi/services/tokens/index.ts
Labels: RELEASE

#5215 Revert "feat(wallets): add metaMask SDK connector (#5028)"
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  libs/wallet/src/api/state/multiInjectedProvidersAtom.ts
  libs/wallet/src/api/types.ts
  libs/wallet/src/api/utils/connection.ts
  libs/wallet/src/index.ts
  libs/wallet/src/web3-react/connection/injectedOptions.tsx
  libs/wallet/src/web3-react/connection/metaMaskSdk.tsx
  libs/wallet/src/web3-react/connectors/metaMaskSdk/index.ts
  libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts
  libs/wallet/src/web3-react/utils/isChainAllowed.ts
  package.json
  yarn.lock
Labels: RELEASE

#5209 fix(hooks-store): disable selling eth
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/BundleTxWrapBanner/index.tsx
Labels: RELEASE

#5180 feat(volume-fee): free some assets from fee
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/volumeFee/index.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/cowswapFeeAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/taxFreeAssetsAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/updaters/TaxFreeAssetsUpdater.tsx
Labels: RELEASE

#5202 fix(twap): display a warning when fbh was changed after twap order
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/SetupFallbackHandlerWarning/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useSetupFallbackHandler.ts
  apps/cowswap-frontend/src/modules/twap/index.ts
  apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
Labels: RELEASE

#5213 feat: add winter theme 🎅
  apps/cowswap-frontend/public/audio/success-winterTheme.mp3
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/styled.ts
  apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
  libs/assets/src/images/background-cowswap-christmas-dark-medium.svg
  libs/assets/src/images/background-cowswap-christmas-dark-small.svg
  libs/assets/src/images/background-cowswap-christmas-dark.svg
  libs/assets/src/images/background-cowswap-christmas-light-medium.svg
  libs/assets/src/images/background-cowswap-christmas-light-small.svg
  libs/assets/src/images/background-cowswap-christmas-light.svg
  libs/assets/src/images/logo-cowswap-christmas-dark.svg
  libs/assets/src/images/logo-cowswap-christmas-light.svg
  libs/common-const/src/theme.ts
  libs/ui/src/pure/ProductLogo/index.tsx
  libs/ui/src/types.ts
  package.json
  yarn.lock
Labels: RELEASE

#5214 feat: warn about unsigned orders, and hide not relevant orders
  apps/explorer/src/components/orders/DetailsTable/index.tsx
  apps/explorer/src/components/orders/OrdersUserDetailsTable/ToggleFilter.tsx
  apps/explorer/src/components/orders/OrdersUserDetailsTable/index.tsx
  apps/explorer/src/components/orders/UnsignedOrderWarning/index.tsx
Labels: RELEASE

#5219 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#5207 fix(orders-table): display allowance warning in Safe
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useGetOrdersToCheckPendingPermit.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrdersTable.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useGetPermitInfo.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useOrdersPermitStatus.ts
  apps/cowswap-frontend/src/modules/permit/index.ts
  apps/cowswap-frontend/src/modules/permit/state/ordersPermitStatusAtom.ts
  apps/cowswap-frontend/src/modules/permit/updaters/PendingPermitUpdater.ts
  apps/cowswap-frontend/src/utils/orderUtils/getOrderPermitAmount.ts
  libs/abis/src/index.ts
Labels: RELEASE

#5222 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#5230 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/abis/CHANGELOG.md
  libs/abis/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5236 fix: allow any safe-like apps
  libs/wallet/src/web3-react/connection/safe.tsx
Labels: RELEASE

#5237 chore: release main
  .release-please-manifest.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5240 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#5244 fix(eth-flow): set chainId explicitly when sending ethFlow tx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
Labels: RELEASE

#5246 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5250 fix(widget): do not display Christmas background
  apps/cowswap-frontend/src/common/constants/common.ts
  apps/cowswap-frontend/src/cow-react/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/styled.ts
  libs/snackbars/src/containers/SnackbarsWidget/index.tsx
  libs/snackbars/src/hooks/useAnchorPosition.ts
  libs/ui/src/pure/MenuBar/index.tsx
Labels: RELEASE

#5251 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/snackbars/CHANGELOG.md
  libs/snackbars/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#5253 fix: fix order filled condition for permit check
  apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.ts
Labels: RELEASE

#5254 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5258 ci: deploy some apps preview only when PR has label
  README.md
  tools/scripts/ignore-build-step.js
Labels: preview-widget-cfg
