Repository cowprotocol/cowswap, pull requests merged in 2024-04, with the labels that each got.

#4136 fix(widget): update snippets corresponding to the code
  apps/widget-configurator/src/app/embedDialog/const.ts
  apps/widget-configurator/src/app/embedDialog/utils/formatParameters.ts
  apps/widget-configurator/src/app/embedDialog/utils/htmlExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/jsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/reactTsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/tsExample.ts
Labels: RELEASE

#4135 Release 2024-04-01
  apps/cowswap-frontend/public/audio/slot-machine.mp3
  apps/cowswap-frontend/src/common/hooks/featureFlags/useIsAprilFoolsEnabled.ts
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/common/pure/CurrencySelectButton/index.tsx
  apps/cowswap-frontend/src/common/pure/CurrencySelectButton/styled.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useImFeelingLucky/gchainTokenAddresses.json
  apps/cowswap-frontend/src/modules/swap/hooks/useImFeelingLucky/index.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useImFeelingLucky/luckyTokens.tokenlist.json
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/styled.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormButtonContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
  apps/widget-configurator/src/app/embedDialog/const.ts
  apps/widget-configurator/src/app/embedDialog/utils/formatParameters.ts
  apps/widget-configurator/src/app/embedDialog/utils/htmlExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/jsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/reactTsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/tsExample.ts
  libs/common-utils/src/sound.ts
  libs/tokens/src/const/tokensList.json
  libs/tokens/src/const/tokensLists.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/ui/src/pure/Button/index.tsx
Labels: RELEASE

#4137 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4144 fix(widget): update widget code snippets
  apps/widget-configurator/src/app/embedDialog/const.ts
  apps/widget-configurator/src/app/embedDialog/utils/jsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/reactTsExample.ts
  apps/widget-configurator/src/app/embedDialog/utils/tsExample.ts
Labels: RELEASE

#4151 chore: remove unused files
  apps/cowswap-frontend/src/legacy/components/earn/styled.ts
  libs/assets/src/cow-swap/cowswap-logo.svg
  libs/assets/src/cow-swap/menu.svg
  libs/assets/src/images/arrow-down-blue.svg
  libs/assets/src/images/arrow-down-grey.svg
  libs/assets/src/images/big_unicorn.png
  libs/assets/src/images/circle-grey.svg
  libs/assets/src/images/circle.svg
  libs/assets/src/images/dropdown-blue.svg
  libs/assets/src/images/dropup-blue.svg
  libs/assets/src/images/ethereum-logo.png
  libs/assets/src/images/gas-icon.svg
  libs/assets/src/images/link.svg
  libs/assets/src/images/magnifying-glass.svg
  libs/assets/src/images/menu.svg
  libs/assets/src/images/noise.png
  libs/assets/src/images/plus-blue.svg
  libs/assets/src/images/plus-grey.svg
  libs/assets/src/images/portisIcon.png
  libs/assets/src/images/question-mark.svg
  libs/assets/src/images/question.svg
  libs/assets/src/images/router-icon-grey.svg
  libs/assets/src/images/sandtexture.webp
  libs/assets/src/images/santa-hat.png
  libs/assets/src/images/spinner.svg
  libs/assets/src/images/squiggle.png
  libs/assets/src/images/survey-orb.svg
  libs/assets/src/images/token-list-logo.png
  libs/assets/src/images/token-list/lists-dark.png
  libs/assets/src/images/token-list/lists-light.png
  libs/assets/src/images/token-logo.png
  libs/assets/src/images/tokenlistsgrouped.png
  libs/assets/src/images/trustWallet.png
  libs/assets/src/images/ukraine.png
  libs/assets/src/images/widget-screenshot.png
  libs/assets/src/images/x.svg
  libs/assets/src/images/xl_uni.png
  libs/assets/src/styles/styled.ts
  libs/assets/src/svg/QR.svg
  libs/assets/src/svg/arbitrum_logo.svg
  libs/assets/src/svg/celo_logo.svg
  libs/assets/src/svg/dot_line.svg
  libs/assets/src/svg/lightcircle.svg
  libs/assets/src/svg/logo.svg
  libs/assets/src/svg/logo_pink.svg
  libs/assets/src/svg/matic-token-icon.svg
  libs/assets/src/svg/optimism_logo.svg
  libs/assets/src/svg/optimistic_ethereum.svg
  libs/assets/src/svg/polygon-matic-logo.svg
  libs/assets/src/svg/static_route.svg
  libs/assets/src/svg/switch.svg
  libs/assets/src/svg/wordmark.svg
  libs/assets/src/svg/wordmark_pink.svg
  libs/assets/src/svg/wordmark_white.svg
Labels: Widget

#4159 feat(widget): customize images
  apps/cowswap-frontend/src/legacy/components/Header/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/styled.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
  apps/widget-configurator/src/app/configurator/controls/CustomImagesControl.tsx
  apps/widget-configurator/src/app/configurator/index.tsx
  libs/permit-utils/vite.config.ts
  libs/widget-lib/src/types.ts
Labels: Widget

#4162 feat(widget): use custom sounds in widget
  apps/cowswap-frontend/src/legacy/state/cowToken/middleware.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/state/orders/middleware/soundMiddleware.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/OnchainTransactionEventsUpdater.tsx
  apps/cowswap-frontend/src/modules/sounds/index.ts
  apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useCreateTwapOrder.tsx
  apps/widget-configurator/src/app/configurator/controls/CustomSoundsControl.tsx
  apps/widget-configurator/src/app/configurator/index.tsx
  libs/common-utils/src/index.ts
Labels: Widget

#4165 chore(widget-cfg): remove initial toast displaying
  apps/widget-configurator/src/app/configurator/hooks/useToastsManager.tsx
Labels: Widget

#4164 feat(widget): use custom tokens as virtual list
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/widget-configurator/src/app/configurator/consts.ts
  apps/widget-configurator/src/app/configurator/controls/AddCustomListDialog.tsx
  apps/widget-configurator/src/app/configurator/controls/TokenListControl.tsx
  apps/widget-configurator/src/app/configurator/hooks/useToastsManager.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  apps/widget-configurator/src/app/configurator/utils/validateURL.ts
  libs/tokens/src/hooks/lists/useAllListsList.ts
  libs/tokens/src/hooks/lists/useVirtualLists.ts
  libs/tokens/src/index.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/types.ts
  libs/tokens/src/updaters/WidgetTokensListsUpdater/index.tsx
  libs/tokens/src/updaters/WidgetVirtualListUpdater/index.tsx
  libs/widget-lib/src/types.ts
Labels: Widget

#4172 feat(widget): option to disable sounds
  apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
  apps/widget-configurator/src/app/configurator/controls/CustomSoundsControl.tsx
Labels: Widget

#4170 fix(widget): disable connect wallet button in dapp mode
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormButtonContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
Labels: Widget

#4176 docs(widget): split interfaces to fit docs
  libs/widget-lib/src/types.ts
Labels: RELEASE

#4175 feat(widget): option to hide safe banner
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/widget-configurator/src/app/configurator/index.tsx
  libs/widget-lib/src/types.ts
Labels: RELEASE, Widget

#4181 fix(widget): call disconnect when destroying the widget
  libs/widget-lib/src/cowSwapWidget.ts
Labels: RELEASE

#4174 fix(safe): handle tx via wc with 1/1 signs
  apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/actions.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/reducer.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/services/checkSafeTransaction.ts
Labels: RELEASE

#4193 fix: fix doesTokenMatchSymbolOrAddress app crash
  libs/common-utils/src/doesTokenMatchSymbolOrAddress.ts
Labels: RELEASE

#4187 feat(tokens-table): do not show explorer link for native token
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
Labels: RELEASE

#4189 fix(mobile): adjust fee display for tiny widths
  apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
Labels: RELEASE

#4182 fix: add partner fee too app-data only for swap orders
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
Labels: RELEASE

#4194 Bundle for widget
  apps/widget-configurator/public/manifest.json
  apps/widget-configurator/src/app/configurator/consts.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  libs/widget-lib/src/IframeCowEventEmitter.ts
  libs/widget-lib/src/IframeSafeSdkBridge.ts
  libs/widget-lib/src/cowSwapWidget.ts
Labels: RELEASE

#4188 feat(widget): use theme colors from URL
  apps/cowswap-frontend/index.html
  apps/cowswap-frontend/src/legacy/theme/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetPalette.ts
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validateWidgetParams.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.tsx
  apps/cowswap-frontend/src/modules/sounds/utils/sound.ts
  apps/widget-configurator/src/app/configurator/consts.ts
  apps/widget-configurator/src/app/configurator/hooks/useColorPaletteManager.ts
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/types.ts
  apps/widget-configurator/src/app/embedDialog/utils/sanitizeParameters.ts
  apps/widget-configurator/src/theme/hooks/useColorMode.ts
  libs/widget-lib/src/cowSwapWidget.ts
  libs/widget-lib/src/index.ts
  libs/widget-lib/src/themeUtils.ts
  libs/widget-lib/src/types.ts
  libs/widget-lib/src/urlUtils.ts
Labels: RELEASE

#4196 fix(widget): send trade params to widget integrator
  apps/cowswap-frontend/src/common/updaters/LogsUpdater.ts
  apps/cowswap-frontend/src/legacy/state/index.ts
  apps/cowswap-frontend/src/legacy/state/logs/hooks.ts
  apps/cowswap-frontend/src/legacy/state/logs/slice.ts
  apps/cowswap-frontend/src/legacy/state/logs/utils.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
  apps/cowswap-frontend/src/modules/trade/updaters/CommonTradeUpdater.tsx
  apps/widget-configurator/src/app/configurator/consts.ts
  libs/events/src/types/events.ts
  libs/events/src/types/index.ts
  libs/events/src/types/trade.ts
Labels: Widget

#4221 chore: fiat amounts type in OnTradeParamsPayload
  apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
  libs/events/src/types/trade.ts
Labels: RELEASE

#4222 chore(widget): add min receive amounts to TradeParams event
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/state/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
  apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts
  libs/events/src/types/trade.ts
Labels: RELEASE

#4225 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  changes.txt
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/events/CHANGELOG.md
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4239 fix(widget): don't reset palette state while navigating
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetPalette.ts
  libs/widget-lib/src/urlUtils.ts
Labels: RELEASE

#4226 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4280 fix(explorer): add sepolia token list
  apps/explorer/src/hooks/useTokenList.ts
Labels: RELEASE

#4282 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4287 fix(explorer): fix browser crashing
  apps/explorer/src/hooks/useErc20.ts
Labels: RELEASE

#4288 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4293 chore: release main
  .release-please-manifest.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4295 chore: release main
  .release-please-manifest.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4290 feat(swap): display warning for safe token
  apps/cowswap-frontend/src/modules/swap/containers/SafeTokenBanner.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  libs/assets/src/svg/brain.svg
Labels: RELEASE

#4296 feat(swap): improve read only message for safe
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
Labels: RELEASE

#4298 Release 2024-04-23
  apps/cowswap-frontend/src/modules/swap/containers/SafeTokenBanner.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/SafeReadOnlyButton.tsx
  apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  libs/assets/src/svg/brain.svg
  libs/common-hooks/src/index.ts
  libs/common-hooks/src/useIsAdvancedMode.ts
  libs/common-hooks/src/useIsLimitOrderMode.ts
  libs/common-hooks/src/useIsSwapMode.ts
  libs/tokens/src/state/tokens/unsupportedTokensAtom.ts
Labels: RELEASE

#4306 fix(widget): make account modal background transparent
  apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
Labels: Widget

#4272 feat(widget-cfg): update web3modal
  apps/widget-configurator/src/app/configurator/hooks/useProvider.ts
  apps/widget-configurator/src/app/configurator/hooks/useSyncWidgetNetwork.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/styled.ts
  apps/widget-configurator/src/main.tsx
  apps/widget-configurator/src/wagmiConfig.ts
  apps/widget-configurator/src/web3modalConfig.ts
  package.json
  yarn.lock
Labels: Widget

#4308 fix(widget): fix modals displaying
  apps/cowswap-frontend/src/common/pure/Modal/index.tsx
  apps/cowswap-frontend/src/common/state/openModalState.ts
  apps/cowswap-frontend/src/modules/injectedWidget/updaters/IframeResizer.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/styled.ts
  libs/widget-lib/src/cowSwapWidget.ts
  libs/widget-lib/src/types.ts
Labels: Widget
