Repository cowprotocol/cowswap, pull requests merged in 2024-06, with the labels that each got.

#4503 fix(arbitrum): replace GNO with COW in fav tokens
  libs/common-const/src/tokens.ts
  libs/tokens/src/const/defaultFavouriteTokens.ts
Labels: RELEASE

#4504 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending

#4511 Release/2024 06 05
  .github/workflows/ci.yml
  .github/workflows/ipfs.yml
  .github/workflows/vercel.yml
  README.md
  apps/cow-fi/.env
  apps/cow-fi/services/uniswap-price/apollo-client.ts
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx
  apps/cowswap-frontend/src/modules/usdAmount/apis/getCoingeckoUsdPrice.ts
  libs/common-const/src/bff.ts
  libs/common-const/src/index.ts
  libs/common-hooks/src/useAvailableChains.ts
  libs/tokens/src/services/searchTokensInApi.ts
Labels: RELEASE

#4512 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: RELEASE, autorelease: pending

#4518 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4539 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#4545 chore: release main
  .release-please-manifest.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
Labels: autorelease: pending

#4467 feat(limit-orders): allow partner fee (variant B)
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/defaultCurrencyInputProps.ts
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/types.ts
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/index.tsx
  apps/cowswap-frontend/src/legacy/state/orders/utils.ts
  apps/cowswap-frontend/src/mocks/tradeStateMock.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/hooks/useInjectedWidgetParams.ts
  apps/cowswap-frontend/src/modules/injectedWidget/index.ts
  apps/cowswap-frontend/src/modules/injectedWidget/state/injectedWidgetParamsAtom.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/helpers/tradeReceiveAmount.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRates/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useRateInfoAfterFees.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/styled.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.ts
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/propsChecker.ts
  apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/__snapshots__/tradeReceiveAmount.test.ts.snap
  apps/cowswap-frontend/src/modules/swap/helpers/tradeReceiveAmount.test.ts
  apps/cowswap-frontend/src/modules/swap/helpers/tradeReceiveAmount.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmount/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/ReceiveAmountInfo/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/styled.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/pure/RowFeeContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/pure/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/RowPartnerFee/index.tsx
  apps/cowswap-frontend/src/modules/trade/types/ReceiveAmountInfo.ts
  apps/cowswap-frontend/src/modules/trade/types/index.ts
  jest.setup.ts
  libs/ui-utils/src/index.ts
  libs/ui-utils/src/lib/return5.spec.ts
  libs/ui-utils/src/lib/return5.ts
  libs/ui/src/pure/Row/index.tsx
  libs/ui/src/pure/TokenAmount/index.tsx
Labels: partner fee

#4513 refactor: get rid of Gp prefix
  apps/cowswap-frontend/src/api/cowProtocol/api.ts
  apps/cowswap-frontend/src/api/cowProtocol/errors/OperatorError.ts
  apps/cowswap-frontend/src/api/cowProtocol/errors/QuoteError.ts
  apps/cowswap-frontend/src/api/cowProtocol/getIsOrderBookTypedError.ts
  apps/cowswap-frontend/src/api/cowProtocol/hooks.ts
  apps/cowswap-frontend/src/api/cowProtocol/index.ts
  apps/cowswap-frontend/src/api/cowProtocol/mock.ts
  apps/cowswap-frontend/src/api/cowProtocol/priceApi.ts
  apps/cowswap-frontend/src/common/hooks/useContract.ts
  apps/cowswap-frontend/src/common/hooks/useTradeSpenderAddress.ts
  apps/cowswap-frontend/src/common/state/totalSurplusState/updaters.ts
  apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/OrdersFromApiUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/PendingOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts
  apps/cowswap-frontend/src/common/updaters/orders/index.ts
  apps/cowswap-frontend/src/common/updaters/orders/utils.ts
  apps/cowswap-frontend/src/cow-react/sentry/index.ts
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
  apps/cowswap-frontend/src/legacy/components/Version/index.tsx
  apps/cowswap-frontend/src/legacy/hooks/useGetGpPriceStrategy.ts
  apps/cowswap-frontend/src/legacy/hooks/useRefetchPriceCallback.tsx
  apps/cowswap-frontend/src/legacy/state/gas/atoms.ts
  apps/cowswap-frontend/src/legacy/state/gas/gas-price-strategy-updater.tsx
  apps/cowswap-frontend/src/legacy/state/orders/helpers.tsx
  apps/cowswap-frontend/src/legacy/state/price/reducer.ts
  apps/cowswap-frontend/src/legacy/state/price/types.ts
  apps/cowswap-frontend/src/legacy/utils/price.ts
  apps/cowswap-frontend/src/legacy/utils/priceLegacy.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useGetInitialPrice.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitHasEnoughAllowance.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/utils/isUnsupportedTokenInQuote.ts
  apps/cowswap-frontend/src/modules/orders/hooks/useSWRProdOrders.ts
  apps/cowswap-frontend/src/modules/permit/hooks/useGeneratePermitHook.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/trade/utils/swapErrorHelper.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
  apps/cowswap-frontend/src/modules/twap/updaters/FullAmountQuoteUpdater.tsx
  apps/cowswap-frontend/src/modules/usdAmount/apis/getCowProtocolNativePrice.ts
  libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/common-const/src/common.ts
Labels: partner fee

#4546 feat(widget): use flexible config for partner fee
  apps/cowswap-frontend/src/legacy/state/orders/utils.ts
  apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts
  apps/cowswap-frontend/src/legacy/state/swap/extension.ts
  apps/cowswap-frontend/src/legacy/state/swap/trade.test.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataInfoUpdater.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataUpdater.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.test.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/TradeRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitOrderPartnerFeeAmount.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/ReceiptModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getAmountsForSignature.test.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapState.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/state/receiveAmountInfoAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/hooks/useVolumeFee.ts
  apps/cowswap-frontend/src/modules/volumeFee/index.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/types.ts
  libs/widget-lib/src/flexibleConfig.ts
  libs/widget-lib/src/index.ts
  libs/widget-lib/src/types.ts
Labels: partner fee

#4547 feat: cowswap volume fee
  apps/cowswap-frontend/src/common/state/featureFlagsState.ts
  apps/cowswap-frontend/src/common/updaters/FeatureFlagsUpdater.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
  apps/cowswap-frontend/src/modules/volumeFee/state/cowswapFeeAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
  libs/common-const/src/tokens.ts
Labels: partner fee

#4558 fix(trade): display recipient on confirm screen
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/RecipientRow/index.tsx
  apps/cowswap-frontend/src/modules/twap/const.ts
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
Labels: RELEASE

#4559 fix(slippage): always reset ethflow slippage when changing networks
  apps/cowswap-frontend/src/modules/swap/state/EthFlow/updaters/EthFlowSlippageUpdater.tsx
Labels: RELEASE

#4560 chore: adjust fee tooltip for cowswap fee
  apps/cowswap-frontend/src/modules/trade/pure/PartnerFeeRow/index.tsx
Labels: RELEASE

#4564 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui-utils/CHANGELOG.md
  libs/ui-utils/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#4567 refactor: fix MenuBar usage in cowswap
  apps/cow-fi/components/Layout/const.ts
  apps/cow-fi/components/Layout/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  libs/ui/src/pure/MenuBar/index.tsx
Labels: Redesign

#4566 fix(explorer): fix style typings conflicts
  apps/cow-fi/components/Layout/const.ts
  apps/cow-fi/components/Layout/index.tsx
  apps/cowswap-frontend/src/legacy/theme/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/explorer/src/components/common/Button/index.tsx
  apps/explorer/src/theme/index.tsx
  apps/explorer/src/theme/styles/index.ts
  apps/explorer/src/theme/styles/mediaQueries.ts
  apps/explorer/src/theme/types.ts
  apps/explorer/tsconfig.json
  libs/ui/src/consts.ts
  libs/ui/src/pure/Footer/footerAnimation.tsx
  libs/ui/src/pure/Footer/styled.ts
  libs/ui/src/pure/MenuBar/index.tsx
  libs/ui/src/pure/MenuBar/styled.ts
  libs/ui/src/pure/ProductLogo/index.tsx
  libs/ui/src/theme/typings.ts
  libs/ui/src/types.ts
Labels: Redesign

#4565 chore: fix lint errors after redesign
  apps/cow-fi/components/Layout/const.ts
  apps/cow-fi/components/Layout/index.tsx
  apps/cowswap-frontend/src/appzi.ts
  apps/cowswap-frontend/src/common/pure/AnimatedConfirmation/index.tsx
  apps/cowswap-frontend/src/cosmos.decorator.tsx
  apps/cowswap-frontend/src/cow-react/index.tsx
  apps/cowswap-frontend/src/legacy/components/FlashingLoading/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/NetworkSelector/index.tsx
  apps/cowswap-frontend/src/legacy/components/Loader/Logo/index.tsx
  apps/cowswap-frontend/src/legacy/components/NetworkAlert/NetworkAlert.tsx
  apps/cowswap-frontend/src/legacy/components/Settings/SettingsMod.tsx
  apps/cowswap-frontend/src/legacy/components/Settings/index.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/BalanceCell.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/FavouriteTokenButton.tsx
  apps/cowswap-frontend/src/legacy/state/orders/middleware/appziMiddleware.test.ts
  apps/cowswap-frontend/src/legacy/theme/index.tsx
  apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx
  apps/cowswap-frontend/src/modules/account/pure/ConnectedAccountBlocked/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/styled.ts
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  apps/cowswap-frontend/src/modules/wallet/pure/PendingView/index.tsx
  apps/cowswap-frontend/src/modules/wallet/pure/Web3StatusInner/styled.ts
  apps/cowswap-frontend/src/pages/Account/Governance.tsx
  apps/cowswap-frontend/src/pages/Account/Tokens/TokensOverview.tsx
  apps/cowswap-frontend/src/pages/Account/styled.tsx
  apps/explorer/src/components/common/Button/index.tsx
  apps/explorer/src/components/layout/GenericLayout/Header/index.tsx
  apps/explorer/src/theme/index.tsx
  apps/explorer/src/theme/styles/index.ts
  apps/explorer/src/theme/styles/mediaQueries.ts
  apps/explorer/src/theme/types.ts
  apps/explorer/tsconfig.json
  libs/analytics/src/index.ts
  libs/common-const/src/misc.ts
  libs/common-hooks/src/useIsOnline.ts
  libs/ui/src/consts.ts
  libs/ui/src/pure/Footer/footerAnimation.tsx
  libs/ui/src/pure/Footer/styled.ts
  libs/ui/src/pure/LoadingApp/index.tsx
  libs/ui/src/pure/MenuBar/index.tsx
  libs/ui/src/pure/MenuBar/styled.ts
  libs/ui/src/pure/ProductLogo/index.tsx
  libs/ui/src/theme/typings.ts
  libs/ui/src/types.ts
Labels: Redesign

#4587 fix: use router links in MenuBar
  apps/cow-fi/components/Layout/index.tsx
  apps/cowswap-frontend/src/common/constants/routes.ts
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  libs/ui/src/pure/MenuBar/index.tsx
  libs/ui/src/pure/MenuBar/styled.ts
Labels: Redesign

#4591 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/snackbars/CHANGELOG.md
  libs/snackbars/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui-utils/CHANGELOG.md
  libs/ui-utils/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#4597 chore: update unsupported FAQ link
  apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  libs/common-const/src/common.ts
Labels: Redesign

#4598 chore: fix limit orders table width
  apps/cowswap-frontend/src/modules/trade/pure/TradePageLayout/index.tsx
Labels: Redesign

#4599 chore: fix order progress bar style
  apps/cowswap-frontend/src/legacy/components/OrderProgressBar/styled.ts
  libs/snackbars/src/containers/SnackbarsWidget/index.tsx
Labels: Redesign

#4600 chore(swap): fix slippage button disabled style
  apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
Labels: Redesign

#4603 Release 2024-06-25
  apps/cow-fi/components/LazyLoadTweet.tsx
  apps/cow-fi/components/Link.tsx
  apps/cow-fi/data/cow-protocol/const.tsx
  apps/cow-fi/data/widget/const.tsx
  apps/cow-fi/pages/careers/index.tsx
  apps/cow-fi/pages/cow-protocol/index.tsx
  apps/cow-fi/pages/cow-swap/index.tsx
  apps/cow-fi/pages/index.tsx
  apps/cow-fi/pages/learn/index.tsx
  apps/cow-fi/pages/mev-blocker/index.tsx
  apps/cow-fi/pages/widget/index.tsx
  apps/cow-fi/styles/global.styles.ts
  apps/cow-fi/styles/styled.ts
  apps/cowswap-frontend/src/common/containers/WalletUnsupportedNetworkBanner/index.tsx
  apps/cowswap-frontend/src/legacy/components/Header/NetworkSelector/index.tsx
  apps/cowswap-frontend/src/legacy/components/OrderProgressBar/styled.ts
  apps/cowswap-frontend/src/legacy/components/Settings/index.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionSettings/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/UnsupportedCurrencyFooter/index.tsx
  apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersSettings/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/mainMenu/constants/mainMenu.tsx
  apps/cowswap-frontend/src/modules/notifications/containers/NotificationSidebar/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenTags/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Settings/SettingsIcon.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Settings/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Settings/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/TradePageLayout/index.tsx
  libs/assets/src/images/image-sandwich-guy.svg
  libs/assets/src/images/logo-curve-text.svg
  libs/assets/src/images/settings.svg
  libs/common-const/src/common.ts
  libs/snackbars/src/containers/SnackbarsWidget/index.tsx
  libs/ui/src/pure/Footer/index.tsx
  libs/ui/src/pure/MenuBar/index.tsx
Labels: RELEASE

#4604 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#4607 Release 2024-06-25.1
  apps/cow-fi/components/LazyLoadTweet.tsx
  apps/cow-fi/pages/cow-swap/index.tsx
  apps/explorer/src/components/orders/FilledProgress/index.tsx
Labels: RELEASE

#4615 Release 2024-06-25
  apps/cowswap-frontend/src/common/pure/PoweredFooter/index.tsx
  apps/cowswap-frontend/src/legacy/components/CowProtocolLogo/index.tsx
  apps/cowswap-frontend/src/legacy/components/OrderProgressBar/styled.ts
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/index.tsx
  apps/cowswap-frontend/src/theme/mapWidgetTheme.ts
  apps/explorer/config-default.yaml
  apps/explorer/src/assets/img/CowProtocol-icon.svg
  apps/explorer/src/assets/img/CowProtocol-logo-white.svg
  apps/explorer/src/explorer/components/TransanctionBatchGraph/styled.ts
  libs/assets/src/cow-swap/anniversary-icons.png
  libs/assets/src/cow-swap/attention.svg
  libs/assets/src/cow-swap/cow.svg
  libs/assets/src/cow-swap/cow_token.svg
  libs/assets/src/cow-swap/cow_v2.svg
  libs/assets/src/cow-swap/cowswap-diagram.png
  libs/assets/src/cow-swap/experiment.svg
  libs/assets/src/cow-swap/fortune-cookie.png
  libs/assets/src/cow-swap/gasless.png
  libs/assets/src/cow-swap/gno.png
  libs/assets/src/cow-swap/important.svg
  libs/assets/src/cow-swap/loading.svg
  libs/assets/src/cow-swap/mev.png
  libs/assets/src/cow-swap/network-goerli-logo.svg
  libs/assets/src/cow-swap/round-arrow.svg
  libs/assets/src/cow-swap/transaction-arrows.svg
  libs/assets/src/cow-swap/transaction-confirmed.svg
  libs/assets/src/cow-swap/usdc.png
  libs/assets/src/cow-swap/vCOW.png
  libs/assets/src/cow-swap/wxdai.png
  libs/assets/src/cow-swap/xdai.png
  libs/assets/src/images/blue-loader.svg
  libs/assets/src/images/icon-appzi.svg
  libs/assets/src/images/vCOW.svg
  libs/ui/src/pure/Footer/index.tsx
  libs/wallet/src/api/assets/alpha.svg
  libs/wallet/src/api/assets/ambire.svg
  libs/wallet/src/api/assets/keystone.svg
  libs/wallet/src/api/assets/ledger.svg
  libs/wallet/src/api/assets/safe-logo.svg
  libs/wallet/src/api/assets/tally.svg
  libs/wallet/src/api/assets/trust.svg
  libs/wallet/src/api/assets/wallet-connect-v2.png
  libs/wallet/src/api/assets/zengo.svg
  libs/wallet/src/web3-react/connection/coinbase.tsx
Labels: RELEASE

#4617 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#4631 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending

#4632 Release 2024-06-27-1
  apps/cowswap-frontend/src/common/hooks/useContract.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
  libs/common-const/src/common.ts
  libs/common-utils/src/getEthFlowContractAddress.ts
  libs/common-utils/src/index.ts
Labels: RELEASE

#4633 chore: release main
  .release-please-manifest.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
Labels: autorelease: pending
