Repository cowprotocol/cowswap, pull requests merged in 2024-09, with the labels that each got.

#4850 Release 2024-09-03
  apps/cow-fi/const/meta.ts
  apps/cow-fi/pages/careers/index.tsx
  apps/cow-fi/services/ashByHq/index.ts
  apps/cow-fi/services/greenhouse/index.ts
Labels: RELEASE

#4851 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#4863 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4882 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#4875 fix(hooks-store): ignore permit data for sc wallets
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/appData/utils/appDataFilter.ts
  apps/cowswap-frontend/src/modules/appData/utils/buildAppData.ts
  apps/cowswap-frontend/src/modules/appData/utils/typedHooks.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/permit/index.ts
  apps/cowswap-frontend/src/modules/permit/utils/appDataContainsHooks.ts
  apps/cowswap-frontend/src/modules/permit/utils/callDataContainsPermitSigner.ts
  apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
Labels: Hooks store

#4878 feat(hooks-store): add order params and signer to hook dapp context
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useOrderParams.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/usePostHooksRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetOrderParams.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetupHooksStoreOrderParams.ts
  apps/cowswap-frontend/src/modules/hooksStore/index.ts
  apps/cowswap-frontend/src/modules/hooksStore/state/orderParamsStateAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts
Labels: Hooks store

#4899 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending

#4903 fix: don't request network switching at page load
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Labels: RELEASE

#4904 Release 17-09-2024 1
  apps/cowswap-frontend/src/api/blocknative.ts
  apps/cowswap-frontend/src/common/updaters/CancelReplaceTxUpdater.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PostHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/useDragAndDrop.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookList/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
  apps/cowswap-frontend/src/pages/Hooks/index.tsx
  package.json
  yarn.lock
Labels: RELEASE

#4908 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#4890 [6] feat(hooks-store): integrate an iframe hook-dapp for example
  .github/workflows/npm.yml
  apps/cow-fi/tsconfig.json
  apps/cowswap-frontend/src/common/hooks/useMenuItems.ts
  apps/cowswap-frontend/src/modules/appData/state/atoms.ts
  apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PostHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useEditHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useHookById.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/usePostHooksRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/iframeHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/hookDetailsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/tsconfig.json
  apps/cowswap-frontend/vite.config.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/CoWShedHooks.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/consts.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/contracts.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/CoWShed.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/CoWShedFactory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/ComposableCoW.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/ExtensibleFallbackHandler.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/TWAP.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/common.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/CoWShedFactory__factory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/CoWShed__factory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/ComposableCoW__factory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/ExtensibleFallbackHandler__factory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/TWAP__factory.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/factories/index.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/generated/index.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/index.ts
  apps/hook-dapp-omnibridge/src/app/cowShed/types.ts
  apps/hook-dapp-omnibridge/src/app/hook-dapp/buildHook.ts
  apps/hook-dapp-omnibridge/src/app/hook-dapp/consts.ts
  apps/hook-dapp-omnibridge/src/app/hook-dapp/index.tsx
  apps/hook-dapp-omnibridge/src/app/hook-dapp/omnilogo.png
  apps/hook-dapp-omnibridge/src/app/weiroll/index.ts
  apps/hook-dapp-omnibridge/src/main.tsx
  apps/hook-dapp-omnibridge/vite.config.ts
  libs/hook-dapp-lib/package.json
  libs/hook-dapp-lib/src/hookDappIframeTransport.ts
  libs/hook-dapp-lib/src/initCoWHookDapp.ts
  libs/hook-dapp-lib/src/types.ts
  libs/iframe-transport/package.json
  libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts
  libs/widget-lib/src/messages.ts
  package.json
  release-please-config.json
  yarn.lock
Labels: Hooks store

#4905 feat(hooks-store): style hook store
  apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/BuildHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/hook.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/iframeHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDappDetails/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDappDetails/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDetailHeader/styled.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  libs/ui/src/pure/BackButton/index.tsx
Labels: Hooks store

#4912 feat: styling tabs + counter
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/index.tsx
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/styled.tsx
  apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookSearchInput/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/AirdropHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddExternalHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAllHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useCustomHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useExternalHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveExternalHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/styled.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddExternalHookForm/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDappDetails/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListsTabs/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListsTabs/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/state/externalHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/hook-dapp-omnibridge/src/app/hook-dapp/index.tsx
  libs/hook-dapp-lib/README.md
  libs/hook-dapp-lib/src/types.ts
Labels: Hooks store

#4910 feat(hooks-store): import external hook-dapps
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/index.tsx
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/styled.tsx
  apps/cowswap-frontend/src/common/pure/NewModal/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookRegistryList/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookSearchInput/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/HooksStoreWidget/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/IframeDappContainer/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PostHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/PreHookButton/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/AirdropHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/ClaimGnoHookApp/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hookRegistry.tsx
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAddHook.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useAllHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useCustomHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useRemoveCustomHookDapp.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useSetRecipientOverride.ts
  apps/cowswap-frontend/src/modules/hooksStore/iframeHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/CustomDappLoader/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/styled.ts
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AppliedHookList/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookDappDetails/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListItem/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListItem/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListsTabs/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/HookListsTabs/styled.tsx
  apps/cowswap-frontend/src/modules/hooksStore/state/customHookDappsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/state/hookDetailsAtom.ts
  apps/cowswap-frontend/src/modules/hooksStore/types/hooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/utils.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/styled.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useResetRecipient.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/hook-dapp-omnibridge/public/manifest.json
  apps/hook-dapp-omnibridge/src/app/hook-dapp/index.tsx
  libs/hook-dapp-lib/README.md
  libs/hook-dapp-lib/src/types.ts
  libs/ui/src/index.ts
  libs/ui/src/pure/Input/index.tsx
Labels: Hooks store

#4917 fix: fix import list warning styles
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/index.tsx
  apps/cowswap-frontend/src/common/pure/ExternalSourceAlert/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ImportListModal/styled.ts
Labels: RELEASE

#4922 fix(explorer): get token logo url from known token lists
  apps/explorer/src/components/common/TokenDisplay/index.tsx
  apps/explorer/src/components/common/TokenImg.tsx
Labels: RELEASE

#4926 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/abis/CHANGELOG.md
  libs/abis/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/iframe-transport/CHANGELOG.md
  libs/iframe-transport/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
  libs/widget-react/CHANGELOG.md
  libs/widget-react/package.json
Labels: autorelease: pending
