Repository cowprotocol/cowswap, pull requests merged in 2024-02, with the labels that each got.

#3759 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#3772 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3814 fix(limit): placement error handling
  apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts
  apps/cowswap-frontend/src/common/hooks/useCancelOrder/index.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  apps/cowswap-frontend/src/modules/trade/utils/swapErrorHelper.ts
Labels: RELEASE

#3835 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3750 [1] feat(trade): update trade confirm modal design
  apps/cowswap-frontend/src/common/hooks/useModalState.ts
  apps/cowswap-frontend/src/common/pure/CurrencyAmountPreview/index.tsx
  apps/cowswap-frontend/src/common/pure/CurrencyAmountPreview/styled.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapHeader/SwapHeaderMod.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useAutoImportTokensState.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/ReceiveAmountTitle/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ReviewOrderModalAmountRow/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/hooks/useIsPriceChanged.ts
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/styled.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradePageLayout/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
  libs/assets/src/cow-swap/equal.svg
  libs/common-hooks/src/useTimeAgo.ts
  libs/ui/src/index.ts
  libs/ui/src/pure/BackButton/index.tsx
Labels: Trade confirm

#3751 [2] refactor(approve): replace LegacyConfirmationPendingContent by ConfirmationPendingContent
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveButton.tsx
  apps/cowswap-frontend/src/common/containers/ZeroApprovalModal/ZeroApprovalModal.tsx
  apps/cowswap-frontend/src/common/hooks/useApproveState.ts
  apps/cowswap-frontend/src/common/hooks/usePendingApprovalModal.tsx
  apps/cowswap-frontend/src/common/hooks/useShouldZeroApprove/shouldZeroApprove.ts
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.cosmos.tsx
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
  apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/ConfirmationPendingContent.cosmos.tsx
  apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/ConfirmationPendingContent.tsx
  apps/cowswap-frontend/src/common/pure/MetamaskApproveBanner/index.tsx
  apps/cowswap-frontend/src/common/pure/MetamaskApproveBanner/styled.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
  apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/index.ts
  apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/useApproveCallbackMod.ts
  apps/cowswap-frontend/src/lib/hooks/useApproval.ts
  apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useSetupEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/containers/EthFlow/index.tsx
  apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/TradeConfirmPendingContent.tsx
  apps/cowswap-frontend/src/modules/trade/containers/WrapNativeModal/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
  apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/InvestOption.tsx
Labels: Trade confirm

#3752 [3] refactor(zero-approval): collect files into module and use ConfirmationPendingContent
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveButton.tsx
  apps/cowswap-frontend/src/common/containers/ZeroApprovalModal/ZeroApprovalModal.cosmos.tsx
  apps/cowswap-frontend/src/common/containers/ZeroApprovalModal/ZeroApprovalModal.tsx
  apps/cowswap-frontend/src/common/hooks/useShouldZeroApprove/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWarnings/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrderCreationContext.ts
  apps/cowswap-frontend/src/modules/zeroApproval/containers/ZeroApprovalModal/ZeroApprovalModal.tsx
  apps/cowswap-frontend/src/modules/zeroApproval/containers/ZeroApprovalModal/index.tsx
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useNeedsZeroApproval.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/index.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/shouldZeroApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useZeroApprovalState.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useZeroApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useZeroApproveModalState.ts
  apps/cowswap-frontend/src/modules/zeroApproval/index.ts
  apps/cowswap-frontend/src/modules/zeroApproval/state/zeroApprovalState.ts
Labels: Trade confirm

#3753 [4] feat(trade): display trade modals as screens
  apps/cowswap-frontend/src/common/containers/MultipleOrdersCancellationModal/index.tsx
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveModal.tsx
  apps/cowswap-frontend/src/common/pure/CancellationModal/index.tsx
  apps/cowswap-frontend/src/common/pure/ConfirmationPendingContent/styled.tsx
  apps/cowswap-frontend/src/common/pure/OrderSubmittedContent/index.tsx
  apps/cowswap-frontend/src/common/pure/TransactionErrorContent/index.tsx
  apps/cowswap-frontend/src/common/pure/TransactionSubmittedContent/index.tsx
  apps/cowswap-frontend/src/legacy/components/CowSubsidyModal/index.tsx
  apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/OrderType/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/index.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ModalHeader/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/commonElements.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/LimitPriceRow.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/SlippageRow.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeBasicConfirmDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/TradeConfirmPendingContent.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetUpdaters.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/styled.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
  apps/cowswap-frontend/src/modules/trade/containers/WrapNativeModal/index.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/TwapConfirmDetails.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/tooltips.tsx
  apps/cowswap-frontend/src/modules/twap/index.ts
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
Labels: Trade confirm

#3754 [5] feat(swap): use common trade confirmation flow
  apps/cowswap-frontend/src/common/constants/common.ts
  apps/cowswap-frontend/src/common/hooks/useApproveCallback.ts
  apps/cowswap-frontend/src/common/pure/Modal/index.tsx
  apps/cowswap-frontend/src/common/updaters/FeesUpdater.ts
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/styled.ts
  apps/cowswap-frontend/src/legacy/components/swap/styleds.tsx
  apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts
  apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts
  apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
  apps/cowswap-frontend/src/legacy/state/application/hooks.ts
  apps/cowswap-frontend/src/legacy/state/application/reducer.test.ts
  apps/cowswap-frontend/src/legacy/state/application/reducer.ts
  apps/cowswap-frontend/src/legacy/state/cowToken/hooks.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/hooks/TransactionHooksMod.tsx
  apps/cowswap-frontend/src/legacy/state/types.ts
  apps/cowswap-frontend/src/legacy/theme/components.tsx
  apps/cowswap-frontend/src/modules/swap/containers/ConfirmSwapModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/EthFlow/hooks/useEthFlowActions.ts
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowFee/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Row/RowReceivedAfterSlippage/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapModals/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeBasicDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowFeeContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/swap/pure/TradeRates/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/styled.tsx
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/types.ts
  apps/cowswap-frontend/src/modules/swap/state/surplusModal.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx
  apps/cowswap-frontend/src/modules/zeroApproval/containers/ZeroApprovalModal/ZeroApprovalModal.cosmos.tsx
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/hooks.ts
  apps/cowswap-frontend/src/pages/Account/LockedGnoVesting/index.tsx
  apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/InvestOption.tsx
  apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/hooks/useApproveCallbackFromClaim.ts
  apps/cowswap-frontend/src/pages/Claim/InvestmentFlow/index.tsx
  apps/cowswap-frontend/src/pages/Claim/index.tsx
Labels: Trade confirm

#3755 [6] refactor: remove dead legacy code
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/LegacyConfirmationPendingContent.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/index.cosmos.tsx
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/ConfirmSwapModal/hooks.tsx
  apps/cowswap-frontend/src/legacy/components/swap/ConfirmSwapModal/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/FeeInformationTooltip.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapHeader/SwapHeaderMod.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapHeader/index.ts
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalFooter/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/index.tsx
  apps/cowswap-frontend/src/legacy/components/swap/SwapModalHeader/styled.ts
  apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/index.ts
  apps/cowswap-frontend/src/legacy/hooks/useApproveCallback/useApproveCallbackMod.ts
  apps/cowswap-frontend/src/legacy/hooks/useTransactionConfirmationModal.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapConfirmManager.ts
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowReceivedAfterSlippageContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/swap/pure/Row/RowReceivedAfterSlippageContent/index.tsx
  apps/cowswap-frontend/src/modules/swap/state/swapConfirmAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/AutoImportTokens/index.tsx
Labels: Trade confirm

#3851 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#3881 feat(token-lists): limit token lists by 5000 tokens
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOnTokenListAddingError.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokenListAddingError.ts
  apps/cowswap-frontend/src/modules/tokensList/index.ts
  apps/cowswap-frontend/src/modules/tokensList/state/tokenListAddingErrorAtom.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  apps/widget-configurator/src/app/configurator/consts.ts
  libs/tokens/src/hooks/lists/useAddList.ts
  libs/tokens/src/index.ts
  libs/tokens/src/migrations/tokensLegacyStateMigration.ts
  libs/tokens/src/migrations/userAddedTokenListsAtomv2Migration.ts
  libs/tokens/src/state/tokenLists/tokenListsActionsAtom.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/updaters/WidgetTokensListsUpdater/index.tsx
Labels: RELEASE

#3883 General style fixes
  apps/cowswap-frontend/src/common/pure/MetamaskApproveBanner/styled.tsx
  apps/cowswap-frontend/src/legacy/theme/baseTheme.tsx
  apps/cowswap-frontend/src/modules/wallet/pure/WalletModal/styled.tsx
  libs/tokens/src/pure/TokenLogo/index.tsx
  libs/ui/src/enum.ts
Labels: RELEASE

#3884 feat: style improvements
  apps/cowswap-frontend/src/common/pure/TradeLoadingButton/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormBlankButton/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/CenteredDots/index.tsx
  libs/ui/src/pure/LongLoadText/index.tsx
Labels: RELEASE

#3950 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending
