Repository cowprotocol/cowswap, pull requests merged in 2025-09, with the labels that each got.

#6206 fix(notifications): improve TG session management
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/src/modules/notifications/README.md
  apps/cowswap-frontend/src/modules/notifications/containers/ConnectTelegram.tsx
  apps/cowswap-frontend/src/modules/notifications/hooks/useTgAuthorization.ts
  apps/cowswap-frontend/src/modules/notifications/pure/TelegramConnectionStatus/index.tsx
  apps/cowswap-frontend/src/modules/notifications/services/getTelegramAuth.ts
Labels: notifications

#6209 fix(trade): do not close auto-import modal when account changes
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
Labels: RELEASE

#6210 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#6217 fix(swap): replace swap unlock screen banner header
  apps/cowswap-frontend/src/modules/swap/pure/CrossChainUnlockScreen/index.tsx
Labels: RELEASE

#6221 fix(swap): adjust swap banner header font size
  apps/cowswap-frontend/src/modules/swap/pure/CrossChainUnlockScreen/styled.tsx
Labels: RELEASE

#6259 chore: update `cow-sdk`
  package.json
  yarn.lock
Labels: RELEASE

#6269 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#6272 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
Labels: autorelease: pending

#6277 chore: release main
  .release-please-manifest.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending

#6295 fix(explorer): handle invalid order class
  apps/explorer/src/utils/getUiOrderType.ts
  package.json
Labels: RELEASE, Explorer

#6306 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending
