Repository cowprotocol/cowswap, pull requests merged in 2025-05, with the labels that each got.

#5658 fix(twap): base dai error v2
  libs/common-utils/src/tokens.test.ts
  libs/common-utils/src/tokens.ts
Labels: RELEASE

#5661 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
Labels: autorelease: pending

#5665 fix(twap): quote 405 error
  apps/cowswap-frontend/src/modules/twap/updaters/FullAmountQuoteUpdater.tsx
  apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
Labels: RELEASE

#5670 chore(release): 2025 05 07
  apps/cow-fi/app/(main)/careers/layout.tsx
  apps/cow-fi/app/(main)/careers/refer-to-earn/page.tsx
  apps/cow-fi/app/(main)/cow-amm/page.tsx
  apps/cow-fi/app/(main)/cow-protocol/page.tsx
  apps/cow-fi/app/(main)/cow-swap/page.tsx
  apps/cow-fi/app/(main)/widget/page.tsx
  apps/cow-fi/app/(mev-blocker)/mev-blocker/page.tsx
  apps/cow-fi/components/CareersPageContent.tsx
  apps/cow-fi/components/DaosPageComponent.tsx
  apps/cow-fi/data/cow-amm/const.tsx
  apps/cow-fi/data/cow-protocol/const.tsx
  apps/cow-fi/data/widget/const.tsx
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
  apps/cowswap-frontend/src/modules/account/containers/AccountDetails/SurplusCard.tsx
  apps/cowswap-frontend/src/modules/fortune/containers/FortuneWidget/index.tsx
  apps/cowswap-frontend/src/modules/notifications/containers/ConnectTelegram.tsx
  apps/cowswap-frontend/src/modules/notifications/pure/TelegramConnectionStatus/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/notifications/pure/TelegramConnectionStatus/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useAutoImportTokensState.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/SettingsTab/index.tsx
  apps/explorer/src/components/common/MenuDropdown/MainMenuTree.stories.tsx
  apps/explorer/src/components/common/MenuDropdown/MenuDropdownItem.stories.tsx
  apps/explorer/src/components/common/MenuDropdown/mainMenu.ts
  apps/explorer/src/components/orders/StatusLabel/index.tsx
  apps/explorer/src/explorer/const.ts
  libs/tokens/src/hooks/tokens/useTokenBySymbolOrAddress.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/tokens/src/utils/mergeTokenMaps.ts
  libs/ui/src/pure/Button/index.tsx
Labels: RELEASE

#5669 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#5588 feat(bridge): use real bridge provider
  apps/cowswap-frontend/src/modules/appData/index.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeProvider.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/bridge/mocks.ts
  apps/cowswap-frontend/src/modules/bridge/state/bridgeProviderAtom.ts
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOnSelectChain.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useSourceChainId.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useNavigateOnCurrencySelection.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeNavigate.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeState.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useQuoteParams.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  apps/cowswap-frontend/src/modules/tradeQuote/services/fetchAndProcessQuote.ts
  apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/getBridgeQuoteSigner.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteDeadline.test.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
  apps/cowswap-frontend/src/modules/twap/updaters/FullAmountQuoteUpdater.tsx
  apps/cowswap-frontend/src/tradingSdk/bridgingSdk.ts
  apps/cowswap-frontend/src/tradingSdk/getErc20Tokens.ts
  libs/common-const/src/chainInfo.ts
  libs/common-utils/src/getQuoteUnsupportedToken.ts
  libs/tokens/src/hooks/tokens/unsupported/useAreUnsupportedTokens.ts
  libs/tokens/src/hooks/tokens/unsupported/useIsTradeUnsupported.ts
  libs/tokens/src/hooks/tokens/useNetworkLogo.ts
  libs/tokens/src/index.ts
  libs/tokens/src/state/environmentAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/types/src/common.ts
  package.json
  yarn.lock
Labels: Bridge

#5633 feat(bridge): display quote error and details
  apps/cowswap-frontend/src/api/cowProtocol/api.ts
  apps/cowswap-frontend/src/api/cowProtocol/errors/QuoteError.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/BridgeQuoteDetails.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormBlankButton/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts
  apps/cowswap-frontend/src/modules/tradeQuote/services/fetchAndProcessQuote.ts
  apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
Labels: Bridge

#5675 fix: null change to trigger cowswap build
  apps/cowswap-frontend/src/react-app-env.d.ts
Labels: RELEASE

#5676 fix: skip quote fetching when appData is not changed
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
  package.json
  yarn.lock
Labels: RELEASE, preview-widget-cfg

#5677 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5695 fix: update curve link (#5694)
  apps/cow-fi/data/cow-protocol/const.tsx
  apps/cowswap-frontend/src/modules/yield/lpPageLinks.ts
Labels: RELEASE

#5696 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5673 feat(bridge): bridge details UI
  apps/cow-fi/app/(main)/cow-swap/page.tsx
  apps/cow-fi/components/Layout/const.ts
  apps/cow-fi/data/cow-swap/const.tsx
  apps/cow-fi/data/home/const.tsx
  apps/cow-fi/data/mev-blocker/const.tsx
  apps/cow-fi/styles/global.styles.ts
  apps/cowswap-frontend/src/common/pure/OrderProgressBar/container/ProgressImageWrapper.tsx
  apps/cowswap-frontend/src/common/pure/OrderProgressBar/steps/AnimatedToken.tsx
  apps/cowswap-frontend/src/common/pure/OrderProgressBar/steps/styled.ts
  apps/cowswap-frontend/src/common/pure/ProtocolIcons/index.tsx
  apps/cowswap-frontend/src/common/pure/ProtocolIcons/styled.tsx
  apps/cowswap-frontend/src/common/pure/RateInfo/index.tsx
  apps/cowswap-frontend/src/common/pure/ReceiveAmount/styled.tsx
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/styled.ts
  apps/cowswap-frontend/src/modules/bridge/constants/bridgeProviders.ts
  apps/cowswap-frontend/src/modules/bridge/constants/index.ts
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/BridgeRouteBreakdown.cosmos.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/index.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/styled.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/index.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeProviderDetails.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useParsedAmountWithUsd.ts
  apps/cowswap-frontend/src/modules/bridge/index.ts
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeAccordionSummary.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/styled.ts
  apps/cowswap-frontend/src/modules/bridge/pure/NetworkLogo/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/NetworkLogo/styled.ts
  apps/cowswap-frontend/src/modules/bridge/pure/SwapStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TokenAmountDisplay/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TokenAmountDisplay/styled.ts
  apps/cowswap-frontend/src/modules/bridge/styles.ts
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/bridge/utils/fees.ts
  apps/cowswap-frontend/src/modules/bridge/utils/index.ts
  apps/cowswap-frontend/src/modules/bridge/utils/status.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeTotalCostsDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/ReceiveAmountTitle/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/Row/styled.ts
  apps/cowswap-frontend/src/modules/trade/pure/Settings/styled.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/SettingsTab/styled.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
  libs/assets/src/cow-swap/icon-refund.svg
  libs/assets/src/cow-swap/spinner.svg
  libs/assets/src/images/bungee-logo.svg
  libs/common-utils/src/displayTime.test.ts
  libs/common-utils/src/displayTime.tsx
  libs/common-utils/src/index.ts
  libs/ui/src/colors.ts
  libs/ui/src/enum.ts
  libs/ui/src/theme/ThemeColorVars.tsx
  libs/ui/src/theme/baseTheme.tsx
  libs/ui/src/theme/typings.ts
Labels: Bridge

#5707 fix(twap): do not reset output amount
  apps/cowswap-frontend/src/modules/trade/hooks/useSetupTradeAmountsFromUrl.ts
Labels: RELEASE, preview-widget-cfg

#5704 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/permit-utils/CHANGELOG.md
  libs/permit-utils/package.json
Labels: autorelease: pending

#5711 fix: handle presign tx signature for Safe via Rabby
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
Labels: RELEASE

#5714 fix: fix order presign flow
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
Labels: RELEASE

#5723 refactor(bridge): enhance TradeDetailsAccordion and related components
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/BridgeRouteBreakdown.cosmos.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/StopHeader/StopHeader.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/SwapStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/styles.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeTotalCostsDetails/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
Labels: Bridge

#5718 fix(bridge): distinguish tokens usd prices corr to network
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/BridgeRouteBreakdown.cosmos.tsx
  apps/cowswap-frontend/src/modules/usdAmount/apis/getCowProtocolUsdPrice.ts
  apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdAmount.test.tsx
  apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdPrice.ts
  apps/cowswap-frontend/src/modules/usdAmount/index.ts
  apps/cowswap-frontend/src/modules/usdAmount/services/fetchCurrencyUsdPrice.ts
  apps/cowswap-frontend/src/modules/usdAmount/state/usdRawPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/state/usdTokenPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/types.ts
  apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.test.tsx
  apps/cowswap-frontend/src/modules/usdAmount/updaters/UsdPricesUpdater.ts
  apps/cowswap-frontend/src/modules/usdAmount/utils/usdPriceStateKey.ts
  apps/cowswap-frontend/src/modules/usdAmount/utils/usdcPriceLoader.ts
Labels: Bridge

#5708 feat(bridge): enhance BridgeRouteBreakdown and related components
  apps/cowswap-frontend/src/common/hooks/useSolversInfo.ts
  apps/cowswap-frontend/src/common/pure/ToggleArrow/ToggleArrow.tsx
  apps/cowswap-frontend/src/common/pure/ToggleArrow/index.ts
  apps/cowswap-frontend/src/common/pure/ToggleArrow/styled.ts
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/index.tsx
  apps/cowswap-frontend/src/common/pure/TradeDetailsAccordion/styled.ts
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/BridgeRouteBreakdown.cosmos.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/index.tsx
  apps/cowswap-frontend/src/modules/bridge/containers/BridgeRouteBreakdown/styled.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/index.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useParsedAmountWithUsd.ts
  apps/cowswap-frontend/src/modules/bridge/index.ts
  apps/cowswap-frontend/src/modules/bridge/lazy.ts
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeStopDetails/styled.ts
  apps/cowswap-frontend/src/modules/bridge/pure/RecipientDisplay/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/StopHeader/StopHeader.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/StopStatus/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/SwapStopDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/SwapStopDetails/styled.ts
  apps/cowswap-frontend/src/modules/bridge/pure/TokenAmountDisplay/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TokenAmountDisplay/styled.ts
  apps/cowswap-frontend/src/modules/bridge/styles.ts
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/bridge/utils/fees.ts
  apps/cowswap-frontend/src/modules/bridge/utils/status.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapRateDetails/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/pure/BridgeQuoteDetails.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeTotalCostsDetails/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/ReceiveAmountTitle/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
Labels: Bridge

#5728 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
Labels: autorelease: pending

#5735 fix: detect EIP7702 account
  libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
Labels: RELEASE

#5734 fix(tokens): fix tokens mixing from different chains
  apps/cowswap-frontend/src/modules/trade/hooks/useAutoImportTokensState.ts
  libs/tokens/src/hooks/tokens/useAllActiveTokens.ts
  libs/tokens/src/hooks/tokens/useAllLpTokens.ts
  libs/tokens/src/hooks/tokens/useSearchToken.ts
  libs/tokens/src/hooks/tokens/useTokenBySymbolOrAddress.ts
  libs/tokens/src/hooks/tokens/useTokensByAddressMap.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/state/tokens/userAddedTokensAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.tsx
  libs/tokens/src/updaters/UserAddedTokensUpdater/index.ts
  libs/tokens/src/utils/mergeTokenMaps.ts
  libs/tokens/src/utils/tokenMapToListWithLogo.ts
  libs/wallet/src/web3-react/hooks/useIsSmartContractWallet.ts
Labels: RELEASE

#5739 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5744 fix: remove UserAddedTokensUpdater
  libs/tokens/src/updaters/TokensListsUpdater/index.tsx
Labels: RELEASE

#5745 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending

#5750 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
Labels: autorelease: pending

#5725 feat(bridge): add bridge types and order type guard
  apps/explorer/src/types/bridge.ts
  apps/explorer/src/utils/orderTypeGuards.ts
Labels: Bridge

#5771 fix(twap): use indexedDB to persist state
  apps/cowswap-frontend/src/common/hooks/useCancelOrder/useSendOnChainCancellation.test.tsx
  apps/cowswap-frontend/src/common/hooks/useUpdateTradeApproveState.ts
  apps/cowswap-frontend/src/common/updaters/GasUpdater.tsx
  apps/cowswap-frontend/src/modules/ethFlow/updaters/InFlightOrderFinalizeUpdater.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useCustomHookDapps.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useOrderParams.ts
  apps/cowswap-frontend/src/modules/hooksStore/hooks/useReorderHooks.ts
  apps/cowswap-frontend/src/modules/hooksStore/updaters/iframeDappsManifestUpdater.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/hooks/useExecutionPriceUsdValue.ts
  apps/cowswap-frontend/src/modules/limitOrders/containers/RateInput/hooks/useRateDisplayedValue.ts
  apps/cowswap-frontend/src/modules/limitOrders/updaters/SetupLimitOrderAmountsFromUrlUpdater.tsx
  apps/cowswap-frontend/src/modules/notifications/containers/NotificationsList/index.tsx
  apps/cowswap-frontend/src/modules/notifications/hooks/useUnreadNotifications.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTablePagination/index.tsx
  apps/cowswap-frontend/src/modules/permit/hooks/useGetCachedPermit.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapSettings.ts
  apps/cowswap-frontend/src/modules/swap/state/swapRawStateAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useSelectTokenWidgetState.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useUpdateSelectTokenWidgetState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useIsEoaEthFlow.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useIsWrapOrUnwrap.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeConfirmState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeScreenState.ts
  apps/cowswap-frontend/src/modules/trade/state/isEoaEthFlowAtom.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/hooks/useIsSlippageModified.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/hooks/useIsSmartSlippageApplied.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/hooks/useTradeSlippage.ts
  apps/cowswap-frontend/src/modules/twap/containers/AmountParts/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/SetupFallbackHandlerWarning/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useEmulatedPartOrders.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useFetchTwapOrdersFromSafe.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrderByChildId.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrdersTokens.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapPartOrdersList.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapSlippage.ts
  apps/cowswap-frontend/src/modules/twap/services/fetchTwapOrdersFromSafe.ts
  apps/cowswap-frontend/src/modules/twap/state/twapPartOrdersAtom.ts
  apps/cowswap-frontend/src/modules/twap/updaters/CreatedInOrderBookOrdersUpdater.tsx
  apps/cowswap-frontend/src/modules/twap/updaters/PartOrdersUpdater.tsx
  apps/cowswap-frontend/src/modules/yield/hooks/useYieldDerivedState.ts
  apps/cowswap-frontend/src/modules/yield/hooks/useYieldSettings.ts
  apps/cowswap-frontend/src/modules/yield/state/yieldRawStateAtom.ts
  libs/core/src/jotaiStore.ts
  package.json
  yarn.lock
Labels: RELEASE
