Repository cowprotocol/cowswap, pull requests merged in 2025-06, with the labels that each got.

#5772 feat(bridge): display bridging progress
  apps/cowswap-frontend/src/legacy/components/TopLevelModals/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeQuoteAmounts.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useUpdateBridgeOrderData.ts
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/CollapsibleBridgeRoute/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProgressDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/QuoteDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/PreparingBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/ReceivedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/QuoteBridgeContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/QuoteSwapContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/SwapResultContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/styles.ts
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/constants.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/containers/SurplusModalSetup/index.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/hooks/useOrderProgressBarProps.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/hooks/useOrderSubmittedContent.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/hooks/useWithConfetti.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/OrderProgressBar/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/StepsWrapper.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/TransactionSubmittedContent/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/BridgingStep.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/ExecutingStep.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/FinishedStep.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/InitialStep.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/SolvingStep.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/stepsRegistry.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/types.ts
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
  apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts
  apps/cowswap-frontend/src/utils/orderUtils/getFilledAmounts.ts
  package.json
  yarn.lock
Labels: Bridge

#5793 fix(safe-wc): pass chainId to wallet_sendCalls in the body of the request
  libs/wallet/src/api/hooks/useSendBatchTransactions.ts
Labels: RELEASE

#5794 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5808 fix(limit-orders): display prices in orders table
  apps/cowswap-frontend/src/common/updaters/orders/SpotPricesUpdater.ts
  apps/cowswap-frontend/src/modules/orders/state/spotPricesAtom.ts
  apps/cowswap-frontend/src/modules/usdAmount/hooks/useUsdPrice.ts
  apps/cowswap-frontend/src/modules/usdAmount/index.ts
Labels: Bug, RELEASE

#5811 fix(trade): hide auto-slippage warning when amounts are not set
  apps/cowswap-frontend/src/modules/tradeSlippage/containers/HighSuggestedSlippageWarning/index.tsx
Labels: Bug, RELEASE

#5804 chore: remove unused package
  package.json
  yarn.lock
Labels: dependencies

#5818 fix(trade): reset loading state when confirm wasn't happen
  apps/cowswap-frontend/src/modules/trade/containers/TradeConfirmModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
Labels: RELEASE

#5846 fix(explorer): adjust items order in order details
  apps/explorer/src/components/orders/DetailsTable/BaseDetailsTable.tsx
  apps/explorer/src/components/orders/DetailsTable/FullDetailsTable.tsx
  apps/explorer/src/components/orders/DetailsTable/SummaryDetailsTable.tsx
  apps/explorer/src/components/orders/DetailsTable/index.tsx
Labels: RELEASE

#5851 fix: bump InputAmountNotSet validation priority
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
Labels: Bridge

#5850 fix(bridge): do not display chais when source chain not supported
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/utils/mapChainInfo.ts
Labels: Bridge

#5849 fix(bridge): do not crash calculating usd price in unsupported chain
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/modules/usdAmount/state/usdTokenPricesAtom.ts
  libs/common-const/src/tokens.ts
Labels: Bridge

#5837 fix(bridge): enable bridging only in Swap
  apps/cowswap-frontend/src/common/updaters/BridgingEnabledUpdater.ts
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useShouldDisplayBridgeDetails.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOpenTokenSelectWidget.ts
  libs/common-hooks/src/useIsBridgingEnabled.ts
  libs/tokens/src/hooks/tokens/useNetworkLogo.ts
Labels: Bridge

#5865 fix(bridge): use explorer link from provider networks
  apps/cowswap-frontend/src/common/pure/ClickableAddress/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/index.tsx
  libs/common-utils/src/getExplorerLink.ts
Labels: Bridge

#5872 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
Labels: autorelease: pending

#5874 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending

#5860 fix(bridge): display only supported favorite tokens
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/FavoriteTokensList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokensContent/index.tsx
  package.json
  yarn.lock
Labels: Bridge

#5869 fix(bridge): display full list of networks
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.tsx
Labels: Bridge

#5882 fix(bridge): display quote errors
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  package.json
  yarn.lock
Labels: Bridge

#5895 feat(bridge): add collapsible banner for proxy account information
  apps/cowswap-frontend/src/modules/bridge/pure/ProxyAccountBanner/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/QuoteSwapContent/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/ProxyRecipient/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/pure/CoWShedFAQ.tsx
  apps/cowswap-frontend/src/modules/cowShed/pure/TokensInProxyBanner/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapConfirmModal/index.tsx
  libs/ui/src/containers/InlineBanner/index.tsx
  libs/ui/src/index.ts
  libs/ui/src/pure/CollapsibleInlineBanner/index.tsx
  libs/ui/src/pure/CollapsibleInlineBanner/styled.ts
  libs/ui/src/pure/DismissableInlineBanner/index.tsx
  libs/ui/src/pure/InlineBanner/InlineBanner/index.tsx
  libs/ui/src/pure/InlineBanner/InlineBanner/styled.ts
  libs/ui/src/pure/InlineBanner/index.cosmos.tsx
  libs/ui/src/pure/InlineBanner/index.ts
  libs/ui/src/pure/InlineBanner/shared/BannerIcon.tsx
  libs/ui/src/pure/InlineBanner/shared/types.ts
Labels: Bridge
