Repository cowprotocol/cowswap, pull requests merged in 2025-08, with the labels that each got.

#6075 fix(cow-fi): update articles page with caching strategy and type annotations
  apps/cow-fi/app/(learn)/learn/[article]/page.tsx
  apps/cow-fi/app/(learn)/learn/articles/[[...pageIndex]]/page.tsx
  apps/cow-fi/next.config.ts
Labels: RELEASE

#6067 fix(bridge): broken network switching when try to select the same network as dst in token select
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
Labels: Bridge

#6073 feat: use account proxy label for consistent naming
  apps/cowswap-frontend/src/modules/account/containers/CowShedInfo/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/menuConsts.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProxyAccountBanner/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/CoWShedWidget/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/ProxyRecipient/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/RecoverFundsWidget/RecoverFundsButtons.tsx
  apps/cowswap-frontend/src/modules/cowShed/hooks/useRecoverFundsCallback.ts
  apps/cowswap-frontend/src/modules/cowShed/pure/CoWShedFAQ.tsx
  apps/cowswap-frontend/src/modules/cowShed/pure/TokensInProxyBanner/index.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/explorer/src/components/orders/BridgeDetailsTable/bridgeDetailsTooltips.tsx
  apps/explorer/src/components/orders/DetailsTable/detailsTableTooltips.tsx
  libs/common-const/src/common.ts
Labels: Bridge

#6071 feat: use received label constant for consistency in bridging content
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/FailedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/PendingBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/ReceivedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/RefundedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/steps/FinishedStep.tsx
  apps/explorer/src/components/orders/BridgeDetailsTable/BridgeDetailsContent/index.tsx
  libs/common-const/src/common.ts
Labels: Bridge

#6090 Hotfix 2025-07-31
  apps/cowswap-frontend/src/common/hooks/useSwapResultsContext.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts
  apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
  libs/common-utils/src/doesTokenMatchSymbolOrAddress.ts
Labels: RELEASE

#6076 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
Labels: autorelease: pending

#6147 Hotfix 2025-08-12
  apps/cowswap-frontend/src/common/hooks/useContract.ts
  apps/cowswap-frontend/src/modules/cowShed/containers/InvalidCoWShedSetup/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/hooks/useCurrentAccountProxy.ts
  apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapOrdersAuthMulticall.ts
  apps/cowswap-frontend/src/modules/wallet/containers/AccountSelectorModal/index.tsx
  apps/cowswap-frontend/src/pages/error/AnySwapAffectedUsers/useIsAnySwapAffectedUser.ts
  apps/cowswap-frontend/src/utils/orderUtils/getOrderFilledAmount.ts
  apps/cowswap-frontend/src/utils/orderUtils/getOrderSurplus.ts
  libs/abis/src/abis/Multicall3.json
  libs/abis/src/generated/custom/Multicall3.ts
  libs/balances-and-allowances/src/hooks/useIsBlockNumberRelevant.ts
  libs/balances-and-allowances/src/hooks/useNativeTokensBalances.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/common-const/src/common.ts
  libs/hook-dapp-lib/src/consts.ts
  libs/hook-dapp-lib/src/hookDappsRegistry.ts
  libs/hook-dapp-lib/src/utils.ts
  libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts
  libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/hooks/useSingleContractMultipleData.ts
  libs/multicall/src/multicall.ts
  libs/multicall/src/types.ts
  libs/permit-utils/src/lib/generatePermitHook.ts
  libs/permit-utils/src/types.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.tsx
Labels: RELEASE

#6176 fix(lens): follow up fixes
  apps/explorer/src/api/tenderly/tenderlyApi.ts
  apps/explorer/src/explorer/components/TransanctionBatchGraph/hooks.ts
  libs/common-const/src/tenderly.ts
  libs/common-const/src/tokens.ts
  libs/hook-dapp-lib/src/hookDappsRegistry.ts
  libs/tokens/src/const/tokensList.json
Labels: preview-widget-cfg

#6190 fix(tokens): check token lists loading state
  libs/tokens/src/state/tokens/allTokensAtom.ts
Labels: RELEASE

#6196 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending
