Repository cowprotocol/cowswap, pull requests merged in 2025-07, with the labels that each got.

#5919 feat(bridge): add bungee prod api urls
  apps/cowswap-frontend/src/tradingSdk/bridgingSdk.ts
Labels: Bridge

#5924 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/core/CHANGELOG.md
  libs/core/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/multicall/CHANGELOG.md
  libs/multicall/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5932 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5934 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5906 feat(trade): slippage config for integrators
  apps/cowswap-frontend/src/modules/hooksStore/dapps/PermitHookApp/index.tsx
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validatePartnerFee.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validateSlippage.ts
  apps/cowswap-frontend/src/modules/injectedWidget/utils/validateWidgetParams.ts
  apps/cowswap-frontend/src/modules/permit/hooks/usePermitInfo.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapConfirmModal/useLabelsAndTooltips.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapSettings.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWarnings/index.tsx
  apps/cowswap-frontend/src/modules/trade/types/TradeType.ts
  apps/cowswap-frontend/src/modules/trade/types/TradeTypeInfo.ts
  apps/cowswap-frontend/src/modules/trade/types/index.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/containers/HighSuggestedSlippageWarning/index.tsx
  apps/cowswap-frontend/src/modules/tradeSlippage/hooks/useSlippageConfig.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/hooks/useTradeSlippage.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/index.tsx
  apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/utils/slippage.ts
  apps/cowswap-frontend/src/modules/tradeSlippage/utils/slippageBpsToPercent.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/DeadlineTransactionSettings/hooks/useCustomDeadline.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/DeadlineTransactionSettings/utils/index.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/RowSlippage/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TransactionSlippageInput/hooks/useSlippageInput.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TransactionSlippageInput/hooks/useSlippageWarningParams.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TransactionSlippageInput/index.tsx
  apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  apps/widget-configurator/src/app/configurator/index.tsx
  apps/widget-configurator/src/app/configurator/types.ts
  libs/common-utils/src/clamp-value.ts
  libs/common-utils/src/index.ts
  libs/widget-lib/src/flexibleConfig.ts
  libs/widget-lib/src/index.ts
  libs/widget-lib/src/resolveFlexibleConfigValues.ts
  libs/widget-lib/src/types.ts
Labels: preview-widget-cfg

#5942 fix(bridge): display deposit tx link in pending state
  apps/cowswap-frontend/src/modules/bridge/pure/DepositTxLink/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TransactionLink/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/PendingBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/ReceivedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/index.tsx
Labels: Bridge

#5943 fix(bridge): do not mix balances from different chains
  apps/cowswap-frontend/src/modules/combinedBalances/hooks/useCurrencyAmountBalanceCombined.ts
Labels: Bridge

#5953 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/widget-lib/CHANGELOG.md
Labels: autorelease: pending

#5955 fix(balances): update balances after network switching
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/combinedBalances/state/balanceCombinedAtom.ts
  apps/cowswap-frontend/src/modules/combinedBalances/updater/BalancesCombinedUpdater.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/hooks/useSwrConfigWithPauseForNetwork.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/balancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
  libs/balances-and-allowances/src/updaters/BalancesResetUpdater.ts
Labels: RELEASE

#5958 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
Labels: autorelease: pending

#5965 fix(bridge): better destination tokens filtering
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts
  apps/explorer/src/modules/bridge/hooks/useBridgeProviderBuyTokens.ts
  package.json
  yarn.lock
Labels: Bridge

#5969 feat(bridge): add disclaimer about third-party bridging features
  apps/cowswap-frontend/src/modules/bridge/constants.ts
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/SwapStepRow.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProgressDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/QuoteDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/RouteOverviewTitle/index.tsx
Labels: Bridge

#5951 fix(bridge): display pending swap in activities list
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeOverview.ts
  apps/cowswap-frontend/src/common/hooks/useSwapResultsContext.ts
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/BridgeSummaryHeader.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/SwapStepRow.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/StackedProtocolIcons.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/QuoteDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/FailedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/SwapResultContent/contents.tsx
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/hooks/useOrderProgressBarProps.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/OrderProgressBar/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
Labels: Bridge

#5973 feat(bridge): add bridging info to appData
  apps/cowswap-frontend/.env
  apps/cowswap-frontend/src/modules/appData/utils/fullAppData.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
  apps/cowswap-frontend/src/modules/twap/services/__snapshots__/createTwapOrderTxs.test.ts.snap
  apps/cowswap-frontend/src/modules/twap/services/createTwapOrderTxs.test.ts
  package.json
  yarn.lock
Labels: Bridge

#5961 feat(bridge): use stored bridge quotes in order progress bar
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/common/types/bridge.ts
  apps/cowswap-frontend/src/common/utils/calculateTargetAmountsBeforeBridging.ts
  apps/cowswap-frontend/src/entities/bridgeOrders/BridgeOrdersCleanUpdater.ts
  apps/cowswap-frontend/src/entities/bridgeOrders/bridgeOrderQuoteAtom.ts
  apps/cowswap-frontend/src/entities/bridgeOrders/index.ts
  apps/cowswap-frontend/src/entities/bridgeOrders/useAddBridgeOrderQuote.ts
  apps/cowswap-frontend/src/entities/bridgeOrders/useBridgeOrderQuote.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/index.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeQuoteAmounts.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useQuoteBridgeContext.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useQuoteSwapContext.ts
  apps/cowswap-frontend/src/modules/orderProgressBar/containers/OrderSubmittedContent.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/hooks/useOrderProgressBarProps.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/tradeFlow/types/TradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/TradeRateDetails/index.tsx
  libs/types/src/common.ts
Labels: Bridge

#5976 feat(bridge): add explorer URL to swap and bridge context
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/BridgeStepRow.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeDetailsContainer/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeTransactionLink/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProgressDetails/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TransactionLink/TransactionLinkDisplay.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/TransactionLink/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/PendingBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/ReceivedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/types.ts
Labels: Bridge

#5981 fix(bridge): adjust AnimatedEllipsis width
  apps/cowswap-frontend/src/modules/bridge/styles.ts
Labels: Bridge

#5985 fix(bridging): enhance account proxy validation
  apps/cowswap-frontend/src/modules/account/containers/CowShedInfo/index.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useQuoteSwapContext.ts
  apps/cowswap-frontend/src/modules/cowShed/containers/CoWShedWidget/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/InvalidCoWShedSetup/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/ProxyRecipient/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/RecoverFundsWidget/RecoverFundsButtons.tsx
  apps/cowswap-frontend/src/modules/cowShed/containers/RecoverFundsWidget/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/hooks/useCurrentAccountProxy.ts
  apps/cowswap-frontend/src/modules/cowShed/hooks/useCurrentAccountProxyAddress.ts
  apps/cowswap-frontend/src/modules/cowShed/hooks/useFetchTokenBalance.ts
  apps/cowswap-frontend/src/modules/cowShed/hooks/useRecoverFundsFromProxy.ts
  apps/cowswap-frontend/src/modules/cowShed/index.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/updaters/TradeFormValidationUpdater.ts
  libs/common-const/src/common.ts
Labels: Bridge

#5988 feat(bridge): lead to explorer bridge tab
  apps/cowswap-frontend/src/legacy/components/TransactionConfirmationModal/DisplayLink.tsx
  apps/cowswap-frontend/src/modules/orderProgressBar/pure/TransactionSubmittedContent/index.tsx
Labels: Bridge

#5987 fix(bridge): detect output token based on order source
  apps/cowswap-frontend/src/common/hooks/useBridgeOrderOutputToken.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeOverview.ts
  apps/cowswap-frontend/src/common/hooks/useSwapResultsContext.ts
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/account/pure/BridgeOrderLoading/index.tsx
Labels: Bridge

#5984 fix: do not multicall allowances globally
  apps/cowswap-frontend/src/common/hooks/useApproveState.ts
  apps/cowswap-frontend/src/common/hooks/useEnoughAllowance.ts
  apps/cowswap-frontend/src/common/hooks/useNeedsApproval.ts
  apps/cowswap-frontend/src/common/hooks/useTokenAllowance.ts
  apps/cowswap-frontend/src/common/types.ts
  apps/cowswap-frontend/src/common/updaters/LpBalancesAndAllowancesUpdater.tsx
  apps/cowswap-frontend/src/common/utils/getApprovalState.ts
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
  apps/cowswap-frontend/src/legacy/hooks/useTokenAllowance.ts
  apps/cowswap-frontend/src/legacy/state/enhancedTransactions/hooks/TransactionHooksMod.tsx
  apps/cowswap-frontend/src/lib/hooks/useApproval.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/usePendingTransactionsContext.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/services/finalizeEthereumTransaction.ts
  apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/types.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts
  apps/cowswap-frontend/src/modules/ordersTable/hooks/useBalancesAndAllowances.ts
  apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/TableGroup.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/WarningEstimatedPrice/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/types.ts
  apps/cowswap-frontend/src/modules/ordersTable/updaters/OrdersTableStateUpdater.ts
  apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.test.ts
  apps/cowswap-frontend/src/modules/ordersTable/utils/getOrderParams.ts
  apps/cowswap-frontend/src/modules/tokens/hooks/useBalancesAndAllowances.ts
  apps/cowswap-frontend/src/modules/tokens/hooks/useEnoughBalance.ts
  apps/cowswap-frontend/src/modules/tokens/index.ts
  apps/cowswap-frontend/src/modules/tokens/types.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useHasTradeEnoughAllowance.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx
  apps/cowswap-frontend/src/pages/Account/Tokens/TokensOverview.tsx
  apps/cowswap-frontend/src/pages/error/AnySwapAffectedUsers/useIsAnySwapAffectedUser.ts
  libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/hooks/useTokensAllowances.ts
  libs/balances-and-allowances/src/index.ts
  libs/balances-and-allowances/src/state/allowancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/balances-and-allowances/src/updaters/BalancesResetUpdater.ts
  libs/balances-and-allowances/src/updaters/PriorityTokensUpdater.ts
  libs/common-utils/src/isEnoughAmount.ts
Labels: Bridge

#6001 fix(trade): compare only selected metadata fields
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
Labels: preview-widget-cfg, Bridge

#6000 feat(bridge): enhance trade snackbars for bridge orders
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeOverview.ts
  apps/cowswap-frontend/src/common/pure/ClickableAddress/index.tsx
  apps/cowswap-frontend/src/entities/bridgeProvider/index.ts
  apps/cowswap-frontend/src/entities/bridgeProvider/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/modules/account/pure/BridgeOrderLoading/index.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useQuoteBridgeContext.ts
  apps/cowswap-frontend/src/modules/bridge/pure/TransactionLink/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/ReceivedBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/ethFlow/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/orders/containers/BridgingSuccessNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/OrderSummary/index.tsx
  apps/cowswap-frontend/src/modules/orders/pure/OrderSummary/summaryTemplates.tsx
  apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx
Labels: Bridge

#6007 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#6011 fix(time-offset): detect time in the past
  apps/cowswap-frontend/src/common/containers/InvalidLocalTimeWarning/index.tsx
Labels: RELEASE

#6015 fix(explorer): load coingecko tokens for all chains
  apps/explorer/src/hooks/useTokenList.ts
Labels: Bridge

#6017 feat(bridge): do not search output tokens in selector
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useAddTokenImportCallback.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItemContainer/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenSearchContent/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokensContent/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokensVirtualList/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  libs/tokens/src/hooks/tokens/useSearchToken.ts
Labels: Bridge

#5986 feat(bridge): enhance activity derived state for bridge orders
  .gitignore
  apps/cowswap-frontend/src/common/hooks/useBridgeOrderOutputToken.ts
  apps/cowswap-frontend/src/common/hooks/useEnhancedActivityDerivedState.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeContext.ts
  apps/cowswap-frontend/src/common/hooks/useSwapAndBridgeOverview.ts
  apps/cowswap-frontend/src/common/pure/IconSpinner/index.tsx
  apps/cowswap-frontend/src/common/types/activity.ts
  apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts
  apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx
  apps/cowswap-frontend/src/modules/account/containers/Transaction/StatusDetails.tsx
  apps/cowswap-frontend/src/modules/account/containers/Transaction/index.tsx
  apps/cowswap-frontend/src/modules/account/containers/Transaction/styled.ts
  apps/cowswap-frontend/src/modules/account/pure/BridgeOrderLoading/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/BridgeSummaryHeader.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/BridgingProgressContent/PreparingBridgingContent/index.tsx
  apps/cowswap-frontend/src/modules/bridge/updaters/PendingBridgeOrdersUpdater.tsx
Labels: Bridge

#6025 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#6019 fix(bridge): display chain name in token selector
  apps/cowswap-frontend/src/common/pure/CurrencySelectButton/index.tsx
Labels: Bridge

#6009 feat: add warning banner if bridge fees are over limit
  apps/cowswap-frontend/src/modules/swap/containers/SwapConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/HighFeeWarningTooltipContent.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/highFeeWarningHelpers.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/hooks/useHighFeeWarning.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/index.tsx
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/HighFeeWarning/styled.tsx
  libs/ui/src/pure/InlineBanner/InlineBanner/index.tsx
  libs/ui/src/pure/InlineBanner/InlineBanner/styled.ts
  libs/ui/src/pure/InlineBanner/shared/types.ts
Labels: Design, Bridge

#6032 fix(bridge): adjust success bridging message
  apps/cowswap-frontend/src/modules/orders/containers/BridgingSuccessNotification/index.tsx
  apps/cowswap-frontend/src/modules/orders/containers/OrderNotification/index.tsx
Labels: Bridge

#6021 feat(bridge): replace address links with AddressLink component for ow…
  apps/explorer/src/components/orders/DetailsTable/BaseDetailsTable.tsx
Labels: Bridge

#6037 fix: migrate tokens store from localStorage to indexedDB
  apps/cowswap-frontend/src/modules/application/containers/App/RoutesApp.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  apps/cowswap-frontend/src/pages/Swap/index.tsx
  libs/tokens/src/state/tokenLists/tokenListsActionsAtom.ts
  libs/tokens/src/state/tokenLists/tokenListsStateAtom.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.tsx
Labels: Bridge

#6029 feat(bridge): add bridging analytics
  apps/cowswap-frontend/src/common/analytics/types.ts
  apps/cowswap-frontend/src/modules/bridge/updaters/PendingBridgeOrdersUpdater.tsx
  apps/cowswap-frontend/src/modules/trade/utils/tradeFlowAnalytics.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
  libs/analytics/src/context/CowAnalyticsContext.tsx
  libs/analytics/src/gtm/CowAnalyticsGtm.ts
  libs/analytics/src/types.ts
  package.json
  yarn.lock
Labels: Bridge

#6048 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#6054 feat(bridge): add feature flag areUnsupportedChainsEnabled
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
Labels: Bridge

#6050 fix(bridge): wait 0.5s between hook and order signing
  apps/cowswap-frontend/src/modules/cowShed/hooks/useRecoverFundsFromProxy.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
  package.json
  yarn.lock
Labels: Bridge

#6056 fix(bridge): update protocol icons to use correct color scheme
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/StackedProtocolIcons.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/styled.tsx
  libs/ui/src/colors.ts
  libs/ui/src/enum.ts
  libs/ui/src/theme/ThemeColorVars.tsx
  libs/ui/src/theme/typings.ts
Labels: RELEASE, Bridge

#6059 fix(bridge): swap protocol icon colors for better contrast
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/StackedProtocolIcons.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/index.tsx
Labels: RELEASE

#6061 Revert "chore(release): hotfix 2025 07 30 (#6055)"
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeActivitySummary/BridgeSummaryHeader.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/BridgeRouteTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/StackedProtocolIcons.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/ProtocolIcons/styled.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/RouteOverviewTitle/index.tsx
  apps/cowswap-frontend/src/modules/bridge/pure/contents/QuoteBridgeContent/index.tsx
  apps/cowswap-frontend/src/modules/cowShed/hooks/useRecoverFundsFromProxy.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/trade/pure/ReceiveAmountTitle/index.tsx
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
  apps/explorer/src/components/common/AddressLink.tsx
  apps/explorer/src/components/orders/BridgeDetailsTable/BridgeDetailsContent/index.tsx
  apps/explorer/src/components/orders/BridgeDetailsTable/bridgeDetailsTooltips.tsx
  libs/multicall/src/hooks/useMultiCallRpcProvider.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/updaters/MultiCallUpdater.ts
  libs/ui/src/colors.ts
  libs/ui/src/enum.ts
  libs/ui/src/theme/ThemeColorVars.tsx
  libs/ui/src/theme/typings.ts
  libs/wallet/src/web3-react/connection/safe.tsx
  package.json
  yarn.lock
Labels: RELEASE

#6063 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/multicall/CHANGELOG.md
  libs/multicall/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending
