Repository cowprotocol/cowswap, pull requests merged in 2025-04, with the labels that each got.

#5585 fix: do not use RPC node when wallet is connected
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/multicall/src/hooks/useMultiCallRpcProvider.ts
  libs/multicall/src/index.ts
Labels: RELEASE

#5586 chore: release main
  .release-please-manifest.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/multicall/CHANGELOG.md
  libs/multicall/package.json
Labels: autorelease: pending

#5592 chore(release): 2025 04 02
  .github/workflows/ipfs.yml
  apps/cowswap-frontend/src/common/pure/CancellationModal/RequestCancellationModal.tsx
  apps/cowswap-frontend/src/modules/application/containers/PageTitle/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/styled.ts
  apps/cowswap-frontend/src/modules/twap/const.ts
  apps/cowswap-frontend/src/pages/Account/Tokens/TokensOverview.tsx
  apps/cowswap-frontend/src/pages/Account/index.tsx
  apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
  apps/cowswap-frontend/src/pages/Hooks/index.tsx
  apps/cowswap-frontend/src/pages/LimitOrders/index.tsx
  apps/cowswap-frontend/src/pages/Swap/index.tsx
  apps/cowswap-frontend/src/pages/Yield/index.tsx
  apps/cowswap-frontend/src/pages/games/CowRunner/index.tsx
  apps/cowswap-frontend/src/pages/games/MevSlicer/index.tsx
  libs/common-const/src/common.ts
  package.json
  yarn.lock
Labels: RELEASE

#5593 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5549 feat(trade): use Trading SDK in trade flows
  apps/cowswap-frontend/src/api/cowProtocol/api.ts
  apps/cowswap-frontend/src/cowSdk.ts
  apps/cowswap-frontend/src/legacy/utils/trade.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/ethFlow/hooks/useEthFlowContext.ts
  apps/cowswap-frontend/src/modules/ethFlow/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/ethFlow/services/ethFlow/steps/signEthFlowOrderStep.ts
  apps/cowswap-frontend/src/modules/ethFlow/types.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitOrdersFormState.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/pure/LimitOrdersDetails/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
  apps/cowswap-frontend/src/modules/limitOrders/updaters/QuoteObserverUpdater/index.tsx
  apps/cowswap-frontend/src/modules/operations/bundle/buildPresignTx.ts
  apps/cowswap-frontend/src/modules/trade/state/receiveAmountInfoAtom.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useSafeBundleFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts
  apps/cowswap-frontend/src/modules/tradeFlow/types/TradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/__snapshots__/useTradeQuotePolling.test.tsx.snap
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useProcessUnsupportedTokenError.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useQuoteParams.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteFeeFiatAmount.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.test.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  apps/cowswap-frontend/src/modules/tradeQuote/services/fetchAndProcessQuote.ts
  apps/cowswap-frontend/src/modules/tradeQuote/state/tradeQuoteAtom.ts
  apps/cowswap-frontend/src/modules/tradeQuote/types.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteDeadline.test.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteDeadline.ts
  apps/cowswap-frontend/src/modules/tradeQuote/utils/quoteUsingSameParameters.ts
  apps/cowswap-frontend/src/modules/twap/updaters/FullAmountQuoteUpdater.tsx
  apps/cowswap-frontend/src/modules/twap/updaters/QuoteObserverUpdater.tsx
  apps/cowswap-frontend/src/tradingSdk/TradingSdkUpdater.ts
  apps/cowswap-frontend/src/tradingSdk/tradingSdk.ts
  package.json
  yarn.lock
Labels: preview-widget-cfg, Bridge

#5636 fix: update links on limit orders page
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/pure/InfoBanner/index.tsx
Labels: RELEASE

#5642 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
Labels: autorelease: pending
