Repository cowprotocol/cowswap, pull requests merged in 2025-02, with the labels that each got.

#5372 feat: display Metamask warning in widget
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/MetamaskTransactionWarning/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts
  libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts
  libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts
  libs/iframe-transport/src/iframeRpcProvider/utils.ts
  libs/iframe-transport/src/types.ts
  libs/types/src/eip6963-types.ts
  libs/types/src/index.ts
  libs/wallet/src/api/state/multiInjectedProvidersAtom.ts
  libs/wallet/src/api/types.ts
  libs/wallet/src/web3-react/connection/injectedOptions.tsx
  libs/wallet/src/web3-react/connectors/Injected/index.tsx
Labels: RELEASE, preview-widget-cfg

#5370 fix: display Metamask warning only for extension/mobile wallets
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/MetamaskTransactionWarning/index.tsx
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  libs/iframe-transport/src/iframeRpcProvider/IframeRpcProviderBridge.ts
  libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts
  libs/iframe-transport/src/iframeRpcProvider/iframeRpcProviderEvents.ts
  libs/iframe-transport/src/iframeRpcProvider/utils.ts
  libs/iframe-transport/src/types.ts
  libs/types/src/eip6963-types.ts
  libs/types/src/index.ts
  libs/wallet/src/api/hooks.ts
  libs/wallet/src/api/state/multiInjectedProvidersAtom.ts
  libs/wallet/src/api/types.ts
  libs/wallet/src/web3-react/connection/injectedOptions.tsx
  libs/wallet/src/web3-react/connectors/Injected/index.tsx
Labels: RELEASE

#5375 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/iframe-transport/CHANGELOG.md
  libs/iframe-transport/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5373 chore: fix limit orders isUnlocked state
  apps/cowswap-frontend/src/modules/limitOrders/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/updaters/PromoBannerUpdater.tsx
  apps/cowswap-frontend/src/modules/trade/containers/LimitOrdersPromoBannerWrapper/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useLimitOrdersPromoBanner.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/pages/LimitOrders/index.tsx
Labels: preview-widget-cfg, Limit orders upgrade

#5356 fix(limit-orders): update price and amounts when tokens changed
  apps/cowswap-frontend/src/modules/limitOrders/updaters/SetupLimitOrderAmountsFromUrlUpdater.tsx
Labels: Limit orders upgrade

#5344 fix(orders-table): approve USDT
  apps/cowswap-frontend/src/common/containers/TradeApprove/TradeApproveButton.tsx
  apps/cowswap-frontend/src/common/hooks/useApproveCallback.ts
  apps/cowswap-frontend/src/common/hooks/useApproveCurrency.ts
  apps/cowswap-frontend/src/common/pure/ApproveButton/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.test.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useNeedsZeroApproval.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/shouldZeroApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useZeroApprove.ts
  libs/common-const/src/tokens.ts
  libs/ui/src/pure/Loader/index.tsx
Labels: Limit orders upgrade

#5387 fix: reset token approval warning banner when sell amount is less tha…
  apps/cowswap-frontend/src/modules/zeroApproval/hooks/useShouldZeroApprove/useShouldZeroApprove.ts
Labels: RELEASE

#5385 fix(limit-orders): do not display rate input when wrap/unwrap
  apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/index.tsx
Labels: RELEASE

#5390 fix(orders-table): prevent excessive transactions on approvals
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts
Labels: RELEASE

#5393 fix(safe-app): remove approval+order placement bundling recommendation
  apps/cowswap-frontend/src/modules/trade/containers/TradeWarnings/index.tsx
  libs/widget-lib/src/types.ts
Labels: RELEASE

#5394 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/assets/CHANGELOG.md
  libs/assets/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#5407 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5412 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5420 chore(release): 2025 02 11
  apps/cowswap-frontend/src/common/hooks/useConfirmPriceImpactWithoutFee.ts
  apps/cowswap-frontend/src/common/hooks/useIsSafeApprovalBundle.ts
  apps/cowswap-frontend/src/common/services/logEthSendingTransaction.ts
  apps/cowswap-frontend/src/cow-react/sentry/events.ts
  apps/cowswap-frontend/src/cow-react/sentry/index.ts
  apps/cowswap-frontend/src/legacy/components/swap/confirmPriceImpactWithoutFee.ts
  apps/cowswap-frontend/src/legacy/hooks/useWrapCallback.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.test.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useSafeBundleFlowContext.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts
  apps/cowswap-frontend/src/modules/limitOrders/services/types.ts
  apps/cowswap-frontend/src/modules/ordersTable/containers/OrderRow/EstimatedExecutionPrice.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrderStatusBox/index.tsx
  apps/cowswap-frontend/src/modules/ordersTable/pure/OrdersTableContainer/styled.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapButtonContext.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts
  apps/cowswap-frontend/src/modules/swap/services/ethFlow/steps/signEthFlowOrderStep.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useIsSafeEthFlow.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useWrapNativeFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useSafeBundleFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleApprovalFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/services/safeBundleFlow/safeBundleEthFlow.ts
  apps/cowswap-frontend/src/modules/tradeFlow/types/TradeFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeWidgetAddons/containers/BundleTxWrapBanner/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/index.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWarnings/warnings/UnsupportedWalletWarning.tsx
  apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useAllEmulatedOrders.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useCancelTwapOrder.ts
  apps/cowswap-frontend/src/modules/twap/hooks/useCreateTwapOrder.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useTwapFormState.ts
  apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/getTwapFormState.test.ts
  apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/getTwapFormState.tsx
  apps/cowswap-frontend/src/modules/twap/pure/PrimaryActionButton/index.tsx
  apps/cowswap-frontend/src/modules/twap/updaters/index.tsx
  apps/explorer/src/components/common/DateDisplay/index.tsx
  apps/explorer/src/components/orders/OrderHooksDetails/HookItem/styled.tsx
  libs/core/src/gnosisSafe/index.ts
  libs/wallet/src/api/hooks.ts
  libs/wallet/src/api/hooks/useSendBatchTransactions.ts
  libs/wallet/src/api/hooks/useWalletCapabilities.ts
  libs/wallet/src/index.ts
  package.json
  patches/@walletconnect+universal-provider+2.10.2.patch
  yarn.lock
Labels: RELEASE, preview-widget-cfg

#5433 Release 2025-02-17
  apps/cowswap-frontend/src/common/constants/banners.ts
  apps/cowswap-frontend/src/common/containers/CoWAmmBanner/index.tsx
  apps/cowswap-frontend/src/common/hooks/useCancelOrder/useSendOnChainCancellation.test.tsx
  apps/cowswap-frontend/src/legacy/components/Header/URLWarning/index.tsx
  apps/cowswap-frontend/src/legacy/components/SideMenu/index.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTable.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/styled.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/twap/containers/SetupFallbackHandlerWarning/index.tsx
  apps/cowswap-frontend/src/modules/twap/hooks/useFallbackHandlerVerification.ts
  apps/cowswap-frontend/src/modules/twap/services/verifyExtensibleFallback.ts
  apps/cowswap-frontend/src/modules/twap/updaters/FallbackHandlerVerificationUpdater.tsx
  apps/cowswap-frontend/src/modules/volumeFee/index.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/correlatedTokensAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/taxFreeAssetsAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/state/volumeFeeAtom.ts
  apps/cowswap-frontend/src/modules/volumeFee/updaters/CorrelatedTokensUpdater.tsx
  apps/cowswap-frontend/src/pages/Account/Balances.tsx
  apps/cowswap-frontend/src/pages/Account/Delegate.tsx
  apps/cowswap-frontend/src/pages/Account/Governance.tsx
  apps/cowswap-frontend/src/pages/Account/Tokens/TokensOverview.tsx
  apps/cowswap-frontend/src/pages/Account/Tokens/styled.ts
  apps/cowswap-frontend/src/pages/Account/constants.ts
  apps/cowswap-frontend/src/pages/Account/index.tsx
  apps/cowswap-frontend/src/pages/Account/styled.tsx
  apps/cowswap-frontend/src/pages/AdvancedOrders/index.tsx
  libs/assets/src/cow-swap/delegate-cow.svg
  libs/ui/src/pure/ClosableBanner/constants.ts
  libs/ui/src/pure/ClosableBanner/index.tsx
  libs/wallet/src/api/hooks/useWalletCapabilities.ts
  package.json
  yarn.lock
Labels: RELEASE

#5434 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5445 refactor: remove legacy price strategies
  apps/cowswap-frontend/src/api/1inch/index.ts
  apps/cowswap-frontend/src/api/cowProtocol/priceApi.ts
  apps/cowswap-frontend/src/api/matcha-0x/index.ts
  apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts
  apps/cowswap-frontend/src/legacy/hooks/useGetGpPriceStrategy.ts
  apps/cowswap-frontend/src/legacy/state/gas/atoms.ts
  apps/cowswap-frontend/src/legacy/state/gas/gas-price-strategy-updater.tsx
  apps/cowswap-frontend/src/legacy/state/index.ts
  apps/cowswap-frontend/src/legacy/state/price/actions.ts
  apps/cowswap-frontend/src/legacy/state/price/hooks.ts
  apps/cowswap-frontend/src/legacy/state/price/middleware.ts
  apps/cowswap-frontend/src/legacy/state/price/reducer.ts
  apps/cowswap-frontend/src/legacy/state/price/types.ts
  apps/cowswap-frontend/src/legacy/utils/price.ts
  apps/cowswap-frontend/src/legacy/utils/priceLegacy.ts
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
Labels: Swap unification

#5450 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
Labels: autorelease: pending

#5458 refactor(ui): improve GlobalWarning component styling and responsiveness
  apps/cowswap-frontend/src/common/pure/GlobalWarning/index.tsx
Labels: RELEASE

#5456 fix(twap): migrate to new Safe api for orders history
  apps/cowswap-frontend/src/modules/twap/hooks/useFetchTwapOrdersFromSafe.ts
  apps/cowswap-frontend/src/modules/twap/pure/CustomDeadlineSelector/index.tsx
  apps/cowswap-frontend/src/modules/twap/services/fetchTwapOrdersFromSafe.ts
  package.json
  yarn.lock
Labels: RELEASE

#5460 feat(cow-fi): update base token reward T&C
  apps/cow-fi/app/(main)/legal/cowswap-terms/page.tsx
Labels: RELEASE

#5459 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5466 chore: release main
  .release-please-manifest.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
Labels: autorelease: pending
