Repository cowprotocol/cowswap, pull requests merged in 2025-03, with the labels that each got.

#5462 Add clickable token address
  README.md
  apps/cowswap-frontend/src/common/pure/ClickableAddress/index.tsx
  apps/cowswap-frontend/src/common/pure/ClickableAddress/styled.ts
  apps/cowswap-frontend/src/legacy/components/Copy/CopyMod.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenInfo/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/styled.ts
Labels: preview-widget-cfg

#5477 fix(appzi): remove open state styles
  apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx
Labels: RELEASE

#5478 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5484 fix(swap): approve amount must always be after slippage
  apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersDerivedState.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useLimitOrdersDerivedState.ts
  apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/types/ReceiveAmountInfo.ts
  apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/utils/getReceiveAmountInfo.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useSafeBundleFlowContext.ts
  apps/cowswap-frontend/src/modules/tradeFlow/hooks/useTradeFlowType.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormButtonContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/hooks/useTradeFormValidationContext.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/pure/TradeFormButtons/tradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/tradeFormValidation/types.ts
  apps/cowswap-frontend/src/modules/yield/hooks/useYieldDerivedState.ts
Labels: RELEASE

#5488 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5485 fix(swap): update quote in confirm screen
  apps/cowswap-frontend/src/modules/ethFlow/containers/EthFlow/hooks/useEthFlowActions.ts
  apps/cowswap-frontend/src/modules/swap/containers/SwapConfirmModal/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/SwapWidget/index.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetUpdaters.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/useOnCurrencySelection.ts
  apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/CountDown.tsx
  apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/index.tsx
  apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts
  apps/cowswap-frontend/src/modules/tradeQuote/updaters/TradeQuoteUpdater/index.tsx
  apps/cowswap-frontend/src/modules/yield/containers/YieldWidget/index.tsx
Labels: RELEASE

#5494 fix(swap): disable button when costs warning is not accepted
  apps/cowswap-frontend/src/modules/swap/containers/TradeButtons/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeButtons/swapTradeButtonsMap.tsx
  apps/cowswap-frontend/src/modules/swap/containers/Warnings/index.tsx
Labels: RELEASE

#5496 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5489 feat(bridge): display tokens in selector from bridge provider
  apps/cowswap-frontend/src/common/pure/ClickableAddress/index.tsx
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeProvider.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/bridge/index.ts
  apps/cowswap-frontend/src/modules/bridge/mocks.ts
  apps/cowswap-frontend/src/modules/bridge/state/bridgeProviderAtom.ts
  apps/cowswap-frontend/src/modules/bridge/types.ts
  apps/cowswap-frontend/src/modules/hooksStore/containers/HookSearchInput/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/RecoverFundsFromProxy/index.tsx
  apps/cowswap-frontend/src/modules/hooksStore/pure/AddCustomHookForm/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOnSelectChain.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useSourceChainId.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/index.ts
  apps/cowswap-frontend/src/modules/tokensList/mocks.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/styled.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/commonElements.ts
  apps/cowswap-frontend/src/modules/tokensList/state/selectTokenWidgetAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  libs/balances-and-allowances/src/hooks/useNativeCurrencyAmount.ts
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/common-const/src/networks.ts
  libs/common-utils/src/getIsNativeToken.ts
  libs/multicall/src/hooks/useMultiCallRpcProvider.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/hooks/useSingleContractMultipleData.ts
  libs/multicall/src/index.ts
  libs/multicall/src/multicall.ts
  libs/multicall/src/state/multiCallContextAtom.ts
  libs/multicall/src/updaters/MultiCallUpdater.ts
  libs/multicall/src/utils/getMulticallContract.ts
  libs/types/src/common.ts
  libs/ui/src/pure/Input/index.tsx
  libs/ui/src/pure/Tooltip/index.tsx
Labels: Bridge

#5508 refactor: enhance ChainsSelector component and styles
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/styled.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/styled.ts
Labels: Bridge

#5509 feat(bridge): do not fetch balances too often
  apps/cowswap-frontend/src/common/updaters/orders/OrdersFromApiUpdater.ts
  apps/cowswap-frontend/src/modules/bridge/mocks.ts
  apps/cowswap-frontend/src/modules/combinedBalances/state/balanceCombinedAtom.ts
  apps/cowswap-frontend/src/modules/combinedBalances/updater/BalancesCombinedUpdater.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useTokensToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/pages/error/AnySwapAffectedUsers/useIsAnySwapAffectedUser.ts
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
  libs/balances-and-allowances/src/hooks/useSwrConfigWithPauseForNetwork.ts
  libs/balances-and-allowances/src/state/balancesAtom.ts
  libs/balances-and-allowances/src/updaters/BalancesAndAllowancesUpdater.tsx
  libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx
  libs/balances-and-allowances/src/updaters/PriorityTokensUpdater.ts
  libs/multicall/src/hooks/useMultiCallRpcProvider.ts
  libs/multicall/src/hooks/useMultipleContractSingleData.ts
  libs/multicall/src/hooks/useSingleContractMultipleData.ts
  libs/tokens/src/hooks/tokens/useAllActiveTokens.ts
  libs/tokens/src/hooks/tokens/useAllLpTokens.ts
  libs/tokens/src/hooks/tokens/useSearchToken.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
Labels: Bridge

#5516 fix(wallets): disable coinbase in widget mobile
  apps/cowswap-frontend/src/modules/wallet/containers/ConnectWalletOptions.tsx
  apps/widget-configurator/src/app/configurator/hooks/useWidgetParamsAndSettings.ts
  libs/common-utils/src/environments.ts
  libs/wallet/src/web3-react/connection/coinbase.tsx
  package.json
  yarn.lock
Labels: preview-widget-cfg

#5511 feat(bridge): add network logo token icon
  apps/cowswap-frontend/src/modules/application/containers/App/Updaters.tsx
  apps/cowswap-frontend/src/modules/bridge/mocks.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useChainsToSelect.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useSourceChainId.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/ChainsSelector/index.tsx
  libs/tokens/src/hooks/tokens/useNetworkLogo.ts
  libs/tokens/src/pure/TokenLogo/index.tsx
  libs/tokens/src/state/environmentAtom.ts
  libs/tokens/src/updaters/TokensListsUpdater/index.ts
  libs/types/src/common.ts
Labels: Bridge

#5524 chore: fix broken unit tests
  libs/common-utils/src/environments.test.ts
Labels: preview-widget-cfg

#5521 feat(bridge): select sell token from another chain
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/legacy/components/Tokens/TokensTableRow.tsx
  apps/cowswap-frontend/src/modules/hooksStore/containers/RecoverFundsFromProxy/index.tsx
  apps/cowswap-frontend/src/modules/swap/containers/TradeButtons/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOpenTokenSelectWidget.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useSourceChainId.ts
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.cosmos.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/SelectTokenModal/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/pure/TokenListItem/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/state/selectTokenWidgetAtom.ts
  apps/cowswap-frontend/src/modules/tokensList/types.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useResetStateWithSymbolDuplication.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useAutoImportTokensState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNavigateOnCurrencySelection.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useOnCurrencySelection.ts
  libs/tokens/src/hooks/tokens/useAreThereTokensWithSameSymbol.ts
  libs/tokens/src/hooks/tokens/useTokenBySymbolOrAddress.ts
  libs/tokens/src/state/tokens/allTokensAtom.ts
  libs/tokens/src/types.ts
  libs/wallet/src/web3-react/hooks/useSwitchNetwork.ts
Labels: Bridge

#5522 feat(bridge): select buy token from another chain
  apps/cowswap-frontend/src/modules/application/containers/App/index.tsx
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeSupportedNetworks.ts
  apps/cowswap-frontend/src/modules/bridge/hooks/useBridgeSupportedTokens.ts
  apps/cowswap-frontend/src/modules/tokensList/containers/SelectTokenWidget/index.tsx
  apps/cowswap-frontend/src/modules/tokensList/hooks/useCloseTokenSelectWidget.ts
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOpenTokenSelectWidget.ts
  apps/cowswap-frontend/src/modules/tokensList/state/selectTokenWidgetAtom.ts
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidgetLinks/index.tsx
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts
  apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useTradeStateFromUrl.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useGetTradeUrlParams.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useIsCurrentTradeBridging.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useNavigateOnCurrencySelection.ts
  apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts
  apps/cowswap-frontend/src/modules/trade/index.ts
  apps/cowswap-frontend/src/modules/trade/types/TradeRawState.ts
  apps/cowswap-frontend/src/modules/trade/utils/parameterizeTradeRoute.ts
  apps/cowswap-frontend/src/modules/trade/utils/parameterizeTradeSearch.ts
Labels: Bridge

#5523 feat(widget): allow passing targetChainId for bridge
  libs/widget-lib/src/types.ts
  libs/widget-lib/src/urlUtils.ts
Labels: preview-widget-cfg, Bridge

#5534 chore: release main
  .release-please-manifest.json
  apps/cow-fi/CHANGELOG.md
  apps/cow-fi/package.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/widget-configurator/CHANGELOG.md
  apps/widget-configurator/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/hook-dapp-lib/CHANGELOG.md
  libs/hook-dapp-lib/package.json
  libs/multicall/CHANGELOG.md
  libs/multicall/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/types/CHANGELOG.md
  libs/types/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
Labels: autorelease: pending

#5539 Release 2025-03-24
  apps/cowswap-frontend/src/modules/advancedOrders/containers/AdvancedOrdersSettings/index.tsx
  apps/cowswap-frontend/src/modules/advancedOrders/pure/Settings/index.tsx
  apps/cowswap-frontend/src/modules/limitOrders/containers/SettingsWidget/index.tsx
  apps/cowswap-frontend/src/modules/swap/hooks/useSwapSettings.ts
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
  libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts
Labels: RELEASE

#5540 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
Labels: autorelease: pending

#5525 feat(bridge): add chain name in currency selector
  apps/cowswap-frontend/src/common/pure/CurrencyInputPanel/CurrencyInputPanel.tsx
  apps/cowswap-frontend/src/common/pure/CurrencySelectButton/index.tsx
  apps/cowswap-frontend/src/common/pure/CurrencySelectButton/styled.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetForm.tsx
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/types.ts
Labels: Bridge

#5545 fix: do not ask apporval for native sell token
  apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts
Labels: RELEASE

#5546 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending

#5532 feat: move inside a popup "copy address" and "view details"
  apps/cowswap-frontend/src/common/pure/ClickableAddress/Content.tsx
  apps/cowswap-frontend/src/common/pure/ClickableAddress/index.tsx
  apps/cowswap-frontend/src/common/pure/ClickableAddress/styled.ts
  apps/cowswap-frontend/src/legacy/components/Copy/CopyMod.tsx
  libs/common-hooks/src/index.ts
  libs/common-hooks/src/useOnScroll.tsx
  libs/ui/src/colors.ts
  libs/ui/src/pure/Tooltip/index.tsx
Labels: preview-widget-cfg

#5561 fix(bridge): ignore buy token selection when bridging is not enabled
  apps/cowswap-frontend/src/modules/tokensList/hooks/useOpenTokenSelectWidget.ts
Labels: RELEASE, Bridge

#5565 chore: fix app crash in getIsNativeToken
  libs/common-utils/src/getIsNativeToken.ts
Labels: RELEASE

#5566 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  libs/analytics/CHANGELOG.md
  libs/analytics/package.json
  libs/common-hooks/CHANGELOG.md
  libs/common-hooks/package.json
  libs/common-utils/CHANGELOG.md
  libs/common-utils/package.json
  libs/events/CHANGELOG.md
  libs/events/package.json
  libs/tokens/CHANGELOG.md
  libs/tokens/package.json
  libs/ui/CHANGELOG.md
  libs/ui/package.json
  libs/wallet/CHANGELOG.md
  libs/wallet/package.json
  libs/widget-lib/CHANGELOG.md
  libs/widget-lib/package.json
Labels: autorelease: pending

#5572 fix(balances): updated balances on network changes (#5569)
  apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/TradeWidgetModals.tsx
  libs/balances-and-allowances/src/hooks/useNativeTokenBalance.ts
  libs/balances-and-allowances/src/hooks/useSwrConfigWithPauseForNetwork.ts
  libs/common-const/src/networks.ts
Labels: RELEASE

#5573 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
  libs/balances-and-allowances/CHANGELOG.md
  libs/balances-and-allowances/package.json
  libs/common-const/CHANGELOG.md
  libs/common-const/package.json
Labels: autorelease: pending

#5581 fix(safe-app-fee): replace Safe App Fee recipient address
  apps/cowswap-frontend/src/modules/volumeFee/state/safeAppFeeAtom.ts
Labels: RELEASE

#5583 chore: release main
  .release-please-manifest.json
  apps/cowswap-frontend/CHANGELOG.md
  apps/cowswap-frontend/package.json
Labels: autorelease: pending
